### ISSUE TITLE
Simulation imported from PKML has an "out of sync" symbol

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1000]
- Export any simulation with PK-Sim V11.2 to pkml
- Open Simulation created with V11.2 in MoBi OSMOSES
- The simulation has a red light:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/d0e6318e-f23e-4a6d-a88f-5f622ea2541f)

**Comment by rwmcintosh** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/MoBi/issues/1052
