### ISSUE TITLE
Double-click on a module opens "Add building blocks" dialogue

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1001]
I would not expect this, do you think this is intuitive and something that a user would expect?

**Comment by msevestre** [comment]
No this should not be like this. It typically opens the first entry of the popup menu which is edit. But we have no edit at this stage. Probably double click should do nothing in this case

**Comment by rwmcintosh** [comment]
> Probably double click should do nothing in this case

I'll make it toggle the node expand state like it does for folders
