### ISSUE TITLE
Combining modules - adding a new container

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1035]
-	Load “simple.pkml” simulation
-	Create new module “BrainModule” with “Spatial Structure” BB
-	Change “Organism” to “logical container”
-	Add a new “Organ -> Physical container” “Brain” to “Organism”
-	Set “Parent path” of container “Organism” in module “BrainModule” to “Organism”

Create a new simulation, selecting "simple" first and "Brain module" second:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/341d2818-d661-4c0c-9d0e-987c12cdf6a1)

## Expected behavior
A simulation is created with the containers "Organism|Brain" located under "Organism|Liver" of the "simple" module.

## Current behavior
Only "Organism|Brain" structure is present:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/b9d2771b-1012-48c3-b469-bd22121bcb41)

**Comment by msevestre** [comment]
@PavelBal Is there a way to make screenshots that are not so big? It makes reading this issue very difficult

**Comment by msevestre** [comment]
@PavelBal Why do you have an organism in your new structure? It should only have brain IMO

**Comment by msevestre** [comment]
>Set “Parent path” of container “Organism” in module “BrainModule” to “Organism”

This does not make sense. Why would you want to have Organism under Organism?

**Comment by msevestre** [comment]
Can you attach the project please?

**Comment by PavelBal** [comment]
> This does not make sense. Why would you want to have Organism under Organism?

I didn't say it should make sense xD

But I realized that I did an mistake and assigned the "Parent path" in the wrong module, so the issue is not valid, sorry.

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/OSMOSES/src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs#L96
I checked the code and it should work as expected. Can't reproduce, at least mentally

**Comment by msevestre** [comment]
oh ok
