### ISSUE TITLE
Combining modules - molecules not created in new containers

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1036]
Sorry for screenshot size, no idea how to change this (Windows scaling problem)

- Load “simple.pkml” simulation
- Create new module “BrainModule” with “Spatial Structure” BB
- Delete the top container “Organism”
- Add a new top container “Organ -> Physical container” “Brain” to the module
- Set “Parent path” of container “Brain” in module “BrainModule” to “Organism|Liver”
- Create a new simulation, selecting "simple" first and "Brain module" second:

## Current behavior:
-
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/c47a282e-5e4f-4c91-97ef-a29e72b28ebf)

- No molecules are created in the "Brain" container

## Expected behavior:
- As no IC for `Organism|Liver|Brain|A` and `Organism|Liver|Brain|B` are defined, these molecules are present in the new container with initial values as defined in the Molecules-BB.

**Comment by msevestre** [comment]
>As no IC for Organism|Liver|Brain|A and Organism|Liver|Brain|B are defined, these molecules are present in the new container with initial values as defined in the Molecules-BB.

I don't get this. If there is no IC, why would they be present. This is not how it's implemented at all at the moment

**Comment by PavelBal** [comment]
21.06.2023: this is by default and the easier implementation. Keep as is (== if there is no entry for the molecule/container combination in any IC, the molecule is not created in this container).

Note: this behavior is different from what is implemented now.
