### ISSUE TITLE
"Extend" of IC

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1037]
- Load “simple.pkml” simulation
- Create new module “BrainModule” with “Spatial Structure” BB
- Delete the top container “Organism”
- Add a new top container “Organ -> Physical container” “Brain” to the module
- Set “Parent path” of container “Brain” in module “BrainModule” to “Organism|Liver”

- Create a new IC BB in the module "BrainModule"
- Click "Extend"

## Current behavior
- Nothing happens

## Expected behavior

- The user select one Spatial Structure - BB (from any module) and one Molecules BB (from any module). IC entries for this combination are created. By default, all present (?), initial values are taken from the molecules BB.

**Comment by rwmcintosh** [comment]
Do we implement a separate 'extend' for initial conditions in expression profile building blocks?

**Comment by msevestre** [comment]
In this cases, you'd only select a spatial structure
The molecule is already known

**Comment by rwmcintosh** [comment]
And then in this IC building block extend, we should exclude builders with ```QuantityType == QuantityType.Protein```

**Comment by msevestre** [comment]
do you mean molecules from the moleculeBuildingBlock? Why are they in the Molecule BB in the first place? is this required? Maybe for reaction building I guess

**Comment by msevestre** [comment]
but then yes, needs to be removed
