### ISSUE TITLE
How to deal with Commit/update logic

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#1050]
Just notes from our discussion

# Display of changes

##  Changes in the simulation

* We create a new ParameterValueTracker (PVT) object in each simulation (similar to a ParameterValue but with the knowledge of the original value). 
==> For example, A|B|P1 was changed from 1 to 2 and then from 2 to 3, this entry would have OriginalValue: 1 and current value. Alternatively, it only stores the original values 
* TODO: How to deal with Formula being overwritten to a constant in the simulation? Probably need to saved the fact that it was a formula and then set IsFixedValue = false upon reset

## Changes in building blocks (Modules and/or Expression Profile and Individual)

* An event is raised already (probably) which will trigger a refresh of the tree structure (icons mostly).
* The logic below will then be applied (see what is red/green)

## What is marked as Green/Red

When is a simulation Red:
1. There is an entry in the PVT 
2. One building block used (e.g from module(s) or Ind or ExpPr has a different version than the one at time of creation). In this case, the simulation is RED **AND** the BB in the simulation tree (maybe even the module icon)

When is a simulation Green:
1. PVT is empty
2. versions of all used building blocks are the same as the Template BuildingBlock and there is no new required building block added to any of the used module => It's ok to add a PV or IC to a module as these are optional selection and would not affect the simulation

# How do we update

## Change in the simulation

* We can commit the changes (PVT) to a module (either a new one or maybe an existing one) and this module will only have one PV containing all changes made in the simulation based on the PVT

## Change in a building block

* I don't think we can simply update a value as we used to (because of order of updates, dependencies etc..). A suggestion would be to always start a CONFIGURE action where all building blocks would be updated.  We need to reapply  the PVT after the reconfiguration

=> drawback. This will be a longer process as we have now as we will reconfigure the simulation all the time. BUT WE WILL BE ABLE TO TRUST the outcome :)

**Comment by msevestre** [comment]
@PavelBal @Yuri05 @stephanschaller

Please feedback

**Comment by PavelBal** [comment]
- There is an entry in the PVT
  - In this case the simulation is red, but do we also show which BB is red? Probably we cannot, because the parameter of questions (or the start value of the molecule) could be present in multiple modules.

Maybe we should show two different changed states:
1) BB version has changed -> Highlight the BB in the simulation, with the possible action to "Update" (== reconfigure)
2) Value in the simulation has been changed (there is an entry in the PVT) -> Show a slightly different icon on the simulation "Parameter overwritten", with the possible action "Commit to PV"
  - Commit to PV of the last module? What if there is no PV in any of the modules?
  - Commit to new PV?
  - Show a selection of modules? Maybe this would be the best option. This would require one additional step from the user, but also prevent from accidental commits (happens to me from time to time)

- Remark to "Reconfigure" - I would propose that when "Reconfigure" is triggered from the "update" action, do not show the UI.

**Comment by Yuri05** [comment]
> * I don't think we can simply update a value as we used to (because of order of updates, dependencies etc..). A suggestion would be to always start a CONFIGURE action where all building blocks would be updated.  We need to reapply  the PVT after the reconfiguration

I don't quite get it: why is the "simple" update not possible?

**Comment by msevestre** [comment]
>In this case the simulation is red, but do we also show which BB is red? Probably we cannot, because the parameter of questions (or the start value of the molecule) could be present in multiple modules.

This is the problem. Before, a value was really coming from one source of truth, with sometimes PSV being mixed in the way which made it very hard to see what was happening (but we had some logic to see it this in PSV, yes, update PSV or it comes from a specific BB). 

Now this is completely different. We can have multiple source for one parameter and only the latest one wins so to speak

>Maybe we should show two different changed states:

I don't think we need to differentiate between different changed state. changed is confusing enough lol. 


re: 


> Commit to PV of the last module? What if there is no PV in any of the modules?

> Commit to new PV?

All of this should be discussed. Either to a new PV or to a new module with a PV only that is applied last. WE could also look check if the latest module only has a PV and  in this case, we use this one otherwise we create one

> Show a selection of modules? Maybe this would be the best option. This would require one additional step from the user, but also prevent from accidental commits (happens to me from time to time)

I don't think it's good because it needs to be applied to the one use LAST otherwise you won't have the same results upon recreating the simulation with the same BB


> Remark to "Reconfigure" - I would propose that when "Reconfigure" is triggered from the "update" action, do not show the UI.

Probably fine now provided that we ALWAYS UPDATE ALL BUILDING BLOCKS and not only the one that has changed. In general, I would prevent update at the BB level because that does not make much sense with the module concept

**Comment by msevestre** [comment]
>I don't quite get it: why is the "simple" update not possible?

SImple update is not possible because the same value can come from multiple sources. Before, it was a 1-1 mapping. now we have multiple potential modules, all defining potentially the same parameter. So unless we keep track of the  very parameter that created the value (e.g. doing sthg with id like we do in PKSIm which is very complicated), there is no easy way to know if the value of a building block is indeed use in the simulation. One would have to reapply all the module logic somehow to see if A|B|P1 from module 1  is used in a simulation or not.
Or maybe you have a better id ? Doing what we do in PKSim took lots of time and I don't think it's worth the effort

**Comment by msevestre** [comment]
>Especially if the changed BB is more or less just a list of parameters (like individual or expression profile etc.)

This is the only exception **maybe** because we are back to a 1 to 1. That being said, they are also not applied last so that i also not quite clear if changing a parameter from 1 to 2 will result in the value 2 being used in the simulation. But this is IMO the only BB for which this can  be done

**Comment by Yuri05** [comment]
> SImple update is not possible because the same value can come from multiple sources. Before, it was a 1-1 mapping. now we have multiple potential modules, all defining potentially the same parameter. So unless we keep track of the very parameter that created the value (e.g. doing sthg with id like we do in PKSIm which is very complicated), there is no easy way to know if the value of a building block is indeed use in the simulation. One would have to reapply all the module logic somehow to see if A|B|P1 from module 1 is used in a simulation or not.
> Or maybe you have a better id ? Doing what we do in PKSim took lots of time and I don't think it's worth the effort

OK, I see. 
One possibility could be: go through the list of modules used for simulation creation top down and apply the parameter change to the first module where this parameter was found. 
E.g. if the modules order during simulation creation was "M1 ⬅️ M2 ⬅️ M3": then look in M3 first; if not found: look in M2; if not found: look in M1.
But not sure if we really need something like this and if it would not become too confusing for the user.

**Comment by msevestre** [comment]
I am completely against thid proposal. This is not transparent and very confusing. This is also the COMMIT logic that you are describing. For me, this was clear we would NOT do this. The problem is for the UPDATE logic (bb => Sim) where this is also not possible easily.

**Comment by rwmcintosh** [comment]
I think this one is over.
