### ISSUE TITLE
Expression profile: Initial conditions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1076]
1) We cannot add or delete new entries in the "Parameters" tab, but can delete entries in the "Initial conditions" tab. I think the latter should also be not modifiable.

2) I would propose to hide the "Is Present" column
3) Also remove the "Value Origin" column
4) Rename column "Initial condition" to "Value"

**Comment by rwmcintosh** [comment]
Just making sure - this is only when the view is shown for Expression Profile right?

**Comment by rwmcintosh** [comment]
This should go in the edit ribbon - both buttons not required
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/8c3ea5f9-ea75-4636-804a-04dd3c4ada3d)

**Comment by PavelBal** [comment]
Yes

**Comment by rwmcintosh** [comment]
Does it make sense to hide Value Origin for all PV and IC views including Expression Profile?

**Comment by PavelBal** [comment]
informationinformatoin.
