### ISSUE TITLE
Simulation out of synch - show differences

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1083]
When a simulation is out of synch, the differences cannot be shown atm. Is this planned to be implemented?

**Comment by PavelBal** [comment]
Ah this is new.

**Comment by msevestre** [comment]
![1000027879](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/7c47f197-f709-421d-94d0-a9b7d84e8fcf)
Lol

**Comment by PavelBal** [comment]
Didn't use the latest nightly ;)

**Comment by PavelBal** [comment]
Well actually, when changing a parameter in a simulation, the simulation is marked as "out of synch" but there is not way to see what is different.
