### ISSUE TITLE
Error when modifying a table formula with x argument

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1085]
When trying to change path to table object or to a-argument of a table formula with x argument, an error is thrown:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/5b92cf77-040e-4cf6-882f-3ce14824a98c)

Application:
MoBi® 12.0.45

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Presenter.EditTableFormulaWithXArgumentFormulaPresenter.selectFormulaUsablePath(Func`2 predicate, String caption)
   at MoBi.Presentation.Presenter.EditTableFormulaWithXArgumentFormulaPresenter.SetXArgumentFormulaPath()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

Already in v11.

**Comment by rwmcintosh** [comment]
Should this automatically expand the tree when I use the spatial structure to edit the formula? See below; the tree is totally collapsed.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/b3328596-e735-4d34-989e-cd60d355e2af)

**Comment by PavelBal** [comment]
Yes I think this is a good idea to expand to the location of the parameter! Is this dialogue specific for the table formula, or can it be generalized?

**Comment by rwmcintosh** [comment]
It seems the reference dialog is generalized to different parameters, but different for the parent container (Reaction, Molecule, or other).

The reason I asked that is that there's a need to resolve the parent container to select the correct reference dialog. However, in the context of the formula cache, the parent is not known.

**Comment by rwmcintosh** [comment]
The same issue was in v11.2 from my testing.

**Comment by rwmcintosh** [comment]
This is related. When editing the formula in a parameter context (not from the formula cache) and you select a local reference point
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/ba4cb907-a1f6-48f2-8785-92a7f7734180)

The dialog does not work. This node should be expandable.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/77dbd6b0-e539-43ea-89ce-458e2fa4acf3)

As it was in V11
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/f44878ce-72f5-4de2-b8fd-491acaa175a9)
