### ISSUE TITLE
SynchronizeParameterValueCommand does not undo the changes

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1090]
I thought this command would work differently. When reverted, it does not undo its updates unless it is run after a change in the quantity it's based on.

**Comment by rwmcintosh** [comment]
Also, it's not enough to just revert the changes that were made, you have to restore the ```OriginalQuantityValues``` to the simulation

**Comment by msevestre** [comment]
Why should this is be undoable?
I would mark it as irreversible and be done with it
