### ISSUE TITLE
Issue with Distributed Parameters in Individual BB

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#1091]
Right now, the concept has a serious flow (I think)
Consider the Kidney parameter, volume

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/5251b103-8ded-4eff-a31d-a34d377a107c)

It's a distributed parameter, you can't see the value. Instead, there are TWO other parameters that are somewhat irrelevant for the standard user

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/071daebc-c395-49ff-8d9e-f44b840df842)

How should we change the display?

@Yuri05 @rwmcintosh @PavelBal @stephanschaller @georgeDaskalakis

**Comment by PavelBal** [comment]
Yes this is definitely not the view I would expect. I propose the following:

For distributed parameters, the entry in `Formula` column is `Dstributed...` or something like this, making it clear that the user can click on this entry. Upon clicking, a floating pop-up appears (no idea how they are called, like this: 
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/1b09c8a3-6686-4211-9619-a8d436ae7d47)
),

where the user can edit the distributed parameter like this:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/4e2c542b-47de-44d5-872d-305f0cb75847)


The user can still override the value by entering something into `Value`. He can also *reset* the value back to using formula.
