### ISSUE TITLE
Error pops up when deleting molecule in reaction building block

### ISSUE THREAD

**Issue by MarKrauss** [Open-Systems-Pharmacology/MoBi#110]
[ErrorMoBi_7_1_66.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1071157/ErrorMoBi_7_1_66.zip)
Reproduce: 
Create Reaction and molecule in reaction building block
mark molecule, right click and select "delete"
Error pops up
Afterwards molecule is deleted and it seems that error has now effect?
![errormobi_7_1_66](https://user-images.githubusercontent.com/25460451/27074531-ade82b1a-5027-11e7-8441-bdecc24dd036.PNG)

**Comment by MarKrauss** [comment]
Project example
[ErrorMoBi_7_1_66.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1071160/ErrorMoBi_7_1_66.zip)

**Comment by msevestre** [comment]
can reproduce
