### ISSUE TITLE
It is possible to add >1 expression profiles for the same enzyme/transporter

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1102]
E.g. here I added 2 expr. profiles for the enzyme E1:
<img width="500" src="https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/d9ae49ca-998b-405a-8dde-fe34e2462149">

Which one is used in the simulation is unclear (probably the last one). It does not make sense for me to allow >1 expression profiles for the same enzyme/transporter.

**Comment by PavelBal** [comment]
Not any more.
