### ISSUE TITLE
Favorites are not automatically specified for parameter identification

### ISSUE THREAD

**Issue by MarKrauss** [Open-Systems-Pharmacology/MoBi#111]
When starting a parameter identification by right click on simulation, parameters defined as favorites were automatically specified as parameters to identify. That does not work in the Version 7.1, Build 66

**Comment by PavelBal** [comment]
It does, but not always. No idea what the logic behind it is, but is also happened in 7.0.

**Comment by msevestre** [comment]
@MarKrauss Would you please attach a project then so that we can reproduce the use cases where it does not work.

**Comment by MarKrauss** [comment]
The bug appears after updating a simulation in Mobi, for example after changing the km value in the building block reaction and then update. Before updating defined favorites are specified (Parameter Identification 1 in example project), afterwards not (Parameter Identification 2
[Desktop.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1074875/Desktop.zip)
 in example project),

**Comment by msevestre** [comment]
I can reproduce the issue.
