### ISSUE TITLE
Simulation sync status after project conversion

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1110]
When I open a project from the test data in MoBi new modules are created and building blocks are grouped.

In the simple case where you have a single simulation, and just enough building blocks for one module, only one module is created and it's linked to the only simulation. 

The sync status (red/green) cannot be reliably established though. MoBi can tell the version of the building blocks, and therefore MoBi checks if those match. However, MoBi keeps track of simulation changes using local change tracking objects, and during a project conversion, there is never any present.

The sync status therefore, is unreliable after a v11 project is updated.

**Comment by rwmcintosh** [comment]
In this project, all simulations use the singular module. They all track green because the building block versions all match.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/b60c7ca1-af19-42cc-9b0e-fc44e336668f)

I'm wondering if we should just create a single module for each simulation, add it to the project.

**Comment by rwmcintosh** [comment]
Or maybe we can just version mismatch the building blocks on purpose. We don't have "update" when a building block version is different; users must reconfigure the simulation to match everything up again.

**Comment by rwmcintosh** [comment]
@PavelBal @Yuri05 @georgeDaskalakis 

After a discussion with @msevestre it seems this might be more difficult than I first thought.

There is no easy 1-1 relationship between changed simulation quantities and building block parameters.

If you have simulation changes at the time of upgrade to V12 and we do nothing about this, then you will **not** lose the simulation changes of course, but you would lose the ability to commit those changes to the project building blocks. Changes you make in V12 can still be committed to existing or new PV building blocks as usual. I don't know how we would handle the checkmark in this scenario.

If we want to implement this 100% correctly, we might have to re-create the simulation from the project building blocks, compare new and existing simulations, and then create the required change tracking objects from the comparison.

That would take some time, and we would only want to take such a step at the user's instigation. The most obvious time is during project conversion, but there's no reason that we couldn't make this feature available any time after as well.

**Comment by rwmcintosh** [comment]
Yeah, this is still an issue. If I change `Age` for example in a simulation then in V11.3 the change should be committed back to a parameter values building block.

In Version 12, there's no record that the change in simulation exists and the simulation status is still green

I search the simulation structure for parameters that are not their default values, indicating they were manually overridden and then make those work.

For example looking for all the resettable parameters

![Image](https://github.com/user-attachments/assets/7f0e1b7a-f6d8-46e3-83fb-04470619e8ec)

I think that might be enough.

**Comment by rwmcintosh** [comment]
That has the drawback that parameters that are `fixed` in the building block also have their changes tracked as if the value was `fixed` in the simulation.

**Comment by rwmcintosh** [comment]
Maybe we should rescue the `BuildingBlockInfo` from the V11 project, deserialize them and then calculate what we need for V12.

**Comment by PavelBal** [comment]
I think this is good.
