### ISSUE TITLE
Observers container criteria: "Match all tag"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1117]
Currently there is no way to define an observer that is present everywhere where the molecule is. "Match all tag" is missing.

**Comment by Yuri05** [comment]
Seems it's already implemented
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/598a9317-8fa3-4559-b42d-ad534c4bd496) ![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/8a043d33-bba2-49b6-92d5-157968bb4499)

**Comment by PavelBal** [comment]
Oh, but only for "Molecule Observer" and not "Container Observer".

**Comment by Yuri05** [comment]
Why not defining it as a molecule observer? 
"observer that is present everywhere where the molecule is" sounds for me more like a molecule observer and not a container observer.

**Comment by Yuri05** [comment]
> Btw, why do _container_ observer always require a _molecule_? Why can't I create a container observer that does something for a container, maybe not necessarily for a molecule?

good question... and I don't have an answer.

**Comment by PavelBal** [comment]
Then... https://github.com/Open-Systems-Pharmacology/MoBi/issues/1119 ;)

**Comment by Yuri05** [comment]
> Then... #1119 ;)

with this, I assume we can close the issue. please reopen if not
