### ISSUE TITLE
It is possible to have two simulations with the same name

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1125]
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/44990944-fa37-4b37-bcbf-989c89a7d0f6)

I first created a simulation with the name, then imported one from PKML that had the same name.

**Comment by Yuri05** [comment]
In the screenshot one sim is `10 mg/kg` and another is `10 mg_kg` ?

**Comment by PavelBal** [comment]
Of course.... Yepp my bad, sorry (facepalm)
