### ISSUE TITLE
Simulation settings should operate independently from the project

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1132]
Need to be able to 

- [x] add output intervals in a simulation when there are none defined (you can remove all intervals in R, but not in MoBi)
- [x] Do not replace them when configuring a simulation from context menu

**Comment by rwmcintosh** [comment]
Do we still need to do this if we have a button to add?

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/1853624d-dc40-464a-8ce9-9b45250df9b0)

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/657fb7b7-e321-4990-8f7c-bbc465f28cdf)

**Comment by msevestre** [comment]
nope remove
