### ISSUE TITLE
Import and rename container into spatial structure with neighborhood

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1139]
Renaming should include confirmation of renaming the neighborhoods

**Comment by msevestre** [comment]
I don't get this one. Renaming what?

**Comment by rwmcintosh** [comment]
When we rename a container already in the structure, we get this preview dialog for related rename actions.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/df53b899-e72f-468d-94b0-23bb4b2e02fd)

Should we implement something similar, but with a single checkbox to do all or not of the renaming? Not the individual checkboxes for each one separately.

Or is the preview not valuable, in which case, we can just ask the user to confirm renaming neighborhoods and neighbor paths if there are any (without preview).

**Comment by rwmcintosh** [comment]
We go with no confirmation and proceed with modifying the neighborhoods to match the container renaming
