### ISSUE TITLE
Expression profile 'Add' button should be disabled when there's no expressions that could be selected

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1142]
There is an exception thrown ATM

**Comment by rwmcintosh** [comment]
This is during simulation creation BTW.

I know we saw it together last week, but the button here is disabled.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/f1427c40-9b9f-4b66-8700-651c05bf727c)

**Comment by msevestre** [comment]
It was fast click... probably triggered before view was updated

**Comment by rwmcintosh** [comment]
You mean, like you have one expression on the left, then double-click the add button?

**Comment by rwmcintosh** [comment]
Cannot reproduce
