### ISSUE TITLE
Add output selections to project simulation settings editor

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1163]
ATM, you can't add output selections to the project's default simulation settings. Create a way to add them by path.

Users can manually edit paths, or browse from paths present in the project simulations already.

**Comment by rwmcintosh** [comment]
I wonder if I could get some opinions on the approach I took before I submit? 

I re-used the same selection modal view as you get when you select outputs for a single simulation, but this one can have outputs from multiple simulations.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/20a2327e-7921-4736-ab39-c9178399f5b0)

You trigger that using the 'Edit' button on the main view. You can also remove directly from the main view using the 'x' buttons for each row in the grid.

The other option that occurs to me after implementing this: you could use the two-grid selection view directly without a modal selection. But, I'm not sure it would be as clear when you are just viewing.

@PavelBal @msevestre @Yuri05

**Comment by PavelBal** [comment]
Can we have an option to manually type in the path? I guess in this case, the "QuantityType" cannot be directly guessed, but I do not think this as a useful information, at all.

**Comment by rwmcintosh** [comment]
I can change the editor behind to look more like the start values editor with separate path columns.

**Comment by rwmcintosh** [comment]
But then, let's keep this modal like it is for adding from existing simulations

**Comment by PavelBal** [comment]
> I can change the editor behind to look more like the start values editor with separate path columns.
I think the whole path would be more convenient (without separation in path parts).

**Comment by rwmcintosh** [comment]
ok, here's an additional suggestion though in favor of using path parts.

We have this paradigm already in similar editors

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/1c3937ea-2dce-4729-8a62-9fc446270e9f)

Where you get a combobox with all the existing options for that path element. You can also type over with whatever value you want in there.

If we had that, do you think you'd need the modal selection presenter? Maybe just an add button that adds a blank one and you pick each path element?

**Comment by msevestre** [comment]
I think creating a path BY hand is probably not something that will be done often
So I agree with @PavelBal that using whole path as a string is more convenient

Ideally there is a way to copy a PATH From a entity in a simulation and paste it there if we want

Why do we need the QuantityType stuff? can this be hidden?

**Comment by Yuri05** [comment]
> Why do we need the QuantityType stuff? can this be hidden?

I use quantity type quite often for filtering, so I would vote against hiding it

**Comment by msevestre** [comment]
I mean in the PATH EDITOR
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/487c5c95-f995-46e1-a7f8-f058278b9aa7)

**Comment by Yuri05** [comment]
> I mean in the PATH EDITOR ![image](https://private-user-images.githubusercontent.com/1041237/289920503-487c5c95-f995-46e1-a7f8-f058278b9aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTY0OTgsIm5iZiI6MTcwMjM5NjE5OCwicGF0aCI6Ii8xMDQxMjM3LzI4OTkyMDUwMy00ODdjNWM5NS1mOTk1LTQ2ZTEtYTdmOC1mMDU4Mjc4YjlhYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTU0OTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdjY2MyNzJjNGYyYzIyMGI1ZWY5NzA3MDdhNGUyOGE1ZDZjZDQ0YTE4NzY2MTMzNGM3Mjg4MjFiZWIyMTRhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VKut2VLG5bHr2tqvavUA3lDDHqj2ecBexeAlyCqqZs4)

mmm, then no opinion on that. I can live with both :)

**Comment by rwmcintosh** [comment]
Yeah, I'm sure it will be easy to hide that.

Do we want this modal selection option at all? Or do we make this really basic and just use an add button and put a blank entry that the user can edit?

**Comment by msevestre** [comment]
I think add with empty is enough and selecting an entity from the tree from which the path would be taken from. (like what we have in many other places when we select an entity to build a path) would make more sense to me than a modal edit

**Comment by msevestre** [comment]
although I am not sure what you mean with a modal edit to be honest :)

**Comment by rwmcintosh** [comment]
This one. Same as used for configuring simulations.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/4ebb5319-e697-47c5-91ab-a9d55cb88063)

**Comment by msevestre** [comment]
I would nto use this eto CREATE entries. here they are already propoluated so it's easy to use. But creating like this would be very cumbersome

**Comment by rwmcintosh** [comment]
This is the planned UI for this feature now.

Edit shows 3 buttons per row:
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/89bb1212-1493-4060-b535-2a27c6a293a7)

I think it would be handy to get the editor to come up when using the add button rather than adding a blank and make the user click the ellipsis to edit.

On either case of add or edit, you get this kind of dialog that allows you to cruise through all the simulations to find the path. This one is just one that I found for spatial structure, but you get the idea.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/83512bdf-91ff-4d4f-9d8c-8a37b2ac2121)
