### ISSUE TITLE
Errors when a molecule references molweight of another molecule

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1167]
[C1C2_MW.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/12936537/C1C2_MW.zip) In the project attached, there are 2 molecules: C1 and C2. 
`C1.MolecularWeight` is defined as a function of `C2.MolecularWeight`:
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/7597b029-6624-4227-b9ee-30b83891eaf2)

Now if I try to run the simulation S1 with those 2 molecules, where C1 is selected for plotting, the error below comes.
The error comes at the end of the simulation run and before the results are plotted.
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/ace65d36-81b7-4c3c-9c74-a37cc3ff9e62)

Followup error: trying to run the simulation again produces the error below.

```
Application:
MoBi® 11.2.138

An item with the key '55a90fc8-ae12-49a4-87ee-99506b5cde1b' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at MoBi.Presentation.Tasks.SimulationRunner.copyResultsToSimulation(SimulationRunResults results, IMoBiSimulation simulation)
   at MoBi.Presentation.Tasks.SimulationRunner.startSimulationRun(IMoBiSimulation simulation)
   at MoBi.Presentation.Tasks.SimulationRunner.RunSimulation(IMoBiSimulation simulation, Boolean defineSettings)
   at MoBi.Presentation.UICommand.RunActiveSimulationCommandBase.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
@christoph27 FYI Your problem, reproduced with dummy compounds

**Comment by Yuri05** [comment]
> oh my gosh. Why would we want to do anything like this

ask @Christoph27 😉 

> I think relative path would work? But absolute path are not replaced in molecules so this can't work. (something like ..|..|C2|MW?)

But there is nothing to replace here. There are no keywords in the path.

**Comment by Yuri05** [comment]
In fact the path is properly interpreted: in the simulation, I can see the value of C1.MW
But when transferring the results back something goes wrong.
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/10ded4b7-3161-4cbd-9bdc-c82f741278ff)

**Comment by Christoph27** [comment]
Why do I want it: I have an administration of two related compounds (MW is related) and I want to study the class of compounds so that I want to vary the MW (and not just set two fixed values). 
I have tried the possible workaround mentioned in #196 of having both molecular weights defined in the spatial structure and referring in the molecules to these parameters. This does not work either (see attached file C1C2_MW_eqSpStr_both.mbp3).

[C1C2_MW_eqSpStr_both.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/12998836/C1C2_MW_eqSpStr_both.zip)

**Comment by msevestre** [comment]
the reason is this code
```
      private MoleculeBuilder getMoleculeFor(IMoBiSimulation simulation, DataColumn dataColumn)
      {
         var moleculeName = _keyPathMapper.MoleculeNameFrom(dataColumn);
         if (string.IsNullOrEmpty(moleculeName))
            return null;

         return simulation.Configuration.All<MoleculeBuildingBlock>().Select(x => x[moleculeName]).FirstOrDefault(x => x != null);
      }

```

trying to retrieve the MW value for the molecule from the BUILDING BLOCK AND NOT THE Simulation itself. It's absolutely ridiculous
