### ISSUE TITLE
Errors when a molecule references molweight of another molecule (part 2)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1168]
[C1C2_MW2.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/12936623/C1C2_MW2.zip)
Same situation as in #1167, but now `C2.MolecularWeight` is defined as a function of `C1.MolecularWeight`
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/815df556-2ca7-426a-ab1c-e9b23e15d995)

Here I even cannot create a simulation: the error message below comes

```
MoBi®

Unable to resolve path 'S1|Neighborhoods|Lumen_duo_Duodenum_cell|C2|Sum of passive process rates' for entity 'Oral mass absorbed segment' with path 'S1|Organism|Lumen|Duodenum|C2|Oral mass absorbed segment'

```

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/ef9a26a5-f742-460b-9a92-9e998911c3ba)

**Comment by msevestre** [comment]
Here this is something else

**Comment by msevestre** [comment]
so weird that there is a different error however. why would the order of molecule matter?

**Comment by msevestre** [comment]
The path does not make sense at all
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/73852a95-3612-4ded-a4a1-14a9ee16dbd9)

**Comment by msevestre** [comment]
For some reason, "sum of passive process rate" is not available for C2

**Comment by msevestre** [comment]
this comes from

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/a90b51d3-26ad-4f8f-8d34-0551fadaa752)

**Comment by msevestre** [comment]
so it's becaused `"Drug absorption rate (lumen to mucosa)"` returns NaN for C2 and 0 for C1... digging

**Comment by msevestre** [comment]
`Specific intestinal permeability (transcellular)` is return NaN for C2

**Comment by msevestre** [comment]
MW Eff is negative in this case !

**Comment by msevestre** [comment]
WTF
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/5c8a8676-c817-441e-9d97-3584b7e009bd)

**Comment by msevestre** [comment]
2 hours of my time that I will never recover

**Comment by Yuri05** [comment]
lol. shitty example indeed :)
