### ISSUE TITLE
Add Expression Profile Button Not Implemented

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1185]
Add Expression button not implemented.
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/d2fb99f2-f547-4554-899b-b5700e697a86)

```
Application:
MoBi® 12.0.0

Action is not implemented yet

Stack trace:

at OSPSuite.Presentation.MenuAndBars.NotImplementedCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

It has 3 sub-buttons that are implemented, but what do you do for the top level button

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/a3b61caf-45f6-4e9b-a72e-b627cb1c51d2)

**Comment by rwmcintosh** [comment]
CreateSubMenu?

**Comment by msevestre** [comment]
What the heck? A top menu should not have an action. Does not make sense

**Comment by msevestre** [comment]
so somehow the buttons are added but not in the right place...I am very puzzled
