### ISSUE TITLE
Refresh/commit simulation settings from project defaults

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1206]

**Comment by rwmcintosh** [comment]
The simulation settings are not a real building block now, they are stored as project level defaults that are applied when the simulation is created.

Users can change the simulation settings, but when they do, there is no way to revert to the project defaults as there was when the simulation settings were a building block.

So, that ability should be recovered, to restore or refresh simulation settings from project defaults, but also to commit simulation settings to the project defaults as well. That way, settings from one simulation could easily be used in other simulations by committing to the project default, then refreshing other simulations.

**Comment by PavelBal** [comment]
@rwmcintosh I could not find how this is implemented, re-opening. If its already there, please show me.

**Comment by PavelBal** [comment]
OK found it... but let's discuss.
