### ISSUE TITLE
Simulation should be able to share name with event

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1207]
Not allowed now because name is already in use

**Comment by rwmcintosh** [comment]
1. Start with a simulation and module with the same name
2. delete the simulation
3. recreate the simulation and try to use the same name

**Comment by rwmcintosh** [comment]
@PavelBal you might have to help me reproduce. I can't make it happen.

**Comment by rwmcintosh** [comment]
Turns out this instance was not due to module name, but an event with the same name

**Comment by rwmcintosh** [comment]
We don't allow simulation to share names with any of:

- Molecule
- Spatial Structure
- Event
- Reaction

Do we really need this protection for those builders?

**Comment by Yuri05** [comment]
I think there were some path resolution issues in the past if a simulation had the same name.
No idea if it's still the case. We can remove the restriction and see what happens :)

**Comment by Yuri05** [comment]
just tried it in MoBi: if you rename a reaction and give it the name of a simulation which uses this reaction and then try to update the simulation: crash, because reaction parameters path cannot be resolved

**Comment by Yuri05** [comment]
so let's DON'T remove the restriction

**Comment by Yuri05** [comment]
I assume that problematic are all use cases where simulation is named as one of its top-level containers:
* `Events`
* `Neighborhoods`
* Name of the top container in the spatial structure (usually "`Organism`")
* Molecule name
* Reaction name
* ...

**Comment by rwmcintosh** [comment]
Ok, so we can just close this with no-fix? Or leave Molecule names and reaction names as restrictions?

**Comment by PavelBal** [comment]
Some simulations might have the administration named after simulation name. As we now moved the applications from the "Applications" node one level up, they become a top level container and simulation with the same name cannot be created.

**Comment by rwmcintosh** [comment]
I think only some of the scenarios that Juri listed are problematic. Not all.

**Comment by Yuri05** [comment]
> Some simulations might have the administration named after simulation name. As we now moved the applications from the "Applications" node one level up, they become a top level container and simulation with the same name cannot be created.

Applications are placed now under **Events**, right? So having "Application name = Simulation name" should be uncritical

**Comment by msevestre** [comment]
I agree. What triggered this bug is the one that is for sure NOT required lol. I would remove the check for event names
