### ISSUE TITLE
"Faction unbound" not found when combinding two modules

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1208]
[AddingTumor_FU_notFound.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/13366112/AddingTumor_FU_notFound.zip)

**Comment by msevestre** [comment]
All right. So this is an interesting one
We are combining two spatial strucutres, both with a `MoleculeProperties` container

First one has

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/1a283a01-3e6c-46f2-bf47-00026a53c82e)

Second one has 

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/1d0339a7-d409-41b3-8c33-37ec240c5b40)


so the parameters from the first spatial structure are remove to use that from the second one (which has none)

I am not sure how to deal with this,

**Comment by msevestre** [comment]
Two ways of dealing with this

1. Allow to delete MoleculeProperties container 
This would work (deleting in the Tumor module) but this is not very intuitive

2. Merge MoleculeProperties container
This would in this case NOT replace but simply do nothing. I feel this is the best way BUT there is no way to delete then parameters from a molecule properties whne merging. Not sure if this is a problem

Thought ? @PavelBal @Yuri05

**Comment by Yuri05** [comment]
Agree that merging is better.

> 2\. no way to delete then parameters from a molecule properties whne merging. Not sure if this is a problem

I think it's not a big problem; after V12 is released we can think again about implementing "Deletion lists" which would allow deleting any entities by path.

**Comment by PavelBal** [comment]
3. Do NOT create `MoleculeProperties` by default in an empty module?

It is a similar problem we had at the very beginning, where each module hat `Organism` container by default.

**Comment by msevestre** [comment]
This also a consideration which would solve this problem and wouldn’t add a different logic for merging containers 
We would have to add capabilities to add a mowlcule properties container in a spatial structure eventually which we so not have 
No way to add however a new parameter for every molecule from a merged module. Feels like a limitation to me

**Comment by PavelBal** [comment]
> No way to add however a new parameter for every molecule from a merged module.

Hmm this is an interesting feature I did not think about... well, then  we need merging, but this would mean additional effort.

**Comment by msevestre** [comment]
Additional effort? Well it's implemented lol :) I have a PR ready

**Comment by msevestre** [comment]
But we could also REMOVE the MoleculeProperties by default in a spatial structure. Feels like an OK behavior to me to add on top of this instead of having empty containers all the time

@Yuri05 Thoughts?
