### ISSUE TITLE
For selecting neighbors and containers add the level of node for the building block

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1221]
This tree below is missing a level for modules

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/a76d599c-e32f-4307-a422-6051b8234880)

The naming would also change because the module name does not need to be added to differentiate between two top containers with the same name.

**Comment by rwmcintosh** [comment]
@PavelBal @msevestre @Yuri05 
Just to be sure before going to PR

I added the module node level here, but did not add a node for the SpatialStructure itself. In all cases, there is a single spatial structure for a module. Modules without a spatial structure are ignored in this view.

So what you're seeing is the module, and the top containers from the single spatial structure. Is it more clear?

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/7ba82d94-4f4a-4192-9011-292ea27a4478)

**Comment by PavelBal** [comment]
Yepp, looks good.

**Comment by msevestre** [comment]
Although in the example, one was a PKSim Module and the icon should be different . Not sure if this is a different project
