### ISSUE TITLE
Export of an organ to PKML - combine "Save to pkml" and "Save to pkml with individual"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1238]
I think we should have only one menu entry "Save to pkml", and in the next step the user decides whether to export with individual or not.

**Comment by rwmcintosh** [comment]
@PavelBal This is a duplicate of #1145 ?

**Comment by rwmcintosh** [comment]
At least, since we already implemented the Individuals. It's probably more accurate to close #1145 and leave this one open since we are starting with already working container and individual export.

**Comment by PavelBal** [comment]
> This is a duplicate of https://github.com/Open-Systems-Pharmacology/MoBi/issues/1145 ?

Almost, #1145 now combines a set of issues, I think.. This issue here does not mention expression profiles.

**Comment by rwmcintosh** [comment]
Yes, but the only portion remaining from that original set of issues is this one. I can probably close one or the other.

**Comment by rwmcintosh** [comment]
This has been done already.
