### ISSUE TITLE
Fialed to run a intranasl administration in MoBi

### ISSUE THREAD

**Issue by MLJiaFei** [Open-Systems-Pharmacology/MoBi#1249]
Hello,
I created an IN administration model according to a discussion in OSP before.
[https://github.com/Open-Systems-Pharmacology/MoBi/issues/246]

Steps are as follow:
1. increasing nasal depot in human standard spatial structure, and connecting it with VenousBlood Plasma.
2. increasing first order nasal absorption in stander passive transports.
3. modifying path and molecule in IV Bolus application.

However, I fialed to create simution because of an error in the figure.
![error](https://github.com/Open-Systems-Pharmacology/docs/assets/156216953/756fab27-b13a-414a-8f16-90573b1bae05)
[mouyao-Mobi -111.zip](https://github.com/Open-Systems-Pharmacology/docs/files/13905508/mouyao-Mobi.-111.zip)

Thanks for your help.

**Comment by Yuri05** [comment]
Please read the documentation on Events: https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#events-and-applications 
The OSP forum can be found [here](https://github.com/Open-Systems-Pharmacology/Forum/discussions)

**Comment by MLJiaFei** [comment]
> Please read the documentation on Events: https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#events-and-applications The OSP forum can be found [here](https://github.com/Open-Systems-Pharmacology/Forum/discussions)

Thanks. Solved.
