### ISSUE TITLE
V12: cannot select entity to change in event assignments

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1251]
The selection window is empty
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/f09995a2-63d3-450f-9845-ff487b61de57)

**Comment by rwmcintosh** [comment]
I just tried it and I get the selection view. This issue was created some time ago, it could have been fixed in the meantime somehow...

Can you check it again @Yuri05?

**Comment by msevestre** [comment]
this is the issue i reported last time to you @rwmcintosh and i fixed it already as part of the event assignment fix
