### ISSUE TITLE
Icons for neighborhoods

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1255]
Ritght now, the "OSP" icon is used for neighbors in the Neighborhoods view of a spatial structure:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/a5ca7ff8-15a8-4a5f-af0b-7375474ed429)

Proposals are:

> For the neighbors we could use the icons which correspond to the last path entry. E.g. in the above screenshot both neighbors would become the icon of "Blood cells"

> However for the neighbors icon, I am not sure about the proposal. SOmetimes, the target won't exist. What should be the icon then?

> If the container is present in the current module, then use it's icon, otherwise something like an "?" ?

Original discussion: https://github.com/Open-Systems-Pharmacology/MoBi/issues/927

**Comment by Yuri05** [comment]
included in #1888
