### ISSUE TITLE
Changing output selection adds a red icon to the simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1260]
1. Create a simultion - it's "green"
2. Click "Defined Settings and Run" and select anything. After running, the simulation is "red".

As output selection is not part of any BB any more, changing the outputs should not make simulation "invalid".

**Comment by rwmcintosh** [comment]
We should remove red/green from this icon all together I suppose

**Comment by rwmcintosh** [comment]
> We should remove red/green from this icon all together I suppose

My mistake, the report is that the simulation icon turns red, but it should remain green. The simulation settings already does not have this indicator within the simulation tree.
