### ISSUE TITLE
Code coverage does not work anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1266]
same as https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2866

**Comment by Yuri05** [comment]
nope, not solved: same error
https://ci.appveyor.com/project/open-systems-pharmacology-ci/mobi-l8pb8

**Comment by rwmcintosh** [comment]
I believe this is fixed now from the AppVeyor side

https://help.appveyor.com/discussions/questions/65061-nunit3-console-runner-has-changed
