### ISSUE TITLE
When importing containers with additional parameter values, allow user to select target for parameter values

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1269]
You should be able to either select an existing building block, or create a new building block in the module.

Watch out for the container being renamed during import.

Follow up to #1145

**Comment by rwmcintosh** [comment]
@PavelBal  Should the new parameter values only add, or also update existing ones if present?

**Comment by PavelBal** [comment]
Also update.

If possible, show a list of values that will be updated (maybe even with checkboxes so the user can select, which ones to update?)
