### ISSUE TITLE
"References to add" tree view should show parameters from all modules

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1277]
Right now, the "References to add" tree view that is shown when e.g. creating a parameter with a value given by an equation only lists the containers and parameters that are present in the same module.

Example: I have a project with two modules with one spatial structures each: 
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/3bf4b5f4-63a1-4881-9f65-8d97afcaf66f)

The "Two-container module" has two containers in the spatial structure - "Container A" and "Container B". The "Second module" has one container "Container A" with a parameter "ParamB".

When defining a formula for a parameter in "Two-container module|Container B", only containers and parameters from the same module are shown:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/45cf7f08-e6b9-4f2b-b5a4-7772608a82d3)

Instead, an additional hierarchy level of modules should be added, so parameters from other modules are also listed.

**Comment by PavelBal** [comment]
Ah-ah and it always has "Organism" as the top container, even if it is not.

**Comment by benjaperez1983** [comment]
@PavelBal  agreed that this ticket is already solved.
