### ISSUE TITLE
Neighborhoods are not imported for compartments

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1285]
When saving an organ to pkml and loading it in a new module, the neighborhoods within the organ and between the organ and the rest of the body (blood organs) are imported. E.g., exporting "Bone" and importing it in a new module:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/8cac30c3-21aa-4cd1-8bb4-8f3d4cbe888c)

The behavior is **as expected**.

However, if I export "Bone|Intracelluar" only and load it in a new module, no neighborhoods are created:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/a0ad9f0c-30d8-44ae-9bca-6d6c43223c8f)

I expect the neighborhood `Bone_int_Bone_cell` being loaded as well.

**Comment by rwmcintosh** [comment]
Tough to spot this one, somehow the parent path stuff is interpreted incorrectly. Strings match, when you look in the debugger you see the same string, but underneath ```Organism|Bone``` is not treated as a separate element.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/873b73ed-d7d6-49be-a47a-755ebb91c3e1)

**Comment by rwmcintosh** [comment]
the mismatch was actually during import rather than export
