### ISSUE TITLE
Cannot change value of a distributed parameter

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1291]
1. Exported an organ (Muscle) to pkml with an individual selected
2. Loaded in a new module
3. Parameter "Volume" is stored in the PV BB as distributed parameter
4. Cannot change its value

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/5e3ea030-edac-43c9-86f4-a78e5a71bebb)

Best solution would be if the parameters from the individual were created in the container upon export/loading (related to https://github.com/Open-Systems-Pharmacology/MoBi/issues/1290).

So after export, PV BB only contains expression values.

**Comment by PavelBal** [comment]
Even if I set a formula for this parameter, its distributed value is retained -> this is definitely a bug:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/4d094384-c8f2-4d40-ad48-ea45ab310ee0)

Proposal: for distributed parameters, "Formula" entry is set to "Distributed". Setting its value to "Not Available" makes the parameter constant and the user can change the value. Again, this should only be relevant for the "Individuals"-BB. For organs, when loading, such parameters should become part of the spatial structure.

**Comment by rwmcintosh** [comment]
Changing the value makes it non-distributed.

What should happen with the sub-parameters?

**Comment by rwmcintosh** [comment]
Plan for now is to make the drop-down read-only so no one can edit this as a distributed parameter. I would like to allow user to show the distribution with the arrow, but if they click in the editor, then this gets overwritten with a constant formula parameter.

**Comment by PavelBal** [comment]
Yeah I think this is okay. Changing of distribution will be not directly possible, but we can address it later if we have a use case.
