### ISSUE TITLE
Parameter values for distributed parameters from PV BB are not applied.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1293]
Trying to work around this https://github.com/Open-Systems-Pharmacology/MoBi/issues/1290

I have created the missing parameters in the SS BB with default values 0. When created the simulation, the values are still 0, not those defined in the PV BB.

Okay this only applies to distributed params?

**Comment by Yuri05** [comment]
@pavel probably fixed, please check

**Comment by PavelBal** [comment]
I think it is fixed.
