### ISSUE TITLE
"Simulation settings" should be stored separately from "Output selections"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1295]
Setting simulation settings from a simulation to project defaults should only update the output intervals and solver settings, but not output selections.

**Comment by rwmcintosh** [comment]
We should be able to just separate these actions in context menus right? They are stored in the same core object and are serialized together, but within the application, we could implement separate context menu actions.

What about when you load/save? Do we need separate buttons for settings/output selections respectively?

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/27fa4738-6a7b-4bc9-8796-6c9142a745ac)
