### ISSUE TITLE
Problem between two versions for a mobi file

### ISSUE THREAD

**Issue by chiarazuni** [Open-Systems-Pharmacology/MoBi#1305]
Hello,

I created a mobi file on version 11.0 in my computer that works perfectly.
I would like to open it on a virtual machine with version 11.1 but the files doesn't open properly and I can't access to building blocks or simulations.
Would you have the solution for that please ?
I should be able to open the file with a more recent version.
Thank you for your help.
Sincerely

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/129844980/f4e46070-ac86-445b-b919-45b8330d4a44)

**Comment by Yuri05** [comment]
check here: https://github.com/Open-Systems-Pharmacology/Forum/discussions/1330
