### ISSUE TITLE
Automatically create a building block "IC" when creating a new Molecules BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1307]
If a module has neither a molecules nor a IC BB, creating a new Molecules BB should also create a new Initial Conditions. This is what users would do in 98% of cases.

If the module already contains an IC BB, do not create one.

**Comment by rwmcintosh** [comment]
using the created dialog, auto-check the IC option when an IC does not yet exist in the module
