### ISSUE TITLE
"Refresh from source" for IC BB does not always refresh the formula cache view

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1308]
[Two-Compartment.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/14998333/Two-Compartment.zip)

In the attached project:

- Module "TowCompartmenalModel" has "Molecule B" which start amount was previously defined as "Container B|Volume". The IC BB of this module was extended and the formula has the path to the volume "Container B|Volume":

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/c6ffa4a9-ecc8-4efd-955b-033fe84a457b)

- The path of the alias has been changed to "Organism|Container B|Volume":

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/db3ac0d9-7ce3-48a4-b250-89536724d13d)

- Open IC BB in the module "TowCompartmenalModel"
- Select entries for "Molecule B" and click "Refresh selected from source"
- In the dialog, select the molecules from this module:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/c51d65c9-d4bb-4c53-af5d-e7e476b5d1fd)

- There are TWO formulas with the same name now:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/80aa906b-6453-44c4-a957-249f475abc7e)

Also this did not work first, it did not change the value at all, and I am not sure what exactly I did to finally manage to update. But the fact that there are two formulas with the same name is already wrong.

**Comment by PavelBal** [comment]
This obviously does not work properly... Let's try this out live tomorrow.

Notes for myself:

- Change start value of Molecule A in the module "CompA" to 15
- IC of Module A: select "Container A|Molecule A" and select "Refresh selected from source"
- Select this:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/90286550-2fae-4e88-8ca2-3713d1af3ec2)

Do we need to select the spatial structure at all? I don't think so, the start values are coming from the Molecules BB only (constant value or a formula)

- Click refresh -> nothing changes

**Comment by rwmcintosh** [comment]
We haven't been able to reproduce the 'refresh not working' part. Other issues mentioned have been fixed in related issues.
