### ISSUE TITLE
Show pk analysis and calcultated pk parameters in a simulation

### ISSUE THREAD

**Issue by chiarazuni** [Open-Systems-Pharmacology/MoBi#1309]
Hello,
I would like to see the calculated PK parameters of my simulation but impossible to display it in mobi.
In pk sim you just click on "Show PK analysis" to obtain calculated AUC cmax but that's not available in a mobi simulation.
Does someone know if that's available please ? 
Thanks.
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/129844980/978b5f49-7673-4cbf-ae63-d38525d76897)

**Comment by Yuri05** [comment]
At the moment not possible in MoBi (Feature request exists: https://github.com/Open-Systems-Pharmacology/MoBi/issues/824)
You could however send a simulation to PK-Sim and display most of the PK parameters there

**Comment by Yuri05** [comment]
Yo can save simulation as pkml in MoBi and import it in PK-Sim as an individual simulation as explained in the documentation: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/importing-exporting-project-data-models#importing-individual-and-population-simulation

**Comment by chiarazuni** [comment]
> You can save simulation as pkml in MoBi and import it in PK-Sim as an individual simulation as explained in the documentation: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/importing-exporting-project-data-models#importing-individual-and-population-simulation

Yes it worked perfectly. Thank you for your help.
