### ISSUE TITLE
Differences between exported and newly created model

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1311]
- Load PK-Sim project from snapshot (e.g. https://github.com/Open-Systems-Pharmacology/Midazolam-Model)
- Send a simulation to MoBi
- Create a new simulation "test"
- Compare the exported and the created simulations:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/270d562b-3214-40a3-a003-8a1ce677238f)

What are all those differences? Description, persistable, visbile...

**Comment by Yuri05** [comment]
`persistable` differences might be due to the default configuration in MoBi, telling which outputs should be kept after the calculation.
`Description`, `Visible` should be the same and I would consider it as a bug.

**Comment by PavelBal** [comment]
Well, it is okay that every output can be generated in Mobi, and also all the parameters/entities are visible. I just think this information is not important for the user and should be hidden.

**Comment by Yuri05** [comment]
This will be hidden if in the comparison options you restrict it to the "changes only relevant for the simulation results"
