### ISSUE TITLE
Saving containers from non-PK-Sim modules - does selecting an Individual and Expression profiles makes sense?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1317]
I don't think so. However, what would make sense is to save a subset of PV BB and IC BB with entries that contain the selected container as sub-path.

**Comment by Yuri05** [comment]
For me: it makes sense, especially if e.g. a former PK-Sim module was converted to a non-PK-Sim module later on in MoBi.

**Comment by PavelBal** [comment]
> especially if e.g. a former PK-Sim module was converted to a non-PK-Sim module later on in MoBi.

Conversion of a PK-Sim to an extension module should automatically include this step.

And if the extension module adds a new organ or whatever (it should not be a common practice to just duplicate the information from the PK-Sim module), then neither the individual nor the expression profiles contain any parameters relevant for this module.

**Comment by Yuri05** [comment]
> Conversion of a PK-Sim to an extension module should automatically include this step.

disagree. 
user might just make some small changes in a PK-Sim module (e.g. and additional parameter whatsoever) - in my opinion this should **not** include merging of individuals/expression profile into the module.
