### ISSUE TITLE
Formula duplicated when updating IC BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1323]
[Two-Compartment.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/15040608/Two-Compartment.zip)

- Open IC in module "TowCompartmenalModel". `Molecule B` is defined by a formula `StartAmount_MoleculeB`
- Open Molecules BB in the same module and change the formula of the start amount of molecule B:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/9a9d6d34-f1f8-4519-af02-eeb7d2e2d36b)

- In the IC BB, select the entries for Molecule B and select "Refresh selected from source" with the following settings:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/a59ea18f-6f7b-4265-89d5-4316a834a4e3)

- Re-open the IC BB (you have to reopen it, otherwise the new formula is not shown). In the "Formulas" tab, there is one more formula (the project has 3 when you open it):

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/bdc96882-2f90-4314-850b-fc16d2f3cd87)

**Comment by rwmcintosh** [comment]
Ok, this is because we are adding a new formula to the building block, but declining to remove the older one with the same name. We can't remove that one because there are other IC's that might be using it.

Is this a missing rename step? Perhaps automatically rename? `StartAmount_MoleculeB_1` etc?

**Comment by rwmcintosh** [comment]
If all instances of the formula will be refreshed with the new formula, then the original formula can be replaced, otherwise, rename and add the formula.
