### ISSUE TITLE
Include Molecule Parameters as Changed Entity in Event Building Block

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/MoBi#1325]
Is there any reason why parameters in the `Molecule` Building Block cannot be selected as changed entity in an `Event`?

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/26541603/f76af3f3-424b-461d-a121-0053b1689a8b)

This would allow a workaround for https://github.com/Open-Systems-Pharmacology/Forum/discussions/1752

**Comment by Yuri05** [comment]
At least the input field should be editable, so that the user can enter the full path by hand if the entity is not selectable via UI
(s. https://github.com/Open-Systems-Pharmacology/MoBi/issues/164)

**Comment by msevestre** [comment]
as discussed in issue #164, this is quite hard because a dimension is required. But I'll update the UI
