### ISSUE TITLE
Difference for the same parameter in container "molecule" or "reaction"

### ISSUE THREAD

**Issue by chiarazuni** [Open-Systems-Pharmacology/MoBi#1328]
Hi,

I am doing parameter identifications for a small molecule and have two parameters for lipophilicity that have different values:

-A value (Lipophilicity) assigned to the molecule 
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/129844980/1e7bc2f3-483a-4fe9-9be3-59983a50e502)

-A different value (Lipophilicity experiment) assigned to a reaction
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/129844980/ae4eb700-5fc3-460f-8e60-97a77cf48cb1)

Could you explain me exactly the difference please ? I should have only one Log P for my molecule.

Thanks

**Comment by PavelBal** [comment]
@chiarazuni please see the issue here for more explanation: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/3032

The value in the reaction is used for in vitro-in vivo extrapolation and should be optimized together with the lipophilicity value of the molecule.
