### ISSUE TITLE
When loading a V11 project - a separate module is created for each BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1353]
I have a project with exactly one simulation and one BB of each type. I would expect that all BBs will be in one single module when opening in V12. However, this is not the case.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/6c76d47b-e96f-42ce-b972-69ff6512bf86)

I cannot upload the project here but will send it to you via email.

**Comment by Yuri05** [comment]
The expectation is that if we have only 1 BB of each type - they will all be placed in the same module; and if we have >1 BB for at least one BB type - then each BB will be placed in a separate module?
In the vast majority of projects, the latter would be the case anyway.

**Comment by rwmcintosh** [comment]
It's worth an investigation anyway because we have specifically implemented this.

Can you attach this project? We will be able to create one ourselves, but it's probably going to work.

**Comment by rwmcintosh** [comment]
You should always change your theme before taking screenshots :)

**Comment by benjaperez1983** [comment]
If we open a project from V11 that either:

Contains exactly one of each of the 8 types needed for the simulation,
OR
Contains fewer than 8 types, but all are distinct,

then we will group them in the same module.
