### ISSUE TITLE
Cannot create a simulation from BBs after opening a V11 project

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1354]
Trying to re-configure a simulation or create a new from existing modules, I get the error:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/614c8ff0-18be-4ce7-be69-11333081a2ce)

**Comment by Yuri05** [comment]
It seems that `formulasAreTheSameForParameter()` called here (s. the screenshot) does not work correctly

<details><summary>Calling <b>formulasAreTheSameForParameter()</b></summary>

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/bbaa759f-99ba-4233-b054-5a121f21a533)
</details> 

The neighborhood keywords are not replaced here:

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/e27f191a-6f95-4dd1-8f3f-1f995589d9ae)

Those specific keywords are expanded not in **KeywordReplacer** but in the **FormulaTask**.

I tried to fix it by calling the proper method from the **FormulaTask**:

![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/09758cac-a07d-4d98-8f2f-5b21dc5f6707)

But this failed:
![grafik](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25061876/9bfee7a9-760d-49e4-8aef-b94b660dfb85)

Not sure how to proceed. Maybe @msevestre can comment on this?

**Comment by msevestre** [comment]
I am getting this error now:

@PavelBal 
Does this makes sense to you
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/02673ce1-e616-4dd2-bdbd-148fd18115d6)

**Comment by msevestre** [comment]
indeed Albumin is not in the neighbhorhoods
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/19a9c167-f62f-42d7-8aa3-107000b1da15)

**Comment by msevestre** [comment]
indeed Albumin is not in the neighbhorhoods
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/1041237/19a9c167-f62f-42d7-8aa3-107000b1da15)

**Comment by PavelBal** [comment]
Albumin is not present in the Intracellular compartments:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/48408aac-9453-414d-98ea-b6427d1609b9)

So it should not be present in this neighborhood. The weird thing is that `Organism|xxx|Interstitial|Albumin|Partition coefficient (water/container)` for albumin is calculated by the formula, though it is defined in the PV BB

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/6bd8d048-77bd-4d1b-ab39-a5ce3a73f3c2)


So the PV BB is not properly applied.

**Comment by PavelBal** [comment]
Okay, this is happening because every BB has been put into a separate module. So when creating a simulation, the parameter is first calculated by the equation and only later is overwritten by the fixed value stored in the PV.

I have updated the MoBi project in the repo and put all the required BBs (except for the Reactions because of https://github.com/Open-Systems-Pharmacology/MoBi/issues/1376) in the "Spatial Stucture" module. Trying to create a simulation from the modules "Spatial Structure" and "Reaction" will give the initial error about "another formula for parameter"

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/3cd85b16-c941-40f1-a9bc-a3371fd99fa6)

**Comment by msevestre** [comment]
>Okay, this is happening because every BB has been put into a separate module. So when creating a simulation, the parameter is first calculated by the equation and only later is overwritten by the fixed value stored in the PV.

I don't understand this. BB in one module works but BB in different module does not?

**Comment by PavelBal** [comment]
Yes this is something else. I simplified the project too much.. I think your fix will work, once it is merged I will try it with this project and update it accordingly.

**Comment by PavelBal** [comment]
Cannot reproduce.
