### ISSUE TITLE
Drag'n'drop from "Possible referenced objects" - append parent path of the selected container

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1363]
Similar as described here: https://github.com/Open-Systems-Pharmacology/MoBi/issues/1330

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/79be29c7-9445-4728-a918-1f53224af828)

The created path should be `Organism|Container B|Volume`, as `Container B` has `Organism` set as parent container.

**Comment by rwmcintosh** [comment]
Not from the same project but I imagine the spatial structure referred to by Pavel looks like this.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/dfffeb7c-a931-4a8b-9fa0-c9375d0f7294)

Container B is at the root of this spatial structure, but it has a `ParentPath` of `Organism`. Meaning, it should be inserted into an appropriately named parent container.
