### ISSUE TITLE
Parameter Values BB -> Add parameter value: better UI

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1367]
If the user wants to overwrite a default parameter value in the PV BB, he has to manually add this parameter as long it is not a protein expression or a local molecule parameter. The currently implemented workflow is not intuitive:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/7a15f478-1403-4087-a8a7-19eb4c600eb5)

After clicking on "New Parameter Value," an empty row with the columns "Parameter Name" and "Parameter Value" is created. The user would have to manually add columns "Path Element n" to be able to enter the path.

A possible solution would be a dialog where the user can either select a parameter that is present somewhere (like in all the places where the user selects a parameter), or enters the whole path which is then separated by `|` to create an entry in the PV BB.

**Comment by rwmcintosh** [comment]
We can just unhide 3 or 4 columns if there aren't any PV in the building block. Would that work?

I would also add a context menu here when the user right clicks in the blank space and allow them to add that way. We have recently implemented something like that in `copy formula` feature.

**Comment by PavelBal** [comment]
>We can just unhide 3 or 4 columns if there aren't any PV in the building block. Would that work?

Would work, but still very inconvenient.

**Comment by rwmcintosh** [comment]
We should enable `paste` of paths here. Recent feature allows you to copy paths to the Windows Clipboard. We could also paste them into the PV through context menu

**Comment by rwmcintosh** [comment]
> A possible solution would be a dialog where the user can either select a parameter that is present somewhere (like in all the places where the user selects a parameter), or enters the whole path which is then separated by | to create an entry in the PV BB.

Is there an existing view you're thinking of?

**Comment by PavelBal** [comment]
Yes, the "Possible fererences objects" viel from formula creation/editing. But without "absolute/relative path", it is always absolute in this case.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/ecc7127c-1dbb-4b7a-88ce-df713b10b642)

**Comment by PavelBal** [comment]
"Multiselect" would be awesome. I.e., I can select multiple entries in the tree view and it will add multiple entires to the PV BB.

**Comment by PavelBal** [comment]
> Recent feature allows you to copy paths to the Windows Clipboard. 

@rwmcintosh  where and how? Cannot find it.

**Comment by rwmcintosh** [comment]
I think it's only implemented as a keyboard shortcut. But we will add a context menu for it too.

@benjaperez1983  is working on it now.
