### ISSUE TITLE
Changing the "Default merge behavior" of a module should mark the simulation as "not synched"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1369]
Sync is noted by this green/red indicator on the module within the simulation explorer

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/88fc299a-0335-4ff1-a795-b88acd7f4816)

`TwoContainerModel` is not in sync, but `OrganismModule` is in sync.

You can change the default merge behavior of a module in the module explorer using the context menu

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/a53ed7d9-fc51-4104-aca1-b8b0fe4c198e)

Doing so should make the module representation in the simulation explorer red, but it does not.

**Comment by rwmcintosh** [comment]
Along with this feature - let's remove the possibility to override the module default behavior at the simulation level.

So, there will not be a 'DefaultBehavior', only 'Behavior'.

They should be the same.

**Comment by rwmcintosh** [comment]
Look for captions describing 'Default Merge Behavior'. It will be just 'Merge Behavior'

**Comment by rwmcintosh** [comment]
It's been renamed now and the context menu is just `Merge Behavior` without Default

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/a5c2b960-2f26-4870-b7e7-3c2ae150a0df)
