### ISSUE TITLE
Module: Add building blocks to module - do not show "Default merge behavior" selection field

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1373]
In the dialog for adding building blocks to the module, do not show the "Default Merge Behavior" field as it is disabled and cannot be changed.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/196d442b-e125-478e-a756-1885c57cd367)

**Comment by PavelBal** [comment]
Well, the property is for the whole module (and we discussed to somehow highlight the mode of the module, e.g. in the icon). With the current UI of adding building blocks, it might be misunderstood that a) this behavior is for the building blocks that are added at this step, and b) cannot be changed.

**Comment by rwmcintosh** [comment]
I see, it makes more sense when the operation will create a new module, but when editing a module, it's confusing.

**Comment by msevestre** [comment]
agreed

**Comment by rwmcintosh** [comment]
It's now just called `Merge Behavior`
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/51022f85-744e-4230-a9f4-4112b66ad9ab)
