### ISSUE TITLE
Container criteria: new condition "In children"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1374]
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/4245c57d-705d-4054-97c8-d3252369b6c9)

We have the container condition `In parent` which is very useful to get certain parameters located in the parent container of the current container.

It would be also very useful to have the `In children` condition, with the behavior similar to the `In container` condition but **excluding** the container itself.

Use case - a parameter `Volume` of the container `Organism` should sum up all `Volume` parameters of the childer of `Organism`. Right now, we require an additional tag assigned to all children containers of "Organism".

**Comment by PavelBal** [comment]
@Yuri05 @msevestre What do you think?

**Comment by PavelBal** [comment]
@Yuri05 @msevestre Is it possible for this version?

**Comment by msevestre** [comment]
yes

**Comment by msevestre** [comment]
here is the discussion on in Parent
https://github.com/Open-Systems-Pharmacology/MoBi/issues/837

**Comment by PavelBal** [comment]
lol it works!
