### ISSUE TITLE
Object Type resolver not used as expected

### ISSUE THREAD

**Issue by benjaperez1983** [Open-Systems-Pharmacology/MoBi#1384]
On many places around the code, the ojecttyperesolver is being called with the generic parameter as this:

ObjectType = new ObjectTypeResolver().TypeFor<T>();

This is causing the objecttype to be shown in an incorrect way, for example 
"I Building Block" instead of it`s actual implementation type "Molecule"

**Comment by msevestre** [comment]
yeah good catch
