### ISSUE TITLE
Transfer from PK-Sim: "Estimated gestational age" and "BMI" are missing a formula in the Individuals BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1397]
Create a human simulation in PK-Sim and transfer it to MoBi. Open the simulation and try to run - error:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/593e08eb-730d-4053-aac7-bf48e29ec3fc)

In the simulation, parameters "BMI" and "Estimated gestational age" are "NaN":

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/9c70fa61-d722-4b4b-a612-7b8f547a86ee)

In the Individual-BB, they neither have a value nor a formula:

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/5196aad1-39e1-4850-995b-ae7ab5547de1)

**Comment by rwmcintosh** [comment]
Is it the same as #1310 ?

**Comment by PavelBal** [comment]
Oh yes, couldn't find it.

**Comment by PavelBal** [comment]
Yes, indeed its project conversion. When recreating PK-Sim project from snapshot, the error does not occur.
