### ISSUE TITLE
Diagram conversion from older version done each time

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#140]
This is an issue we had before (see YouTrack # 46-7209). When loading a model created with an older version of MoBi, a conversion is done even though the project had been saved several times already with MoBi 7.1. This will lead to the safety question "Do you want to save the current project?" each time the project is only opened but nothing has been changed. It also will bloat the History list with entries as shown below whenever the project is really saved again, i.e., after making real changes.

State After Action	Command Type	Object Type	Description	User	Time
3615	Info	Diagram	Diagram 'Diagram' converted from version '6.3.1' to '7.1.0'	<user> 	2017-07-10 16:16

**Comment by msevestre** [comment]
Similar to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/183

**Comment by msevestre** [comment]
@UlrichSi Could you attach a project so that I can reproduce the issue? Thanks

**Comment by msevestre** [comment]
I have tried with numerous projects and cannot reproduce the issue. I was hoping that I could spare you the pain but I don't think so. Thanks @UlrichSi

**Comment by UlrichSi** [comment]
Please refer to YT issue #46-7471 regarding an example project.

**Comment by UlrichSi** [comment]
The example project's diagram is still converted to v 7.2 each time I load it, after having been saved. The history shows multiple conversion steps. 
State After Action	Command Type	Object Type	Description	User	Time
717	Info	Diagram	Diagram 'Diagram' converted from version '6.2.1' to '7.2.0'	zfsuu	2017-11-13 09:58
716	Info	Diagram	Diagram 'Diagram' converted from version '6.2.1' to '7.2.0'	zfsuu	2017-11-13 09:58
715	Info	Diagram	Diagram 'Diagram' converted from version '6.2.1' to '7.2.0'	zfsuu	2017-11-13 09:56

**Comment by msevestre** [comment]
There has to be some specifics here in the wokflow as I could not reproduce it anymore. 
I will try again and let you know

**Comment by msevestre** [comment]
@UlrichSi I do not have access to YT anymore. Can you send me the project by email?

**Comment by msevestre** [comment]
Cannot reproduce. Let's close for now and see if we can reproduce the issue in a consistent way

**Comment by UlrichSi** [comment]
Not reproducible any more on my side either. We'll keep a watchful eye on the history.
