### ISSUE TITLE
Every action that converts a PK-Sim module to an extension module should have a confirmation dialog

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1411]
Any action that will convert a PK-Sim module to an extension module should not only show a warning, but also have a "yes/no" option.

**Comment by PavelBal** [comment]
Yes, "The module will be converted".

**Comment by rwmcintosh** [comment]
Now I remember why this is implemented as notice instead of confirmation dialog. It's done _during_ command execution. At a point where backing out is not possible. In most cases you can reverse the command after.

This might require re-evaluating how we have this implemented.

**Comment by rwmcintosh** [comment]
Check this PR for a demo where I just converted one command execution.

https://github.com/Open-Systems-Pharmacology/MoBi/pull/1480/files
