### ISSUE TITLE
Spatial Structures in "Extend" modules - tags are not extended

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1413]
In a module with merge behavior "Extend", addition of new tags to a container that is present in the upper module is not applied in the simulation.

E.g., an xModule with a container "ArterialBlood" and a new tag "ExtendTag".
![image](https://github.com/user-attachments/assets/d6a7a126-6913-45a8-abc6-474f8d378ed4)

When combining this module with a PK-Sim module, the simulation only has the "BloodOrgan" tag but not the new "ExtendTag":

![image](https://github.com/user-attachments/assets/e70e39f6-04b7-4db9-9a25-63f7ee2a6154)

**Comment by PavelBal** [comment]
I think this should also be checked for tags of Parameters (and everywhere else?)

**Comment by msevestre** [comment]
Oh didn’t think about this at all

**Comment by msevestre** [comment]
@PavelBal I am not sure about parameter
In the case of parameters, we are REPLACING THEM instead of merging them

**Comment by PavelBal** [comment]
Yes you are right about parameters.

**Comment by msevestre** [comment]
this is also fixed
