### ISSUE TITLE
Merge behavior of BBs other than Spatial Structure

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1414]
It appears to me that both in "Extend" and "Overwrite" modes, reactions are completely replaced, i.e., overwritten. E.g. it is not possible to create only add a parameter to a reaction in an extension module. Just making sure that this is by design?

**Comment by PavelBal** [comment]
The same for Passive Transports... So "extend" and "overwrite" only differs for the SS BB?

**Comment by msevestre** [comment]
Yes this behavior is at the spatial structure level only.

**Comment by msevestre** [comment]
Removing the milestone here.
