### ISSUE TITLE
Export Parameter Values, Expression Profile and Initial Conditions BB to excel 

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1418]
Export the values stored in an PV BB into the excel structure that can be loaded.

**Comment by benjaperez1983** [comment]
@PavelBal  @rwmcintosh 
Do we have a current import excel file? I`m trying to figure out from the code, but will take me longer to do that.
In the meantime I can export all the data on an excel and them refine the fields.
Thanks!

**Comment by rwmcintosh** [comment]
Why not `IndividualBuildingBlock`?
