### ISSUE TITLE
"Volume" as a mandatory parameter of physical containers

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1419]
I want to have an extension module with the merge behavior "Extend" that adds specific parameters to the default PBPK structure.

Problem - for physical containers (e.g., `Lumen|Caecum`), the `Volume` parameter is always added and cannot be removed. It is therefore not possible to just add new parameters to any physical container without overwriting Volume.

Proposal - remove this restriction.

**Comment by msevestre** [comment]
so you just want to remove be able to remove the volume correcT?

**Comment by PavelBal** [comment]
Yes
