### ISSUE TITLE
Feature request: x64 bit version

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#142]
Due to high memory demands, a 64-bit version of PK-Sim/MoBi is needed.

**Comment by msevestre** [comment]
on the radar for a while.

**Comment by StephanSchaller** [comment]
@msevestre 
Do you have a release number for when this is planned?

**Comment by StephanSchaller** [comment]
Also compatibility with 64bit version of Matlab would be awesome!

**Comment by msevestre** [comment]
@StephanSchaller nope

**Comment by msevestre** [comment]
@StephanSchaller unfortunately :(

**Comment by msevestre** [comment]
A pilot project will be started in January to estimate the overall cost of such a migration. This is a significant work because the underlying database (access) does not work in 64 bit.. So all databases (PKSimDb, GeneExpression, Templates) need to be migrated to sqlite or the like

**Comment by StephanSchaller** [comment]
@msevestre - That's great news. Let us know if we can be of any help!

**Comment by msevestre** [comment]
FYI. We have started with the pilot project and will keep you guys posted. Testing is going to be the most critical part where help will be welcomed.

**Comment by StephanSchaller** [comment]
Thet's great news! :tada:

**Comment by msevestre** [comment]
@all: Work has started for 64bit migration

**Comment by PavelBal** [comment]
Wonderful news on this not so sunny day! :)

**Comment by msevestre** [comment]
@PavelBal That would be cool to try out the latest portable version of MoBi and see if anything is wrong (version from tomorrow)

This version is the same as 7.3 only with 64 bit support. I would not use if for production. Instead I'd like to hear about heavier load and see if this behaves better...

**Comment by PavelBal** [comment]
@msevestre Will it be under "Releases" from tomorrow on? Or where do I find it?

Will gladly test.

**Comment by msevestre** [comment]
@PavelBal I'll post the link here once this is ready. Stay tuned

**Comment by msevestre** [comment]
@PavelBal 

It should be enough to download this guy and unzip it. 
BEWARE: This might not work at all. No guarantee at that stage. All tests ran fine except SBML tests

https://ci.appveyor.com/api/buildjobs/xobrwvq16s2l2wj5/artifacts/mobi-portable-setup.zip

**Comment by PavelBal** [comment]
-It starts
-Loads the project
-Consumes 5.5 GB RAM directly after loading the project (which can also be loaded with x86 - memory load about 2.8 GB)
-Simulates
-PI starts and runs with 19 (!!!) simulations - unimaginable with x86!
-Utilizes almost all of the 8 threads, memory consumtion around 8 GB. In the next step I'll try out how well it gets along with 16 threads :)

Summary - this is a miracle!

**Comment by msevestre** [comment]
@PavelBal Great news
Going from 2.8 to 5.5 is almost exactly double the amount of Ram and is expected with the amount of Data we are using...

Once PK-Sim is migrated, we'll be able to run all our tests and ensure that calculations are also the same as before. Looking good tho

Thanks for testing it out with a serious project

Cheers,
