### ISSUE TITLE
"Extend" merge behavior - "Container type" is not applied

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1420]
The "Container type" property (logical vs physical) is not applied when combining modules.

**Comment by msevestre** [comment]
I don't think this makes sense
We are ADDING in an existing container
if it's Physical after the merge it's still physical no?

**Comment by PavelBal** [comment]
hmmm... yeah ok. I will document this.

**Comment by msevestre** [comment]
Happy to change if you think this is the better behaviour

**Comment by PavelBal** [comment]
For me as a user this was the expected behavior. Extend **adds new** entities/properties, and **overwrites existing** properties (e.g., existing parameters will be overwritten). So have assumed that the container type property is also overwritten.

**Comment by msevestre** [comment]
this is done. And it's container mode not container type FYI
