### ISSUE TITLE
Selecting a neighbor in the neighborhood view: behavior when the container is not present in the module

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1424]
The neighborhoods view shows the neighbors:

![image](https://github.com/user-attachments/assets/0496491c-4267-41ed-9200-6e11cf1e627e)

When selecting a neighbor that is present in the spatial structure of this module (in this case - `Organism|Bone|Lysosome`, the right panel shows the information about this container:

![image](https://github.com/user-attachments/assets/6ecd97e1-7810-43cb-8f4c-ca71b1dd9bd3)

**Problem:** when selecting a neighbor that is not present in this module (`Organism|Bone|Intracellular`), the view is not updated and just shows what was shown before:

![image](https://github.com/user-attachments/assets/6204451e-2c9a-4fb7-8709-01660481412e)

**Expected behavior:** the view is updated and is "empty", e.g., disabled (grey background), or a message "Container cannot be located in this spatial structure".

**Comment by benjaperez1983** [comment]
![image](https://github.com/user-attachments/assets/8388c773-1ca8-49eb-b944-56a9a603f65f)

**Comment by PavelBal** [comment]
Now this happens:

Application:
MoBi® 12.0.308

Object reference not set to an instance of an object.

Stack trace:
```
at MoBi.Presentation.Presenter.BaseDiagram.MoBiBaseDiagramPresenter`3.Handle(EntitySelectedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by PavelBal** [comment]
[null-pointer-neighbor.zip](https://github.com/user-attachments/files/16663130/null-pointer-neighbor.zip)

**Comment by rwmcintosh** [comment]
oh, I opened a different issue for fixing this in diagram manager

**Comment by rwmcintosh** [comment]
https://github.com/Open-Systems-Pharmacology/MoBi/issues/1498
