### ISSUE TITLE
Neighborhood selection dialog - selection of containers not always work

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1430]
Open any neighborhood and open the dialog for neighbor selection:

![image](https://github.com/user-attachments/assets/c9d054cc-c17e-4baa-95ac-509b23d85cf0)

- [ ] When a module is selected, the "OK" button should  be disabled:

![image](https://github.com/user-attachments/assets/0f4cddcd-7062-40fe-8bc0-6f3527f93720)

- [ ] Currently, when an organ (i.e., a container with children) is selected, "OK" is enabled but the path is NOT updated:

![image](https://github.com/user-attachments/assets/58df17d4-6a99-4e91-a1b7-ca5db950258c)

This should be changed to either:
1. It should be possible to select any kind of container and the right path is constructed (e.g., "Organism|Bone")
2. OR the "OK" button is only active when a **physical** container is selected

**Comment by benjaperez1983** [comment]
OR the "OK" button is only active when a physical container is selected

This should be the correct way to do it.
