### ISSUE TITLE
PI export in MatLab - cannot map "Fraction" to "Dimensionless".

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#144]
When exporting a PI with dimensionless parameter mapped to "Fraction"-data, MatLab reports following error:

Error using initParameterIdentificationForOSPSuiteExport>addOutputStructure (line 103)
output I1|Organism|Liver|Plasma|Insulin|OUTPUT_hepatic_extraction_AB_only and data IR_SS_fitData.IHE_Ferrannini_G1 have different dimensions!

**Comment by msevestre** [comment]
@PavelBal This is an issue in the Matlab ToolBox. Can you move this issue here please? Thanks
