### ISSUE TITLE
When importing a simulation from PK-Sim, set the project-wide simulation settings

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1442]
When opening one pkml from PK-Sim, set the simulation settings (output intervals, solver settings, output selections) from this simulation to project wide defaults.

**Comment by rwmcintosh** [comment]
Applies when you open the first simulation for a new project from PKML

**Comment by benjaperez1983** [comment]
![image](https://github.com/user-attachments/assets/fcafc6e3-a866-4682-aec0-9ed1a269a5d6)

**Comment by PavelBal** [comment]
Settings should be set also when sending the simulation from PK-Sim to MoBi.

**Comment by rwmcintosh** [comment]
Does this mean that no prompt will ever be necessary? 

Just assume that if this simulation is used to create a new project, those are the defaults and at all other times, there's not prompt necessary?

**Comment by PavelBal** [comment]
Hmm, true.

**Comment by rwmcintosh** [comment]
ok, I'll remove that check, and see what about sending directly. It seems like that's done by a temp file, but I'll check it.

**Comment by PavelBal** [comment]
And that the options are only updated when the project is started from a simulation, not each time a simulation is loaded?

**Comment by rwmcintosh** [comment]
well, there was a prompt if you loaded a pkml to ask, but it sounds like that should just be removed. We only set these if the simulation is sent directly from PK-Sim, or if you start a new project by opening a simulation.

If you start a new project, then load a simulation, you will not overwrite the project defaults.

So, in short - I'm just removing the prompt to ask users each time a pkml is loaded.
