### ISSUE TITLE
Wrong formula assigned when loading a pkml?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1444]
[Breasts.zip](https://github.com/user-attachments/files/16425635/Breasts.zip)

Attached is a pkml with an organ created with an earlier version of PK-Sim. When this pkml is loaded in a new module in MoBi v12, the parameter `Neighborhoods|Breasts_int_Breasts_cell|MoleculeProperties|Partition coefficient (intracellular/plasma)` has a formula `INTERSTITIAL PARTITION COEFFICIENT FORMULA` assigned:

![image](https://github.com/user-attachments/assets/aebb4deb-f69d-4645-b30b-475f66dcbdcb)

However, in the pkml, the parameter has a formula with ID `tQgO57HHP0-zG9T9D3J3Yg`

`              <Parameter id="EHhOufcGLkm5d3cNj3nx2A" name="Partition coefficient (intracellular/plasma)" description="Partition coefficient between intracellular space and plasma" icon="Parameter" persistable="0" isFixedValue="0" quantityType="Parameter" negativeValuesAllowed="1" formula="tQgO57HHP0-zG9T9D3J3Yg" isDefault="1">`

which is:

![image](https://github.com/user-attachments/assets/b8324a2d-98f9-4132-ab22-b81be86c4396)

`PARTITION COEFFICIENT FORMULA` which has a different ID.

**Comment by PavelBal** [comment]
This also happens with organs exported with V12.

**Comment by PavelBal** [comment]
This is very weird, as it seems that the simulation is created with the correct formula:

![image](https://github.com/user-attachments/assets/b60bdbef-2d0f-4c00-a364-2f10d9a765ab)

**Comment by msevestre** [comment]
I htink we match by path and not by id. We just say => HERE there is a black box formula, resolve later

**Comment by msevestre** [comment]
@PavelBal I don't get it. this name is not even defined in the PKML. I wrote a test in core showing that it was load properly

**Comment by msevestre** [comment]
I can't reproduce when starting Mobi
![image](https://github.com/user-attachments/assets/b65e42e9-3009-4875-8ae8-48443212bcfa)

I don't even know where the string is coming from
@Yuri05 Where is the name of the Black box formula coming?

**Comment by Yuri05** [comment]
> Where is the name of the Black box formula coming?

From PK-Sim DB
![grafik](https://github.com/user-attachments/assets/d0305985-06af-43c8-9b27-ee0b0ff610da)

**Comment by PavelBal** [comment]
> I can't reproduce when starting Mobi

lol how? Start mobi, new project, new module, load in SS BB:

![image](https://github.com/user-attachments/assets/1b8e3379-4658-4a56-bf19-36b6a8ccb0ba)

**Comment by msevestre** [comment]
This string is not even in the pkml. So it comes from somewhere and we don't have the same somewhere somehow lol. Or I could not find it it in the Pkml at least

**Comment by Yuri05** [comment]
> This string is not even in the pkml. So it comes from somewhere and we don't have the same somewhere somehow lol. Or I could not find it it in the Pkml at least

I can find them in pkml, e.g.

```
<SpatialStructure id="4fD1xORVzkSGzMquJCMmgQ" name="S1" icon="SpatialStructure" bbVersion="0">
  <GlobalMoleculeDependentProperties id="IXUATDQmfU2T_TmcSWjYNA" name="MoleculeProperties" description="Molecule dependent properties" mode="Logical" containerType="Molecule">
    <Children>
      <Parameter id="ZlFySHpHiEO__G38_Gh7mA" name="Partition coefficient (blood cells/plasma)" formula="zD1_hYKRd0eRwKMKCQ2wLw" description="Partition coefficient between blood cells and plasma" icon="Parameter" persistable="0" isFixedValue="0" quantityType="Parameter" negativeValuesAllowed="1" buildMode="Global" isDefault="1">
        <Info min="0" flag="122" seq="1" ref="0" bb="2" group="67" />
      </Parameter>
       ...
  <FormulaCache>
    <Formulas>
       ...
      <BlackBoxFormula id="QkkTfZBA80GGmxN2r0NygA" name="CELLULAR PERMEABILITY FACTOR RATE" />
      <BlackBoxFormula id="zD1_hYKRd0eRwKMKCQ2wLw" name="PARTITION COEFFICIENT FORMULA" />
      ...
```

**Comment by msevestre** [comment]
Pavel has "INTERSTITIAL PARTITION COEFFICIENT FORMULA"

**Comment by msevestre** [comment]
in the pkml, it's PARTITION COEFFICIENT FORMULA

**Comment by Yuri05** [comment]
same:
`<BlackBoxFormula id="vJGkxH62rUW-PhoORyo2Cg" name="INTERSTITIAL PARTITION COEFFICIENT FORMULA" />`

**Comment by msevestre** [comment]
nice. Well the load is non deterministic then :) lol

**Comment by msevestre** [comment]
@rwmcintosh I can't reprdroduce on my machine

Can you try ?

**Comment by rwmcintosh** [comment]
Also cannot reproduce:

![image](https://github.com/user-attachments/assets/6a2ce8ea-05c5-44d2-88a7-88b52051b054)

**Comment by PavelBal** [comment]
Okay @rwmcintosh let's try to do it in a videocall once I'm back.

**Comment by rwmcintosh** [comment]
It looks like BlackBoxFormula are always replaced during import.

![image](https://github.com/user-attachments/assets/6d90bdfc-e61c-4a59-9c76-5643bc07d51e)

That's done by the `_adjustFormulasVisitor` during import. 

In V11 it was done differently somehow and without the visitor, but I'm not sure how it was supposed to work because importing this particular PKML results in empty formula.

The formula adjuster replaces all black box formulas in the building block with whatever one was imported first because all non-null black box formulas are considered equal.

```
      public bool AreEqualBlackBoxFormula(BlackBoxFormula usedFormula, BlackBoxFormula alreadyUsedFormula)
      {
         return alreadyUsedFormula != null && usedFormula != null;
      }
```

**Comment by rwmcintosh** [comment]
Can we just include a name check in black box comparison so they are not removed unless the name is the same?

**Comment by Yuri05** [comment]
> Can we just include a name check in black box comparison so they are not removed unless the name is the same?

I think yes.
