### ISSUE TITLE
Loading a spatial structure triggers the "Formula 'DistributedTableFormula' not supported at the moment" error

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1454]
[Organism.zip](https://github.com/user-attachments/files/16469897/Organism.zip)

The attached pkml has been created by exporting the whole "Organism" structure of a PBPK model with an individual and multiple expression profiles selected.

Load this pkml as a container in a Spatial Strucutre BB of a module. An error is thrown:

Application:
MoBi® 12.0.296

Formula 'DistributedTableFormula' not supported at the moment

Stack trace:
```
at MoBi.Presentation.Presenter.FormulaPresenterCache.PresenterFor(Type formulaType)
   at MoBi.Presentation.Presenter.FormulaPresenterCache.PresenterFor(IFormula formula)
   at MoBi.Presentation.Presenter.FormulaCachePresenter.Select(IFormula formula)
   at MoBi.Presentation.Presenter.FormulaCachePresenter.Handle(AddedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

I know that the error will be fixed, but why does loading of the container triggers the presenter of a formula in the first place?

**Comment by rwmcintosh** [comment]
Can you check if DistributedTableFormula is the first one in the formula cache? I belive the formula cache tab is created and populated with the first formula, and just waiting for someone to click it.

**Comment by msevestre** [comment]
that's interesting

**Comment by rwmcintosh** [comment]
We could probably do something about this - the load triggers `AddFormulaToFormulaCacheCommand` which publishes an event, which forces a "select". So every formula in the container will be presented, but out of view.

This is going to be fixed by implement #1396, but if it's easy, we should prevent this from silently showing hundreds of formulas for no reason.

**Comment by msevestre** [comment]
> AddFormulaToFormulaCacheCommand which publishes an event, which forces a "select". So every formula in the container will be presented, but out of view.

Let's just add a property called silent or sthg
that does nto shtorwn the even. we did that for other command

**Comment by rwmcintosh** [comment]
There already is one. It just needs to be set in the case of adjustFormula

**Comment by rwmcintosh** [comment]
oh, but you need to throw an event somewhere to get the view to update lol
