### ISSUE TITLE
Exporting/importing of containers with selected expression profiles should also create entries for the IC BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1455]
[Organism.zip](https://github.com/user-attachments/files/16469897/Organism.zip)

The attached pkml has been created by exporting the whole "Organism" structure of a PBPK model with an individual and multiple expression profiles selected.

When this container is loaded in a SS BB, a PV BB is created (or the user can select an existing one) with the entries for the parameters coming from the expression profiles. The same should be done for the initial conditions.

**Comment by benjaperez1983** [comment]
This is already done by @rwmcintosh in #1504 #1505
