### ISSUE TITLE
MoBi crashes with a wrongly set up event

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1462]
In the attached project, there is an event that should increment the value of a variable `eventCounter` every time the event is fired. The checkbox "Use assignment as value" has wrongly been set to "false".

![image](https://github.com/user-attachments/assets/c8dabfd8-aebb-4cac-8cf2-782f39f8f30f)

When trying to run the simulation with "Plot parameter" selected for `eventCounter` (and only then!), MoBi silently crashes.
[endless-event.zip](https://github.com/user-attachments/files/16508172/endless-event.zip)

**Comment by benjaperez1983** [comment]
@Yuri05 This is at c++ code level, so most likely you are the chosen one.

Let me know if I can help you with anything

**Comment by rwmcintosh** [comment]
Can we check if cirucular references are checked on these formulas?

There's a formula task that has this check. Make sure it's running on this particular formula.

**Comment by rwmcintosh** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2325
