### ISSUE TITLE
Renaming a building block should not trigger "Rename related entities"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1467]
[PregnancyV1.zip](https://github.com/user-attachments/files/16509992/PregnancyV1.zip)

Similar to https://github.com/Open-Systems-Pharmacology/MoBi/issues/1343

In the attached project, when renaming the Spatial Structures BB "Organism" from the module "Pregnancy V2", the "Rename related entries" dialog appears:

![image](https://github.com/user-attachments/assets/10aa7972-3b6b-473d-9512-9d1a8e0cf997)

This should not be the case, the name of the BB is nowhere in the paths.

**Comment by rwmcintosh** [comment]
I think what's happening here is that the building block has the same name as the top container. There should be a distinction of the 'what' is being renamed here. If it's the top container, then you need this, if it's the building block, then you don't, even if the name is coinciding.
