### ISSUE TITLE
Neighborhood creation - path created for a neighbor contains "Organism" twice

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1468]
[PregnancyV1.zip](https://github.com/user-attachments/files/16509992/PregnancyV1.zip)

Module "Pregnancy V2", open the spatial structure BB, create new neighborhood. Select "Pregnancy V2|Endometrium|Interstitial" as a neighbor. The created path is `Organism|Organism|Endometrium|Interstitial`,  which is wrong (should be `Organism|Endometrium|Interstitial`

![image](https://github.com/user-attachments/assets/b110f114-ddb7-453c-8787-70563c6685a8)

**Comment by msevestre** [comment]
@rwmcintosh the fix that keeps on giving lol

**Comment by msevestre** [comment]
yes thsis is due to the fix in core.
