### ISSUE TITLE
Always show the "Update from building block" action

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1477]
![image](https://github.com/user-attachments/assets/070ddce0-e186-4bbb-9914-e3be83b16ed7)

Curently this is only shown when some differences to the BBs are detected. Well, why not always show it? There are some changes (e.g., changing the "create rate parameter", but also other) that are not directly shown in the simulation.

**Comment by Yuri05** [comment]
I think all actions which make it worth to update the simulation from BBs (changing the state of "Create process rate" parameter, changing the state of "Plot Parameter" etc.) should change the simulation status.
(compare https://github.com/Open-Systems-Pharmacology/MoBi/issues/1443#issuecomment-2278005272)

**Comment by PavelBal** [comment]
Okay, we can agree on that. However, still, let's have this action always displayed :)

**Comment by PavelBal** [comment]
MoBi 12 Build 350, "Update" is not always shown?

![image](https://github.com/user-attachments/assets/765ddfee-016c-45ac-9617-ccde97fb2b51)
