### ISSUE TITLE
Changing a parameter value in a simulation does not appear in the history.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1478]

**Comment by rwmcintosh** [comment]
What parameter were you changing? I tried one and I got one entry in the history browser.

Case closed?

**Comment by PavelBal** [comment]
Haha this is tricky. This is only for parameter defined by a formula and after resetting it.

- Change the value of `Organism|BMI` to anything. The action appears in the history:

![image](https://github.com/user-attachments/assets/a64c16d5-f547-47e4-94ca-9956ebab36c9)

- Change the value again - nothing in the history:

![image](https://github.com/user-attachments/assets/8d08f455-dae7-4041-b915-7a5e6bd2f9bf)


- Reset the value - nothing in the history:

![image](https://github.com/user-attachments/assets/cc5a0307-f426-47b3-90cc-0b28840456f4)

- Change again - no history entry.
