### ISSUE TITLE
When neighborhood is not present and selected diagram throws exception

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1498]
See this comment - https://github.com/Open-Systems-Pharmacology/MoBi/pull/1469#issuecomment-2296990955

To reproduce, select the diagram tab

![image](https://github.com/user-attachments/assets/2e60c260-5d90-4942-9a4b-c10d9617b96c)

When the diagram has not been viewed, the Selection event is unhandled. We will need to check if the handled object is null

```
     public void Handle(EntitySelectedEvent eventToHandle)
     {
        if (DiagramManager == null)
           return;
...
```

**Comment by rwmcintosh** [comment]
@PavelBal FYI

**Comment by PavelBal** [comment]
Now it does not throw an exception but jumps to the last opened tab :D
