### ISSUE TITLE
Rework actions in PV and IC BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1503]
![image](https://github.com/user-attachments/assets/b422cbc4-1c59-400a-8fc7-d78ffc7cb48b)

Instead of drop-downs and "for all" and "for selected", only show buttons for:

- Delete
- Refresh (IC only)
- Mark as present (IC only)
- Mark as not present (IC only)
- Neg values allowed (IC only)
- Net values not allowed  (IC only)

And they should only work on the **selected** items.

@rwmcintosh @Yuri05 FYI, we think this would be a better UX.

**Comment by rwmcintosh** [comment]
Can we do this as context menus and remove these from the top all together?
