### ISSUE TITLE
Export an organ to PKML: expression profiles are not exported

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1504]
When  saving an organ to PKML, the user can select an individual AND expression profiles.

The expression profiles information is not exported to PKML at all. What should be exported:

- Parameter values associated with the selected protein and organ
- IC

**Comment by rwmcintosh** [comment]
Hmm, we had this for individual parameters where we exported a separate building block but then we reversed that and put the individual parameters right in the spatial structure.

We are also doing that with the expression parameters where should they be kept separate? along with the IC? As a parameter values building block?

**Comment by rwmcintosh** [comment]
> We are also doing that with the expression parameters

But there's a bug in the export

**Comment by rwmcintosh** [comment]
> Hmm, we had this for individual parameters where we exported a separate building block but then we reversed that and put the individual parameters right in the spatial structure.
> 
> We are also doing that with the expression parameters where should they be kept separate? along with the IC? As a parameter values building block?

My mistake. The bug I mentioned prevented the export of a `SpatialStructureTransfer` which combines spatial structure and PV building block

**Comment by rwmcintosh** [comment]
We are exporting the expression parameters as ParameterValues, should the initial conditions of the expression be exported as a separate IC building block, or as ParameterValues in the same building block as the expression parameters?
