### ISSUE TITLE
PV BB -> New Parameter Value: Allow multiselect

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1506]
Allow selection of multiple parameters (witch "Ctrl") and adding them.

**Comment by rwmcintosh** [comment]
like this?
![image](https://github.com/user-attachments/assets/2a56596c-c478-4a3e-8fc7-4007fd18b73d)

**Comment by rwmcintosh** [comment]
oh, when adding. Ok
