### ISSUE TITLE
PV BB -> New Parameter Values: for neighborhoods, do not show neighbors

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1507]
![image](https://github.com/user-attachments/assets/05205a43-2b50-4f92-a87e-92442ee17468)

Currently, the neighbors are shown as separate containers. This is not necessary here, they should be excluded. So show only parameters of the neighborhood (or the molecule parameters in this neighborhood).

**Comment by rwmcintosh** [comment]
@PavelBal can you try to reproduce? It may have been solved by another fix.

**Comment by PavelBal** [comment]
All good.
