### ISSUE TITLE
PV BB -> New Parameter Value: also show parameters from ExpProfiles and Individuals

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1508]
As separate groups.

**Comment by rwmcintosh** [comment]
What do you mean by separate groups? I've got the nested tree building, but I expect you want a node for Expressions and a separate node for Individuals or something?

![image](https://github.com/user-attachments/assets/b539b9d8-1fda-4eb3-b074-aab658047e0e)

**Comment by PavelBal** [comment]
Yes looks good.

**Comment by rwmcintosh** [comment]
> Yes looks good.

Do you mean it's good like this? Or you want a node to group expressions together and another node to group individuals, probably a third to group spatial structures as well?

**Comment by PavelBal** [comment]
Looks good like in the screenshot.
