### ISSUE TITLE
PV BB: New parameter value - required columns are not added

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1526]
When creating a new (empty) PV BB, only the columns "Parameter Name", "Parameter Value", "Value Origin", "Formula", and "Dimension" are shown.

When adding parameter through "New Parameter Value", the entries are added but the required columns are not added:

![image](https://github.com/user-attachments/assets/a7505377-e24c-42ef-adb3-aa1bedbf58b6)

**Comment by PavelBal** [comment]
Create two views - on the left side the tree view, on the right a text field with parameter paths.
Button that "transfers" selected parameters from the tree view to the text field, creating full paths.
Paths are separated by `;` and newline.
User can edit and add new paths.

Button "OK -> creates entries in the PV BB for the entered paths.

**Comment by rwmcintosh** [comment]
We are specifically not enabling additional columns unless it's the first row added I think. The idea is that if there are no elements in the list then it's reasonable to assume the user has not set the view to their liking. If there is already a showing row, the user may have configured the columns as they want them, so we don't change it.

The column chooser needs to be available thoguh.

**Comment by rwmcintosh** [comment]
Column chooser re-introduced in #1562
