### ISSUE TITLE
PV BB: New parameter value - Notification for dimension check

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1527]
Now, when adding new entries through the "New Parameter Value" button, all entries have the dimension "Dimensionless". Instead, they should have the dimension of the parameter selected from the tree view.

**Comment by rwmcintosh** [comment]
We probably can't do this with the proposal in #1528 
We are going to have to assume all the paths entered are dimensionless if we do this by text entry.

**Comment by PavelBal** [comment]
Yes true... well, okay.

Maybe add a note "Warning - check the "Dimension" property of the added parameters".
