### ISSUE TITLE
When loading a simulation, some building block is automatically opened.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1529]
1. New MoBi project
2. Load simulation from pkml
3. Events-BB is opened?? :D

**Comment by rwmcintosh** [comment]
I can't reproduce. maybe attach the pkml?

**Comment by PavelBal** [comment]
True, does not happen with every simulation.

Take the pkml from here https://github.com/esqLABS/bug-reports, `main` branch.

**Comment by rwmcintosh** [comment]
I don't see any PKML in there. It's a mobi file.

**Comment by PavelBal** [comment]
Oops, did commit but no push.

Should be there now.
