### ISSUE TITLE
SetupTableParameters.m after exporting to Matlab

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/MoBi#154]
After exporting a simulation to Matlab as differential equations, should the function file SetupTableParameters.m be empty? If I run the main file (ODEMain.m) it doesn't throw an error about it, so I assume it's ok. I'm wondering what the SetupTableParameters function does in this case?

**Comment by Yuri05** [comment]
>If I run the main file (ODEMain.m) it doesn't throw an error about it, so I assume it's ok.

Yes :-)

> I'm wondering what the SetupTableParameters function does in this case?

Nothing. It's just a function stub which is always generated. If there are no parameters in your model which are described by table formulas, it has no effect

**Comment by mlcraig** [comment]
Thanks @Yuri05 ! One follow-up: per issue #155 , you cannot export from MoBi to the Matlab ODEs with table formula (without the workaround you highlighted there, thank you for that). So essentially the SetupTableParameters.m file will always be empty. Is that correct?

**Comment by Yuri05** [comment]
Nope :-)
You cannot export table formulas **with offset**; you can export table formulas (without)

**Comment by mlcraig** [comment]
Right, thanks for pointing that out!
