### ISSUE TITLE
Table formulas with offset not supported by matlab export

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/MoBi#155]
I have successfully exported one of my MoBi projects to Matlab as differential equations but when I try to export a different compound, I receive the following error:

"Table formulas with offset not supported by matlab export
FormulaID =  9815"

Any advice on the source of the error/how to fix it? Thanks!

**Comment by Yuri05** [comment]
Not all modeling features can be exported to Matlab ODE equations at the moment.
One not supported feature are so called “Table formulas with offset” (will be implemented in one of the next OSP versions)

You will have such a formula in your model if for example you have defined an oral application with a table formulation (which is also the most common case for this kind of formulas)

Workaround for now:

If you have **_exactly one oral application with table formulation starting at t=0_**
* In MoBi, open the Events building block used in the Simulation you want to export.
* Find your oral application and navigate to **ProtocolSchemaItem**
* Click on the parameter **Fraction (dose)**
* You will see, that its formula is defined by “Table Formula with Offset” (s. screen below)
![001](https://user-images.githubusercontent.com/25061876/28308486-a1b2074a-6ba6-11e7-8009-de173de927e5.jpg)

* Change formula type from “Table formula with offset” to “Table”
* **After that**, select formula “Fraction (dose)” from the dropdown menu . The result should look like in the screen below
![002](https://user-images.githubusercontent.com/25061876/28308531-c1eb1222-6ba6-11e7-8854-55e103696173.jpg)
* Create new Simulation using adjusted Events building block
* If changed formula was the only one of type “Table formula with offset”, you will be able to export it to ODE now

If your oral application with table formulation starts at t>0 or if you have more than 1 oral application with table formulation, there is also a workaround in MoBi for exporting the ODE, which is more complicated. Please let me know.
