### ISSUE TITLE
Simulations can be deleted although they are part of Parameter Identification

### ISSUE THREAD

**Issue by MarKrauss** [Open-Systems-Pharmacology/MoBi#156]
It should not be possible to delete a simulation with which a PI was performed, at least a warning should appear which states that afterwards also PI and Sensitivity Analyses cannot be used anymore. 
[Test Project.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1154976/Test.Project.zip)

**Comment by msevestre** [comment]
@rwmcintosh don't we have that already??

**Comment by MarKrauss** [comment]
We have an unspecific warning so far, but no specific one which tells the user that this simulation is used in a certain PI. In my opinion a user should not be able to delete a simulation before deleting the related PI when the PI becomes useless afterwards. Another possibility would be to store all information about the PI even after deleting the simulation.

**Comment by msevestre** [comment]
so here is the warning at the moment: (Version 7.2)

```
MoBi

Do you really want to remove Simulation 'Wisman et al' from tumor model.  Wisman et al will also be removed from parameter identifications and sensitivity analyses
```


```
PK-Sim®

Really delete simulation 'Kaumeier IV 100 mg'?
Simulation results will be permanently deleted.
Moreover simulation will be removed from all comparison charts, sensitivity analyses, and parameter identifications.
```

I think we should unify the messages but in my eyes, the message is clear. Or what issue do you have with this?

**Comment by msevestre** [comment]
Is this an issue still?

**Comment by MarKrauss** [comment]
Yeah for me it is an arbitrary warning, so a specific warning that the simulation to be deleted is actually part of a PI or SI and that this SI or PI cannot be used properly afterwards would be quite important from my point of view.

**Comment by msevestre** [comment]
Sorry  @MarKrauss but  I don't quite understand what you mean with `arbitrary warning`. do you mean `generic warning`?

```
...
Moreover simulation will be removed from all comparison charts, sensitivity analyses, and parameter identifications.
```
This is a very specific warning this is being shown here. Not sure what else to add.

Could you please elaborate and let me know what is the message that you would like to see. That should clarify everything :)

**Comment by MarKrauss** [comment]
Haha sorry, yeah I mean generic ;-)

My propsal: "Really delete simulation 'Kaumeier IV 100 mg'?
Simulation results will be permanently deleted.
Moreover simulation 'Kaumeier IV 100 mg' is used in 'Parameter Identification/Sensitivity Analysis/Comparison Chart "XXX"', which cannot be further used when deleting this simulation."

**Comment by Yuri05** [comment]
Warning looks good for me. Please reopen, if you still have a different opinion
