### ISSUE TITLE
Favorites list: Tooltip should show the content of the cell under mouse cursor

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#159]
In the favorites list of a simulation, only the name and description of the parameter under cursor is shown as tooltip. It would be of much better help if the content of the respective cell, e.g., the "Container" cell, would be shown.
![tooltip](https://user-images.githubusercontent.com/25903040/28610431-a30a6b12-71e8-11e7-93d9-ffcf10b11ce0.png)

**Comment by Ian-Du** [comment]
All the parameters view behave the same with regards to their tooltips. Currently, it will always show the Name value and its corresponding tooltip
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/113724279/a4afed45-040e-46f2-b3c6-d9abd1ad4492)

If we go by content per cell, it will show this tooltip for those cells. Is this the values that you want to be shown
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/113724279/7f8b836b-7313-4695-8ccf-fb38df525f74)
