### ISSUE TITLE
Create process option when configuring a simulation

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#1606]

**Comment by rwmcintosh** [comment]
There are two flags that are related to process rate parameters in a process builder. One is called `ProcessRateParameterPersistable` and the other `CreateProcessRateParameter`.

What I've done here is create a single checkbox on the simulation configuration that overrides both properties for all process builders when true and not affect the values when false.

Is it true that this flag should override both properties in the process builders?

![Image](https://github.com/user-attachments/assets/807bd636-6a8c-4542-a4d1-0b5702cc9458)

**Comment by PavelBal** [comment]
No, only "create". "Make persistable" will plot them (and this should be selected manually by the user, I think)

**Comment by rwmcintosh** [comment]
Under the name or beside?
![Image](https://github.com/user-attachments/assets/aaac3076-07cf-485e-82f0-3369aa0dc1c2)

**Comment by PavelBal** [comment]
Under
