### ISSUE TITLE
It should not be possible to create multiple neighborhoods with same neighbors

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1618]
[neighborhoods-diff-name-same-neighbors.zip](https://github.com/user-attachments/files/17630328/neighborhoods-diff-name-same-neighbors.zip)

Currently, it is possible to create multiple neighborhoods between the same two containers but with different names. This can result in transport processes being created multiple times and unexpected model behavior (spent almost 5 hours debugging a project).

This should not be allowed; only one neighborhood between the same two containers should be allowed. Therefore, at the simulation creation step (when combining the modules), for each NEW neighborhood (i.e., the neighborhood with a new name), it should be checked whether a neighborhood between the specified containers already exists (disregarding what the first or the second neighbor is). 

To speed up the process, maintain a map of neighborhood paths that are already connected?

If a new neighborhood between two already connected containers is being added, show an error "Neighborhood \<NeighborhoodName> cannot be created because a neighborhood between the containers \<Container1> and \<Container2> already exists. Every pair of containers can be connected by one neighborhood only".

Attached is a project for testing. It contains three modules and three combinations of the modules (simulations). "Module 1" has three containers - A, B, and C, and the neighborhoods between containers A and B and between B and C, and the simulation "Valid_Simulation" can be created from this one module:

![image](https://github.com/user-attachments/assets/2f27d47e-fba4-4b48-b716-785b0d7be572)

Module 2 defines a neighborhood between containers B and A, and it is combined with the first module to the simulation "Invalid_1", which has two neighborhoods between A and B. This should NOT be allowed:

![image](https://github.com/user-attachments/assets/feb70011-e05d-4f3d-8750-d392224af387)

Module 3 defines a neighborhood between A and B (the same as Module 1, but with a different name). It is combined with the first module to the simulation "Invalid_2", which again has two neighborhoods between A and B. This should NOT be allowed:

![image](https://github.com/user-attachments/assets/409b9493-e866-4378-9884-eb835435fb4e)

**Comment by rwmcintosh** [comment]
Within a module we can probably prevent equivalent neighborhoods being created. Just comparing paths of the neighborhood being edited to the existing ones (irrespective of the neighbor order).

But when combining two modules, why not just silently collapse equivalent neighborhoods from different modules into one? Is there a need to alert the user?

**Comment by rwmcintosh** [comment]
This original issue has two parts 
1. Prevent duplicate neighborhood creation within a Spatial Structure (in MoBi) 
2. If multiple modules define the same neighborhood, with a different name, show an error and do not create a simulation (in Core)

**Comment by PavelBal** [comment]
Nice! I like how the validations are performed at different steps - selecting the neighbors from the tree view but also manually typing in the paths.
