### ISSUE TITLE
V12 beta: Possibility to delete initial conditions container missing

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/MoBi#1634]
In Mobi V12 beta, I wanted to re-order to project and thus I wanted to delete the Molecules Building Block and Initial Conditions Building Block. This worked for the Molecules Building Block and the individual Initial Conditions Building Blocks but not for the top container of the Initial Conditions (see screenshot)

![DeleteIC](https://github.com/user-attachments/assets/4435e6e7-aaa8-420a-8fde-47cbac15fb98)

**Comment by rwmcintosh** [comment]
Hi @Christoph27, this is just a grouping folder and shouldn't have any affect if present without any contents.

I take the point that when you delete the last `Initial Conditions` building block, the folder can also be removed with it.
