### ISSUE TITLE
How to link the observed data to the simulation results in MoBi 11 Update 3

### ISSUE THREAD

**Issue by jiangz-98** [Open-Systems-Pharmacology/MoBi#1638]
I sent the simulations from PK-Sim to Mobi and added some differential equations to the physico-chemical parameters in MoBi. The simulation in PK-Sim includes the observed data and it can be shown in the simulation results. However, the observed data can not display on the simulation results in MoBi even through it can be found in the "Observed Data" from the "Building Blocks".

Could I ask how to link the observed data to the simulation results in MoBi? I plan to run the parameter identification by using the observed data in MoBi as the next step.

Thank you for your time!
<img width="1107" alt="Screenshot 2024-11-11 103159" src="https://github.com/user-attachments/assets/92dd5a4a-dc29-407b-80a4-ebcbb8590c44">
<img width="277" alt="Simulations in PK-Sim" src="https://github.com/user-attachments/assets/e5043f9f-72d6-482f-a395-9dce944e6bf6">

**Comment by rwmcintosh** [comment]
Can you drag and drop the observed data from the building blocks into a result chart for the simulation? After that the observed data should appear in the chart and allow you to assign output mappings

**Comment by jiangz-98** [comment]
Thank you very much for your suggestion! I tried this before but it was not working. Probably I did something wrong. It's working now!
