### ISSUE TITLE
Copy path of a parameter/container in the simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1639]
For parameters, a context menu entry "copy path" is implemented in the building blocks, but this actually should also be available in the simulation.

Additionally, copying a path to any container should be possible.

**Comment by PavelBal** [comment]
What is missing are the parameter entries of the selected container:

![image](https://github.com/user-attachments/assets/0d59e4fc-e669-438f-b111-ba31347129e3)

**Comment by peterdew** [comment]
![image](https://github.com/user-attachments/assets/8baa6be3-a1d3-4394-b59d-acadbeecff38)

**Comment by peterdew** [comment]
@PavelBal 
Copying a path from a container was already possible. 
Like here: 
![image](https://github.com/user-attachments/assets/9ccaf90f-094f-4f45-8bac-abc989cb65f1)
0 mg/kg  (vehicle)|Organism|Brain|BloodCells

Do you agree that this covers this issue?

**Comment by Yuri05** [comment]
For containers **in a simulation,** this does not work anymore.
Reopened the issue https://github.com/Open-Systems-Pharmacology/MoBi/issues/472

**Comment by PavelBal** [comment]
This does not work for containers.

**Comment by PavelBal** [comment]
@rwmcintosh @benjaperez1983 Possible for 12.1?
