### ISSUE TITLE
Extend IC from BB - values are not overwritten?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1644]
![image](https://github.com/user-attachments/assets/37ee625c-1b35-4d24-893a-f70d66254b7b)

When "extending" from a pkml - are values only added but not overwritten? They should be overwritten (so it is more of "Import from Building Block" rather then "extend").

**Comment by rwmcintosh** [comment]
There should never be two with the same path in the same building block. So, it should be overwritten if the path already exists.

**Comment by rwmcintosh** [comment]
Ok, I see what you are saying. The import contents are not duplicating entries, but keeping the current value rather than using the new value.
