### ISSUE TITLE
If I commit to bulding blocks and try to roll back the action in the history, I get the message below and no rollback.

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1657]
If I commit to bulding blocks and try to roll back the action in the history, I get the message below and no rollback.
Is it as expected? 
@PavelBal @rwmcintosh @msevestre @benjaperez1983 
![grafik](https://github.com/user-attachments/assets/63227469-06ff-47c0-9a4e-7f3accda6994)

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/MoBi/issues/1653#issuecomment-2474441013_

**Comment by PavelBal** [comment]
@rwmcintosh can this action can be reversible?

**Comment by rwmcintosh** [comment]
Pretty sure it can
