### ISSUE TITLE
Removing Initial Conditions or Parameter Valuesfrom PK-Sim module does not ask for changing to extension module

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#1659]
When removing an initial conditions (or parameter values) BB from PK-Sim module: only the prompt below (btw. the question mark is missing in the prompt caption) comes. But not the warning, that PK-Sim module will be converted to extension module.
And when rollbacking the action: the building block is restored, but extension module does not become PK-Sim module again.
![{14000DB5-6731-48DA-B820-103C6B986485}](https://github.com/user-attachments/assets/193e7a8c-3ea9-4c87-aa1a-4b36cb0d2014)

**Comment by rwmcintosh** [comment]
Well, this is also the case for any content change in a module... Remove spatial structure etc...
