### ISSUE TITLE
When adding new parameters through PV BBs, it should be possible to set the "Global/Local" property

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1687]
Currently, when adding a new parameter to the simulation structure through the PV BB (which is a suuuuuper cool feature), these parameters are always defined as local parameters and created everywhere. It should be possible to specify whether the parameter is local or global.

Would be super cool if it gets into v12.

**Comment by msevestre** [comment]
I don’t get it. Don’t you specify parameter by path in the PV? How can it be added everywhere?

**Comment by PavelBal** [comment]
Hmm... true :D @VanessaB could you check your use case?

**Comment by PavelBal** [comment]
Okay misunderstanding...
