### ISSUE TITLE
Parameter with flag CanBeVaried set to false should be excluded from PI

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#170]
This should be in implementation of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/316
Possibly ReadOnly parameter as well. (A ReadOnly Parameter should never be CanBeVaried anyways)

**Comment by Yuri05** [comment]
>A ReadOnly Parameter should never be CanBeVaried anyways

There are some. E.g. Fractions Interstitial/Vascular/Intracellular.
So ReadOnly should be also taken into account

**Comment by msevestre** [comment]
Fraction intestinal are can be variend? That means that the sum if for sure wrong no? I think this is a bug

**Comment by Yuri05** [comment]
I don't think so. It should be possible to vary the fractions in Matlab/R. As one of the fractions is defined as `1-fraction1-fraction2`, it will only become a problem if this fraction is varied or if `fraction1+fraction2>=1`. And those cases should be catched by (advanced) users in Matlab/R

**Comment by msevestre** [comment]
ok but MoBi should excluded REadOnly parameters in my opinion as well as parameter that are not CanBeVaried

**Comment by StephanSchaller** [comment]
I think this is a critical issue!

I think here, CanBeVaried in PI or Population need to be aligned.
In general only allow independent parameters to be varied (i.e. organ volume, but not BodyWeight).
And I agree with @Yuri05, that there has to be some freedom to the user (give us the credit ;-)).
This is especially the case for parameters for physiology (as often they sum up in some way as for fraction int/vas/cell).

However, there is a gap for preclinical species: we are missing physiological variability!
This means, for dose/BW applications you will always get the same Cmax within a population a populations are linearly scaled. 
But here is the problem: flagging plasma or Organ Volumes for "User Defined Variability" in a population Simulation is not possible. 
So either we need better animal populations, or allow user defined variability!

**Comment by UlrichSi** [comment]
Please make sure this will not cause a similar issue as described in #208 !

**Comment by msevestre** [comment]
>So ReadOnly should be also taken into account

What do you mean here @Yuri05 ?
