### ISSUE TITLE
"Simulation configuration wizard" layout broken

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#1707]
![image](https://github.com/user-attachments/assets/dd2cb7a5-2e8f-4dcd-9aa0-f477a1281e39)

The "Previous"/"Next"/"Cancel" buttons moved to the left (I expect them on the right) and are misaligned.

**Comment by rwmcintosh** [comment]
This always happens whenever you just _touch_ the designer.
