### ISSUE TITLE
MoBi stopped working

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/MoBi#183]
This is an issue that I had when I tried to open an sbml file from the Biomodels database. Suddenly MoBi gives the error msg attached and shuts down. This doesn't happen every time though as sometimes it successfully opens the file.

This is the msg:
![image](https://user-images.githubusercontent.com/31896854/30707760-894f52be-9eca-11e7-8d04-49bb9178a094.png)

and this the sbml file:
[BMID000000063853.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1322082/BMID000000063853.zip)

**Comment by Yuri05** [comment]
Unable to reproduce with MoBi 7.3
Please reopen the issue if the problem persists.
