### ISSUE TITLE
can't import xml

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/MoBi#184]
Hi,
I was trying to open an xml file of a diabetes model that was developed in pk-sim/mobi but I don't seem to find an import xml option. I tried the sbml but it doesn't work. Is there another way I can open the model in mobi?
This is the xml file:

[psp4201340-sup-0005.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1325114/psp4201340-sup-0005.zip)

**Comment by msevestre** [comment]
You have to use the mobi project file.

https://github.com/Open-Systems-Pharmacology/Glucose-Insulin-Model/blob/master/GlucoseInsulinModel.mbp3

The XML is a one way export only that can be used in Matlab, R etc...

**Comment by msevestre** [comment]
And I would strongly suggest to read the readme file explaining how to use the model

**Comment by aelmokadem** [comment]
Thanks a lot Michael for the fast reply.. Indeed the file works and I will go through the readme file.

**Comment by msevestre** [comment]
Great news. Cheers

**Comment by msevestre** [comment]
Great news. Cheers
