### ISSUE TITLE
Observed data import: override of default range does not work

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#192]
1. Create a new project
2. Right-click "Observed Data", select "Add Observed Data"
3. Select the attached xlsx data file. Several columns of PK data will appear, time in hours, conc in nM.
4. We want to import only the second data set, i.e., columns 4 and 5. To proceed to the selection menu, click the "Preview Original Data" button below the table. A new window showing the table will appear.
5. Select the data range of columns 4&5, starting with row 3 (the headers) and going down to the last values, i.e., the 24 h value. Then click "Ok".
6. The selected range will appear in the left part of the window. In the right part, "Time" and "Measurement" are correctly interpreted. 
7. Click on the "Import(1)" or on the "Import All" button. Either way, the data that now show up on the "Imports" window is NOT the data set selected but instead the data from columns 1 and 2 of the original Excel worksheet.

The same happens on multi-select. 

[Nolan2013PKdata.xlsx](https://github.com/Open-Systems-Pharmacology/MoBi/files/1441136/Nolan2013PKdata.xlsx)

**Comment by msevestre** [comment]
I cannot reproduce the issue in 7.2
![image](https://user-images.githubusercontent.com/1041237/32617110-205cd0e4-c542-11e7-937b-5a3191a1cc1d.png)

**Comment by msevestre** [comment]
can you try using the following download link (unzip folder) and let me know if you can reproduce the issue?

https://ci.appveyor.com/api/buildjobs/ojbekqn3ppbspocl/artifacts/mobi-portable-setup.zip

**Comment by msevestre** [comment]
@UlrichSi Sorry it's in the graph that the data are not the same
I could reproduce the issue!

**Comment by msevestre** [comment]
This will be implemented as part of the Importer Redesign

**Comment by Yuri05** [comment]
obsolete with observed data redesign
