### ISSUE TITLE
Observed data import: Lists of more than 2 columns are not properly resolved.

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#193]
1. Follow steps 1-3 of issue #192. Use the data file attached to that issue.
2. Manually adjust the mapping headers to have time in hours in columns 1,4,7 & 10, and to have measurement/concentration in nmol/l in columns 2,5,8 & 11. The empty columns should remain on "<None>".
3. Click on the "Import(1)" or on the "Import All" button. Either way, instead of 4 data pairs, 16 are generated. It appears that every time column is combined with every concentration column. If this is a feature, it should be possible to deselect this behavior.

**Comment by msevestre** [comment]
@UlrichSi 
What pairing are you expecting? Or in other word, how should the importer know which Time should go with which concentration?

**Comment by UlrichSi** [comment]
I would expect that neighboring columns are paired, at least as a (de)selectable option.

**Comment by Yuri05** [comment]
obsolete with observed data redesign
