### ISSUE TITLE
Parameter "F" is not shown in PI parameter selection

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#208]
While the parameter name "F" may be used for a molecule (F is often used for "bioavailability"), it cannot be selected in the parameter identification "Parameters" tab. For some reason (suspect is the "F" as number of fluorine atoms in PK-Sim)  is masked.

**Comment by msevestre** [comment]
Do you mean that any parameter named "F" is not shown in the PI? 
Or that the parameter F from a molecule coming from PKSim is not shown?

**Comment by UlrichSi** [comment]
My project was started from scratch in MoBi, no PK-Sim molecule was part of it. A parameter "F" added to a reaction is shown neither.

To reproduce, open the ManualModel. 
1. Add a parameter called "F" to molecule "A" as global or local. Also, add a parameter called "G" as a "negative control". 
2. Add a parameter "F" to the reaction R1 as well, and possibly also "G". 
3. Update the simulation S1.
4. Create a PI task, select S1 as simulation.
5. Click the parameters tab and check what is present. Any Fs, anywhere?

**Comment by msevestre** [comment]
This is so weird it's almost funny. Going to look at that and see if I can reproduce .I'd appreciate if you could attach a project as always, so that I can get right to the problem

**Comment by UlrichSi** [comment]
Just use the Manual Model project as example, see procedure above to reproduce.

**Comment by msevestre** [comment]
I can reproduce. crazy

**Comment by msevestre** [comment]
ok so this is indeed a bug/feature in implementation

The code responsible for that is [here](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/f75c2b2f6a639a8a8f27e4937358ad7819e87ba0/src/OSPSuite.Core/Domain/Services/IParameterAnalysableParameterSelector.cs#L35)

Basically the idea is that some parameter that only get discrete values (such as true, false or yes no) etc.. are excluded from the PI. 
It happens that we have included halogens parameter here that also have a list of values (1 to 10) to make edit easier.. But clearly they do not belong here.

**Comment by UlrichSi** [comment]
Thomas G suspected that too when I showed it to him last Friday. It really is a crazy behavior. Together with the other issues I put in today it made work quite interesting. ;-)

**Comment by msevestre** [comment]
@UlrichSi This will be fixed in current implementation
