### ISSUE TITLE
Observed Data import will not properly handle CSV files with continental European standard

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#210]
Use the attached CSV file which was produced in Excel set to German standards. Note that the numbers use a comma as decimal separator and a semicolon as column separator.

When importing this to MoBi Observed Data, the  columns are well separated but many numbers are ill-converted, as can be seen in the sheet window of the import function.

Current workaround: load into Excel, save as xls(x) file, then import.

[TestDataMoBi-Import.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1505194/TestDataMoBi-Import.zip)

**Comment by Yuri05** [comment]
obsolet with observed data redesign
