### ISSUE TITLE
Right-click underneath tabs in Parameter Identification displays "Customize Layout"

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#213]
When right-clicking into the empty space or some of the headlines (e.g., "Configuration/General") in the PI window tabs, a "Customize Layout" option is displayed. Clicking on it displays a not self-explaining functionality - most likely not intended.
See screenshots below.

![grafik](https://user-images.githubusercontent.com/27352743/33325577-f66b9570-d452-11e7-83fe-b6913f3dc307.png)
![grafik](https://user-images.githubusercontent.com/27352743/33325627-15e6a6b0-d453-11e7-8ae4-4191b8140a73.png)

**Comment by msevestre** [comment]
each instance of LayoutControl needs to be replaced with our own UxLayoutControl to remove that behavior

**Comment by UlrichSi** [comment]
Yuri05 just tested it too, and found it to be present as well in PK-Sim. Quite entertaining...

**Comment by msevestre** [comment]
Fixed in 7.3 with https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/commit/38d59a6cd791b9f1b8403b79347e475e632a42d9
