### ISSUE TITLE
No change in the building block status shown

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#220]
In the project attached the value of **fraction unbound (plasma, reference value)** was overwritten in the simulation, however in the simulations tree the status of used molecules building block is shown as unchanged.

[OLD_Cefuroxime_LatePregnancy.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1539218/OLD_Cefuroxime_LatePregnancy.zip)
<img width="721" alt="pic" src="https://user-images.githubusercontent.com/25061876/33717599-d8fe063a-db5a-11e7-90b1-1548364323c3.png">

**Comment by msevestre** [comment]
What about the PSV?

**Comment by PavelBal** [comment]
@Yuri05 closing because I assume now the changes are handled differently... re-open if you think this is still an issue.
