### ISSUE TITLE
Feature: Show project file name in the title bar

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#221]
Showing the name of the opened file in the title bar would help to navigate when multiple projects are open.

**Comment by Yuri05** [comment]
Project file name is shown in the status bar. Think that's enough?

**Comment by PavelBal** [comment]
Having the name (we don't need the full path) would allow to quickly select the "right" MoBi instance from the task bar. This is supported by many other applications and is extremely convenient.

Here an example for PowerPoint - I know which instance to select because file name is shown in the title:

![image](https://user-images.githubusercontent.com/25903040/201923792-6ddd15b8-5761-4f24-8f7d-05b8a77e91de.png)

The same for MoBi:

![image](https://user-images.githubusercontent.com/25903040/201923853-6e60b1a6-9ebe-4607-b468-b56e49df9b5e.png)

**Comment by PavelBal** [comment]
Hah, this is awesome!!

**Comment by msevestre** [comment]
I have a bunch of undefined now I the title when the project is not saved.  Is this on purpose ?

**Comment by peterdew** [comment]
Yes, the name is not yet defined then. As a developer it feels a bit off though maybe, since it means an unhandled situation sometimes. If it needs some tweak here, let me know.

**Comment by msevestre** [comment]
I think it should not say anything. It really feels weird IMO. I didn’t specify this behaviour so I don’t know if this was intented

**Comment by PavelBal** [comment]
> I have a bunch of undefined now I the title when the project is not saved. Is this on purpose ?

How does it look like? I don't have any "undefined":

![image](https://github.com/user-attachments/assets/f43034ad-c06d-4e11-83ef-0e6236c62527)

**Comment by msevestre** [comment]
send a simulation from PK-Sim to MoBi => undefined

**Comment by PavelBal** [comment]
![image](https://github.com/user-attachments/assets/f9f7ad89-4604-43d5-b287-a4daa1d50026)

Not a big deal I would say.
