### ISSUE TITLE
Add Debounce effect when entering formula in MoBi

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#237]
Right now, updating / editing a formula string is very painful because the validation is called on EACH keystroke. Instead a debounce mechanism should be implemented (500 ms, 1s or something similar) to start validation ONCE the user stopped typing for the above mentioned amount of time. This would make the UI much snappier and the editing experience overall better

**Comment by Yuri05** [comment]
@msevestre this can be closed now (done in 7.5)?

**Comment by msevestre** [comment]
Yep. This was implemented
