### ISSUE TITLE
PI: Allow copying values from the results tab. 

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#24]
Results are shown in a table, which cells are not active (cannot select and copy the value). Being able to copy values is a must.
<img width="562" alt="aufnahme2" src="https://cloud.githubusercontent.com/assets/25061876/23745035/05ee9ed2-04b7-11e7-82cf-16cebedb083d.png">

**Comment by msevestre** [comment]
This is not fixed. It is not possible to copy a value with multiple optimization result
