### ISSUE TITLE
Load Observed Data from PKML: Molecular Weight unit/conversion error

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#241]
Transfer of observed data from PK-Sim to MoBi can be done by saving it as a PKML file in PK-Sim, then loading it into MoBi. In this process, the metadata of the compound is transferred as well. However, the molecular weight is not properly converted and thus 9 orders of magnitude too low. This appears to be a missing conversion factor to convert from kg/µmol, the internally used unit, to g/mol.

This becomes a problem whenever the model results are displayed in molar concentrations. Observed data are wrongly recalculated.

As current workaround, the molecular weight has to be manually overridden.

To reproduce:
1. Open the example project "Paracetamol" in PK-Sim, select the data set "Albert 325mg capsule". 
2. Right-click on it and select "Export to PKML" from the context menu. 
The exported file is already attached to this issue.
3. Open MoBi, create a new project.
4. Right-click on "Observed Data", select "Load observed data" from the context menu. Select the file created above or extracted from the attached ZIP file.
5. Open the newly imported data for edit by double-clicking on it. The molecular weight in the upper left shows 1.512E-7 g/mol in MoBi, while the value seen in PK-Sim is 151.160 g/mol. 

[Albert 325mg capsule.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1727670/Albert.325mg.capsule.zip)

**Comment by msevestre** [comment]
@UlrichSi Does it happen with newly imported observed data?

**Comment by UlrichSi** [comment]
Yes, it happened with my current project data as well. 

What I tested in the meantime is importing a PKML observed data file that was generated from MoBi. There the issue does not seem to be present. You can try it by exporting the sample data (after manually correcting the molecular weight) and re-importing it.

**Comment by msevestre** [comment]
I know we had an issue with unit in an older version. The code however in PKSim uses the correct unit [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/1cf59d1afd67b1b04a6f0b21994842de002f8d03/src/PKSim.Core/Services/ParameterChangeUpdater.cs)

So it might really just be because the obs data was too old. I am going to try it out with a brand new import and see what's going on

**Comment by msevestre** [comment]
Please ask your questions in the forum (and only here)
https://github.com/Open-Systems-Pharmacology/Forum/discussions
