### ISSUE TITLE
proposal for change of value description and value origin in Simulation view

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/MoBi#242]
As discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/234#issuecomment-322488101
![grafik](https://user-images.githubusercontent.com/25585248/36297715-9e90c2f4-12f4-11e8-8783-03ce3e9b26b3.png)
@msevestre hope this is the right place ;-)

**Comment by msevestre** [comment]
@tobiasK2001 thanks

**Comment by msevestre** [comment]
* Description and Value Origin are two different concepts. cannot replace one by the other
* Hide description: Yes. It will be available as extra column
* Rest is done already
