### ISSUE TITLE
Edit PK-Sim Model: Access amount in container/compartment

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/MoBi#246]
Hello,

I am trying to edit a PK-Sim simulation for an IV drug. I am trying to update the model in mobi to add intranasal (simple first order) absorption. I created new container in spatial structure and connected it to venous plasma. Now, I am in Event block trying to add ODE for first order process. What would be the parameter for a drug amount in nasal absorption compartment at a given time? Do I have to create it in spatial structure? I am trying to define drug transfer from nasal absorption container to venous plasma by dN/dt = Amt*Ka. Now, I am not sure how to let Mobi know that Amt changes are dependent on an ODE formula for nasal absorption compartment, i.e. dNasal/dt = - Nasal*Ka - Nasal*Kloss?

I can share PKML file for event building block; however, am not sure how to attach here. Thanks for your help in advance.

Kind regards,
Krina

PS: Thanks for making PK-Sim and Mobi available as open source. It's a great help to the pharmacology community. :)

**Comment by PavelBal** [comment]
You can share the pkml by zipping it and attaching the zip. It will be probably easier to understand you problem and to find a solution if you could do that.

**Comment by krinaj** [comment]
Thanks, Pavel. Here is the attached building block for event that I am trying to create.

`
[Sim_2.5mg_Nasal_new.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/1782624/Sim_2.5mg_Nasal_new.zip)
`

**Comment by StephanSchaller** [comment]
HI,

Generating Applications in MoBi is not yet very user-friendly. It's easier this way:

Define your first-order process in PKSim (for any type of compartment). Export the Simulation to MoBi. Open the Events BuildingBlock and Save the Applikation you see as a PKML (right click --> save).

In the other model with the nasal structure, you now right-click on the white space in your Event BB and select "load" and choose the previously saved application pkml.

Now edit the Application by changing the properties of the application target compartment to your new nasal compartment (extend the application tree view and you will find somewhere an object "*yourcontainertype*_Transport". Click on it and in the properties on the right change the tags for target to the name of your nasal compartment.

**Comment by krinaj** [comment]
Thanks, Stephan. I am able to make changes as you suggested, the simulation runs; however, the simulation has no curve. It seems like dose need to be changed from skin (compartment that I selected from PK-Sim to do user defined dose) to nose. I tried reading manual and looking everywhere, but can't figure out how to give dose to nasal depot?

thanks,
Krina

**Comment by PavelBal** [comment]
There are some things:

1) First, remove the tag "PeripheralVenousBlood" from the container "NasalDepot". You can see the list of tag when you select the container in the Spatial Structures Building Block (BB).

2) Now, there are two processes you have to define - application of drug into the nasal compartment, and transfer from the nasal compartment into venous blood plasma.

3) The application itself is probably a bolus-like administration, i.e., the dose is delivered at once? In this case I would take "intravenous bolus" as a template for the nasal application and change the path of the changed molecule  accordingly (from venous blood to NasalDepot).

4) After step 3), you can administed a certain amount of the drug into nasal compartment. From your question I understand that there is a linear transfer to venous blood, and also linear degradation ("loss") in the nasal depot? Then create a reaction for the loss part, let's call it "NasalDegradation", with linear reaction rate, and restrict this reaction to the nasal depot only by selecting the "Container Criteria"-tab of the reaction, then right-click and select "New match tag condition", and enter "NasalDepot".

5) To allow the transfer of the drug from nasal depot into venous blood plasma, you have to create a passive transport process. Go to the BB "Passive transports", select "New", and create a new transport process as shown on the screenshots:

![nasal1](https://user-images.githubusercontent.com/25903040/37020671-e0e61bf0-211c-11e8-8d28-440233791b7a.PNG)

![nasal2](https://user-images.githubusercontent.com/25903040/37020712-18a8d546-211d-11e8-9154-c8a177ec0e04.PNG)

"k_transfer" is a parameter of the transport.

This way, your simulation should work. Good luck!

**Comment by krinaj** [comment]
This is great. Thanks so much, Pavel. This way simulation works now. Many thanks
