### ISSUE TITLE
Usability: PSV-BB, refresh start values - set default action to "Refresh selected from source"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#251]
By default, the action for the "Apply" button for refreshin start values from BB is "Refresh all". I think it is dangerous, as it destroys the whole BB if the user "accidentally" hits it. "Refresh selected" is safer, and also probably more used option.

**Comment by rwmcintosh** [comment]
No more refresh from source.

![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/261477/4fe6f793-7930-4b24-a99c-c41d78623363)
