### ISSUE TITLE
Chart editor - many data points and scrolling

### ISSUE THREAD

**Issue by Aedginto** [Open-Systems-Pharmacology/MoBi#268]
I have many experimental data points (n=100+). When trying to make them visible or not visible on the chart, if the row is not within the view box, if 'visible' is clicked, it scrolls back up to the top. Then I have to scroll down to find the next row that I want to have visible. Disabling the automatic scrolling would be very helpful.

**Comment by msevestre** [comment]
Will be done when is merged https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/417
