### ISSUE TITLE
Error when exporting Simulation with Solubility Table to Matlab differential equations

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#285]
7.3 Beta: The attached simulation will, when exported to Matlab differential equations, abort export and report the following error message:

MoBi

Table formulas with offset not supported by matlab export
FormulaId = 1035

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).
[SolubilityTable.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/2044415/SolubilityTable.zip)

**Comment by UlrichSi** [comment]
Possibly, the MoBi build is not up to date. PK-Sim: 7.3.0.29 Beta; MoBi: 7.3.0.23 Beta.

**Comment by Yuri05** [comment]
should be fixed with https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/issues/48
