### ISSUE TITLE
"User defined" in Reactions-BB?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#293]
First of all - the "User defined"-section for parameters changed in simulation is great, thank you!

But I do not understand what is the purpose of the "User defined"-tab in the Reactions-BB?

![image](https://user-images.githubusercontent.com/25903040/41398933-421745d0-6fb9-11e8-970b-33f9c2c1a582.png)

If it is by design - why is it missing in other BBs?

**Comment by UlrichSi** [comment]
From my understanding, this is supposed to be an automatically created list of parameters that you added in MoBi (or already in PK-Sim, if you started there). Try it with a newly created model, or for the Reactions, try adding a new parameter to your existing older model. Remember to fill out the "Value origin" field. And force a screen refresh by clicking to another tab and then back to "User Defined".

For the other BBs, it seems to work only for newly created models.

The **real** (minor cosmetic) **bug** seems to me that the header of the "User Defined" tab starts with the column "Simulation", **which disappears** as soon as the table is filled.

**Comment by PavelBal** [comment]
OK, makes sense. In this case - I want to have the same for the other BBs :)

**Comment by UlrichSi** [comment]
See my additions above. It might be that "Passive Transports" is lacking it.

**Comment by msevestre** [comment]
@UlrichSi Sorry not sure what you are asking me. What details?

**Comment by UlrichSi** [comment]
We were wondering why some BBs do not have a "User defined" tab or tree entry. Like "Passive Transport" or MSV, PSV.

**Comment by PavelBal** [comment]
> Sorry not sure what you are asking me. What details?

Well, the initial question is - what is the tab "User defined" in the reactions-BB for? And why other BBs do not have it (at least, not always)?

**Comment by msevestre** [comment]
I guess the original questions was answered already. 

The concept of User Defined only apply for parameters. Because we already have another competing concept in MSV and PSV with "Show only value changed by user" or sthg similar, and because MSV and PSV are not parameters, this is not available there

This is also not available for Settings as well.

As far as PassiveTransport is concerned, good question. Probably an oversight during the specification (at the beginning it was only supposed to be defined for SpatialStructure and Simulation)

**Comment by UlrichSi** [comment]
So, summarizing: the remaining issues are
- obsolete column "Simulation" in case of empty "User defined" window
- lack of window refreshing after new parameter has been added
- check for possibly missing "User defined" tab or tree entry in "Passive Transports"

**Comment by PavelBal** [comment]
>Because we already have another competing concept in MSV and PSV with "Show only value changed by user" or sthg similar

Unfortunately, no! The option shows all values which are different from the original BB-values, i.e., all the thousands (exaggerating, yes) of "Relative expression...)! But I see the point that PSV and MSV-BBs have no "User defined".
