### ISSUE TITLE
Events: Change RHS of state variable parameters

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#306]
It is possible to change the value of a state variable parameter, but not its RHS. It would be great to have this option.

**Comment by Yuri05** [comment]
RHS of a state variable is usually combined out of multiple processes (passive transports, active transports, reactions, ...). 
Is that really the case that you would like to change the whole RHS? Or just the transport/reaction rate of 1 or more processes involved?
In the latter case: you could force creation of the **ProcessRate**-parameter for transport/reaction and change this parameter in a event.

**Comment by PavelBal** [comment]
I am talking about Parameters that have the "Parameter is state variable"-checkbox activated, and a user-defined RHS-formula. So there are no transports etc (e.g., the parameter "Lumen|Stomach|Liquid").

**Comment by Yuri05** [comment]
Ok, I see. 

One possible solution could be: allow user to automatically add a corresponding RHS parameter in a simulation (similiar to _ProcessRate_ parameter for transports/reactions) and change this parameter in event.

And this would be also a workaround for now: just define such an RHS parameter manually in the parent Building block and set RHS formula to this parameter. After that, change RHS parameter in your event
<img alt="aufnahme36" src="https://user-images.githubusercontent.com/25061876/42584580-08e91746-8523-11e8-9012-d2d8de9ccf63.png">

**Comment by Yuri05** [comment]
workaround provided
