### ISSUE TITLE
Comma as decimal separator - inconsisten behavior.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#319]
In german localization, comma is the default decimal separator. It is accepted in some, but not in all, input fields in MoBi (and PK-Sim, too, see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/902).

Where it **does not** work (i.e., 1,5 is interpreted as 15):
-Axis min/max values in chart editor (simulation, PI)
-Observed data editor
-PI: weight of observed data points

**Comment by UlrichSi** [comment]
Still one special case remains open: 
1. Edit observed data
2. Create a list with the time points 1, 2, and 5 hours or use attached file.
3. Try to change the time value "1" to "0,5"
An error is displayed that a time point "5 hours" is already existing.

[Testdata0-2-5.xlsx](https://github.com/Open-Systems-Pharmacology/MoBi/files/2581075/Testdata0-2-5.xlsx)

**Comment by msevestre** [comment]
Yes this is another behavior that was not part of the original issue unfortunately. BaseGrid treatment is somewhat different here
