### ISSUE TITLE
"Load" and "Load from template" - duplicate functions?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#339]
For some model parts, e.g., molecules, there exist options to "Load..." and "Load from template...". Both allow to select a PKML. Are there some differences between the functions, or should one of the be removed?

**Comment by Yuri05** [comment]
The only difference is: 
- _Load_ remembers the last used folder and starts in it next time it's called.
- _Load from template_ always starts in the predefined templates folder

**Comment by PavelBal** [comment]
From my point of view, "Load" is sufficient and removing "Load from template" would make the context menu slimmer.

**Comment by Yuri05** [comment]
"Load from template" was added after "Load" due to requirement from some users.

**Comment by msevestre** [comment]
Those users :)
