### ISSUE TITLE
Feature wish: add "Ctrl+F" for "Find"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#340]
It would be great to have the "Search"-option by pressing the "Ctrl+F" shortcut.

**Comment by msevestre** [comment]
what about you try "CTRL + SHIFT +F"
https://github.com/Open-Systems-Pharmacology/MoBi/blob/5ebd610e1dddd1eb57bed7a37d7128f2b27bc84e/src/MoBi.Presentation/Repositories/MenuBarItemRepository.cs#L145

**Comment by PavelBal** [comment]
OK, better as nothing :)

**Comment by msevestre** [comment]
CTRL+F is used as default shortcut to find element in Table that's why we had to settle for something else

**Comment by PavelBal** [comment]
OK, you can reject the issue then.
