### ISSUE TITLE
Predicted vs. Observed plots for MoBi

### ISSUE THREAD

**Issue by fweysser** [Open-Systems-Pharmacology/MoBi#350]
Predicted vs. Observed plots for MoBi like the ones available in the parameter identification.

**Comment by Yuri05** [comment]
I guess not only for MoBi but also for PK-Sim?

**Comment by StephanSchaller** [comment]
@fweysser , good to see you are actively working with OSPS ;-)

**Comment by Yuri05** [comment]
implemented in 11.1
