### ISSUE TITLE
Add InContainer descriptor criteria

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#366]
required when https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/534 is implemented

**Comment by msevestre** [comment]
FYI @UlrichSi @AndreDlm @Yuri05

**Comment by msevestre** [comment]
@UlrichSi @AndreDlm @Yuri05 @PavelBal @StephanSchaller

Here we go:)

![image](https://user-images.githubusercontent.com/1041237/56070671-312bc200-5d57-11e9-9698-33c939034921.png)


It's now possible to define "In Container" condition as criteria for a Formula

I am assuming it does not make much sense for a Container Criteria (such as Transporter etc..)
Potentially it could make sense for Observer (where should the observer be defined?)

I am going to allow it everywhere now and would like some input as to WHERE it does not make sense:)

**Comment by PavelBal** [comment]
Cool! Will have to work with it a bit to see where it makes most sense.

**Comment by msevestre** [comment]
Actually it's even going to be better.
We will have InContainer and NotInContainer conditions which will look at all the tags in the hierarchy of the element (an not only its direct pare not)

**Comment by StephanSchaller** [comment]
Would this be useful to replace the sum formulas used in the EndogeneousIgG Organ?

**Comment by msevestre** [comment]
I don't know about that very specific use case.

In my opinion, the power of this feature will be especially useful with `SumFormula` which will allow you to perform model wide operations that scale when an organ or compartment is added or removed

**Comment by UlrichSi** [comment]
Great that this venerable feature wish is progressing!

I would like to use the feature in a local parameter formula in connection with a sum formula, in combination with the tag match condition. However, I agree that container observers might also be a field to apply it to.
