### ISSUE TITLE
Create Simulation. It is possible to change MSV and PSV Values during simulation process

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#371]
@UlrichSi @PavelBal @StephanSchaller 

Does anyone actually uses this feature?

IT makes the code very hard to reason about because we are trying to merge PSV and MSV all the time and I feel that this is very, very overkill

I would vote to remove that completely from the code

![image](https://user-images.githubusercontent.com/1041237/56287847-6df71080-60eb-11e9-9c3e-ddce880d450e.png)

**Comment by UlrichSi** [comment]
Not me. I am using the start value editor in the BB explorer.

**Comment by PavelBal** [comment]
Nah, I don't think this one is necessary.

**Comment by msevestre** [comment]
Also as a side note, it also changes the building block used by extending what's not there
Some saw it as a feature, but I think it's a bug in my opinion..
THe user should be responsibile for his/her building block. Having the tool mess around with them all the time is not transparent

![image](https://user-images.githubusercontent.com/1041237/56312120-83852e00-611d-11e9-9843-a1bb880f1b1f.png)

Adding PSV all the time makes it impossible to have only the list of changed parameter in PSV for example. In my opinion this behavior should be removed also

The same goes with MSV. if a molecule was not present, then it's not present. Easy enough to extend the building block or create a new one

**Comment by UlrichSi** [comment]
I faintly remember that was one of the original intentions for having this feature: To create/update missing or incomplete start values via the simulation wizard without having to go back to the BB editor mode. Don't think of it as a bug!

**Comment by TWendl** [comment]
I am using it and I would vote for keeping this feature!

**Comment by StephanSchaller** [comment]
I am not using it (but also never have).

**Comment by msevestre** [comment]
@TWendl Are you using the "edit feature" of this view? E.g. changing value on the fly while constructing a simulation?

Could you explain the use case?

It creates a lot of weird code in MoBi because it breaks the concept of building blocks. As soon as the simulation is created, for example, it is already in "RED" state (e.g. building block have been modified). T

**Comment by Yuri05** [comment]
Obsolete in V12 and can be closed?
