### ISSUE TITLE
Export from MoBi into population simulation with dimensionless parameter state variable 

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/MoBi#379]
Hello all,

Please ignore my posting in the Forum, I think this is the wrong location.

I am having an issue when exporting a MoBi file into the population simulator.

I needed to introduce a dimensionless parameter state variable (fraction) but the export to the population simulator seem not to allow such step. Is there a solution to this problem or can I work around it?

The message: Could not load simulation from ...
Dimension dimensionless per time not available in DimensionFactory.

![Picture1](https://user-images.githubusercontent.com/33650076/57076633-69854700-6cea-11e9-825d-b24915d8363b.png)

Thank you.

Best regards,

Rudiger

**Comment by msevestre** [comment]
@RKasp This seems to be a bug in MoBi. It is creating a dimension `Dimensionless per time` instead of using the one already available `Inversed time`

>I needed to introduce a dimensionless parameter state variable (fraction) 

Can you set the dimension to `fraction` instead and see if this work?

**Comment by RKasp** [comment]
I just tried, same error message...
Now it says:
'Dimension fraction per time not available in DimensionFactory.'

**Comment by msevestre** [comment]
hum ok. 
WE are going to give it a look

In the meantime, here is a workaround
* goback to your dimensionless parameter
* Then SAVE the simulation as pkml file (instead of exporting it direclty) for population
* Open the pkml file with a text editor (notepad ++ for example)
* Search for Dimensionless per time
* Replace with Inversed time
* Go to pksim and select 
![image](https://user-images.githubusercontent.com/1041237/57081950-c02b5a80-6cc3-11e9-9d4b-e0e461706812.png)


This should be equivalent

**Comment by msevestre** [comment]
@PavelBal
https://github.com/Open-Systems-Pharmacology/Forum/issues/318#issuecomment-489040899

Can you add your workaround here? Hopefully it's easier than mine :)

**Comment by RKasp** [comment]
thank you! Your approach works.

**Comment by PavelBal** [comment]
My workaround (if still needed):

1) Open the file "C:\ProgramData\Open Systems Pharmacology\PK-Sim\7.4\OSPSuite.Dimensions.xml" with a text editor
2) Add the block 
  	<Dimension name="Dimensionless per time" baseUnit="/min">
      <BaseRepresentation lengthExponent="0" massExponent="0" timeExponent="-1" electricCurrentExponent="0" temperatureExponent="0" amountExponent="0" luminousIntensityExponent="0" />
      <Units>
        <Unit name="/min" factor="1" />
      </Units>
    </Dimension>
