### ISSUE TITLE
MoBi running with R using populations

### ISSUE THREAD

**Issue by RKasp** [Open-Systems-Pharmacology/MoBi#380]
Hi all,
I would like to run population simulations across a wider dose range including user defined intersubject variability. It seems the R package for MoBi does not cover the use of a population data set in a population simulation in R. It is possible to compute all parameter distributions needed in R using 'setParameter', but I am wondering if there is an easier way by importing an input file. Thank you for any ideas.
All the best,
Rudiger

**Comment by StephanSchaller** [comment]
Hi Rüdiger,

generate your Population in PK-Sim. Export as Spreadsheet (Excel) and then in R write a loop to set the parameters from the Spreadsheet for each individual.

It is very convenient and easy to do.

Hope this helps,
Stephan
