### ISSUE TITLE
Beta 7.5: Editing Sum formula box requires more than one mouse click to activate

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#382]
See title, happens when editing a formula. The cursor is blinking, but no keyboard entry is accepted.

**Comment by Yuri05** [comment]
happens to me as well...

**Comment by msevestre** [comment]
I can't reproduce. Does it happen all the time ? Are you on your computer or using a remote desktop session?

**Comment by Yuri05** [comment]
local computer, not always reproducible as well...

**Comment by msevestre** [comment]
closing. Please reopen if there is a way to reproduce
