### ISSUE TITLE
Increase project version

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#390]
s. https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/572#issuecomment-495645472

**Comment by msevestre** [comment]
@Yuri05 I am not sure about that. At the moment, MoBi uses OPSSuite.Core version (why, I do not know). That means that we also need to increase the OSPSuite.Core version and define for core and potentially for MoBi an empty conversion. Does it make sense? Probably not

**Comment by Yuri05** [comment]
OK, we should introduce MoBi version in the next release.
For now it's not that critical (the only Problem is getting an exception when trying to open MoBi 8 project with an older software version)
