### ISSUE TITLE
Solver Warnings empty

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#401]
This is how solver warnings look like in 8.0:

![image](https://user-images.githubusercontent.com/25903040/60025853-c70a9400-969a-11e9-9173-93b89148560e.png)

**Comment by msevestre** [comment]
@PavelBal Not very useful this window indeed :)

Can you attach a project creating warning so that we can reproduce ?

**Comment by PavelBal** [comment]
Unfortunately, I cannot attach the project I am working on now. If I will encouter the same error in a non-critical project, I will upload it.

**Comment by Yuri05** [comment]
Maybe there are just no warnings? ;)
