### ISSUE TITLE
Simulations comparison table: Strange output for "Quantity Type"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#416]
See screenshot - the listed differene in "Organism|MeanHeight" is "QuantityType", which is "0" in one simulation and "Parameter" in another. No idea what this means.

![image](https://user-images.githubusercontent.com/25903040/65585994-ad236a80-df83-11e9-8d22-6a765649924d.png)

**Comment by msevestre** [comment]
0 is undefined.... Was it created by hand?

**Comment by PavelBal** [comment]
> Was it created by hand?

No, but it is a rather old model... Pre- 7.0 era.

**Comment by PavelBal** [comment]
Old.
