### ISSUE TITLE
Simulations comparison table: wrong difference listed for distributed parameters

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#417]
The object "Organism|MeanBW" is defined by a distributed parameter in one simuulation, and is overwritten in the PSV with a fixed value for another simulation. The comparison states "Different types: Constant Formula vs Formula", which is wrong.

![image](https://user-images.githubusercontent.com/25903040/65586146-f2479c80-df83-11e9-8d6e-c06a3815aa4f.png)

**Comment by PavelBal** [comment]
BTW: What is a "constant formula" in this context?

**Comment by msevestre** [comment]
>The comparison states "Different types: Constant Formula vs Formula", which is wrong.

Why is this wrong? You say that you override the value with a PSV( constant value). 
I don't understand the problem

**Comment by PavelBal** [comment]
The difference is in the value of the parmeter - but the comparison says "Different types: Constant Formula vs Formula". In one case, it is a constant parameter (I did not find any other place in MoBI that uses "constant formula", in another, it is a distributed parameter.

**Comment by msevestre** [comment]
Every time you defined  a value as  a constant, it is a constant formula. MOST parameters are constant formula I'd say

in this case, the parameter have TWO different types of formula. This is the first check done in comparison

You can get the same behavior by overriding any Explicit formula with a constant

**Comment by PavelBal** [comment]
OK I just saw for the first time that the filed is called "Formula type:" 

![image](https://user-images.githubusercontent.com/25903040/65617928-c812d080-dfbd-11e9-9225-c141aea8f608.png)

Quite unintuitive from my perspective.  Especially in combination with the "isFormula" property in Matlab/R toolboxes ;)

**Comment by msevestre** [comment]
@PavelBal 
a parameter has a Formula. A formula has different types (constant, explicit formula, table, etc..) 
This has been like that since the first version of Mobi 3. 

whas `isFormula` does in Mobitoolbox works at a different level probably. It returns true if the parmaeter is not constnat

so probably it should be called isConstant as opposed to isFormula (which does nto make sense because a parameter IS NOT a formula. It should be called at least hasFormula)

**Comment by StephanSchaller** [comment]
Technically, "Formula type" may be called "Value tape" which could be constant or a formula. and the Parameter(value) could then have the property 'isConstant' or 'isFormula'

Question is if this needs to / should be changed?

**Comment by PavelBal** [comment]
Cannot reproduce.
