### ISSUE TITLE
Exception when trying to "Calculate Scale Divisor" for simulation that cannot be solved.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#439]
When trying to calculate scale divisor for a simulation that cannot be solved (e.g., because of the solver settings), and exception is thrown. Instead, a proper error message would be preferrable.

1) Open any model in MoBi (e.g., export the "Aciclivor"-example model from PK-Sim)
2) In "Simulation Settings -> Solver Settings", change `MxStep` to `9` (or any other value that leads to an error during simulation)
3) Click on "Calculate Scale Divisor" and select calculate.
4) An exception is thrown.

![image](https://user-images.githubusercontent.com/25903040/73738751-53a72580-4745-11ea-88ff-21064d0f4984.png)

**Comment by msevestre** [comment]
wow. Interesting. I see if I can swing it for 9.0.  (only if it's a trivial change)

**Comment by msevestre** [comment]
I could not reproduce the issue with 9.0. However the message was showing a OOPS window

**Comment by msevestre** [comment]
now
MoBi®

Error solving ODE at time t=3: The solver took 9 internal steps but could not reach output time (TOO_MUCH_WORK)

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/73890735-aca7b400-4840-11ea-914c-95eb3186deb2.png)
