### ISSUE TITLE
Do not expand molecules-BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#447]
Molecules-BB is the only BB that can be expandend:

![image](https://user-images.githubusercontent.com/25903040/74532989-d17ee400-4f30-11ea-83df-cd4ce1c456d6.png)

Actually, I do not see a reasong for this, so maybe remove this option?

**Comment by msevestre** [comment]
To see the list of molecules defined in the bb? why is this an issue?

**Comment by PavelBal** [comment]
Inconsistent behavier/duplicate feature?

If I edit this BB, I will **always** have the list of the molecules in the editor frame.

![image](https://user-images.githubusercontent.com/25903040/74649153-552e1000-517f-11ea-97a5-8fb5b3e42c2d.png)

At the same time, any other BB does not have this list (and, actually, it would be very convenient for the Reactions).

**Comment by Yuri05** [comment]
>At the same time, any other BB does not have this list (and, actually, it would be very convenient for the Reactions).

Exactly. So for me the question would be why other BBs do not support this? In any case I wouldn't remove the feature from  the molecules-BB

**Comment by PavelBal** [comment]
Well, I can also rename the issue to "Expand all BBs" ;)

**Comment by msevestre** [comment]
OK but what to expend under all other building blocks? 
I have no problem removing the expand in MoBi. But if it was added...probably someone wanted this. I agree that in your case, with so many molecules, expanding is not so good for the UX

**Comment by PavelBal** [comment]
> But if it was added...probably someone wanted this

I just wonder if anyone uses it. It looks a bit "lost" because it does not match the behavior of other BBs.

**Comment by Yuri05** [comment]
I do use it.

**Comment by PavelBal** [comment]
All right, than it can be left there :)

**Comment by PavelBal** [comment]
OK, than it can be left as is :)

**Comment by msevestre** [comment]
The more I think about it, the more I think we should remove it lol

**Comment by StephanSchaller** [comment]
May opinion: remove it. I never ever used it and I am basically working with MoBi all my life (very sad, LOL).

**Comment by msevestre** [comment]
I'd rather have you February opinion
