### ISSUE TITLE
Instances of molecules in parameter containers?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#448]
I see a very strange warning message:
![image](https://user-images.githubusercontent.com/25903040/74541949-eb292700-4f42-11ea-9c1d-917c1e0cdb3d.png)

"Obsever ... with path "Organism|Lumen|Stomach|**Gastric emptying time|Sitagliptin**|blabla"

Which looks like there is an instance of "Sitagliptin" under the parameter "Gastric emptying time"???

**Comment by Yuri05** [comment]
@PavelBal is this still the case in V12 or we can close the issue?

**Comment by PavelBal** [comment]
Cannot reproduce right now, closing.
