### ISSUE TITLE
Error trying to load Excel-files

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#451]
MoBi 9 Build 74

When trying to load observed data:

`Could not load file or assembly 'SX, Version=2.7.3.5, Culture=neutral, PublicKeyToken=882b9c044052e7f6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

When trying to import MSV from excel:

`Failed to import from <PathToFile>.xlsx. It may not be valid Excel file format`

**Comment by msevestre** [comment]
I think the script to update the SX.dll version does not work anymore (or the entry was removed from the app.config file after convestion)

**Comment by msevestre** [comment]
@PavelBal This should be fixed. Can you try to downlaod the latest version of MoBi portable and let me know if this is the casE?

**Comment by PavelBal** [comment]
@msevestre Yepp, works. Thanks!
