### ISSUE TITLE
Placing the cursor into the "Amount"-field overwrites the formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#452]
In the Simulation tree view, simply placing the curso into the field "Amount" of a molecule "overrides" the formula.

![image](https://user-images.githubusercontent.com/25903040/75243490-42908800-57ca-11ea-8ff4-75809af740ef.png)

Changin e.g. the expression value in the parameters-field has then no effect on the amount of the molecule.

**Comment by msevestre** [comment]
and the reset formula does not work. WTF
