### ISSUE TITLE
"Unable to parse expression" instead of more informative tooltip

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#453]
MoBi 9 Build 74: When the expression for any formula cannot be parsed, only the general tooltip is shown, and not the one with the information what is wrong.

**Comment by msevestre** [comment]
Can you paste an example so that I understand what you mean

@Yuri05 Probably issue with messaging in FuncParser?

**Comment by PavelBal** [comment]
MoBi 9:
 ![m9](https://user-images.githubusercontent.com/25903040/75268630-07a54900-57f8-11ea-89df-b11eb7085796.jpg)


 
MoBi 8:
 
![m8](https://user-images.githubusercontent.com/25903040/75268644-0bd16680-57f8-11ea-87b5-2c280129bc6f.jpg)
