### ISSUE TITLE
Disable "create" and "load" context menus in the simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#456]
When right-clicking on model entities in the simulation tree, entries like "load from pkml" or "Create..." are still present. Trying to do it results in an error. These entries should not be present in the simulation.

**Comment by StephanSchaller** [comment]
lol...I also reported this

**Comment by msevestre** [comment]
Cannot reproduce in v9. Please try with the portable version and let me know

**Comment by PavelBal** [comment]
![image](https://user-images.githubusercontent.com/25903040/77579197-35a2a980-6eda-11ea-9461-155358025327.png)

Still there

**Comment by msevestre** [comment]
verrueck.t Ich kann es bei mir nicht reproduzieren...

**Comment by PavelBal** [comment]
Einfach eine Simulation öffnen, Rechtsclick auf einem Organ? Strange.

**Comment by msevestre** [comment]
yep

**Comment by msevestre** [comment]
Has to be a difference between debug and compiled version...fun

**Comment by msevestre** [comment]
definitely some stuff going on here
![image](https://user-images.githubusercontent.com/1041237/77582861-7092e600-6eb6-11ea-80b4-de6c9a9e2e1e.png)

**Comment by msevestre** [comment]
ah ah you need to have at least one favorite in your simulation :)

**Comment by PavelBal** [comment]
Well, totally obvious!😂 Good catch, never would have thought about trying
that.

Michael Sevestre <notifications@github.com> schrieb am Mi., 25. März 2020,
21:38:

**Comment by msevestre** [comment]
I don;t understand why this is like this but at least I can reproduce. We'll fix asap

**Comment by msevestre** [comment]
ok fixed. Good find
