### ISSUE TITLE
Disable "Container Edit Functions" in MoBi Simulation

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/MoBi#457]
We can still do the same operations in the Simulation as in the Spatial Structure:
![image](https://user-images.githubusercontent.com/25477643/76883260-26897f00-687c-11ea-931b-4c046426a467.png)

But of course this will create an erroer (after reloading a saved organ):
![image](https://user-images.githubusercontent.com/25477643/76883297-399c4f00-687c-11ea-9c58-2da472447fd9.png)

**Comment by msevestre** [comment]
Is this new? What version?

**Comment by StephanSchaller** [comment]
V8 Build 21

**Comment by msevestre** [comment]
Hum I cannot reproduce in v9. CAn you please try the nightly build or portable version and let me know. (e.g. reopen )
