### ISSUE TITLE
Import of simulation parameters: Wrong dimension

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#459]
When importing simulation parameters from an Excel-file via right-clicik on the PSV-BB -> "Import...", entries with the unit "1/min" are imported as dimension "Becquerel".  Most of the time, it is "Inversed time".

A solution would be to specify an extra column "Dimension" in the import file.

**Comment by msevestre** [comment]
Bequerel and inveesedtime are the same dimension?? ( From a scientific point of view?)

**Comment by PavelBal** [comment]
From scientific point of view maybe, but in the model it is clearly wrong. I cannot even check what is the base unit of becquerel (because if it is not 1/min, then importing "1/min" will result in wrong calculations) because it is not listed in the [Appendix](https://docs.open-systems-pharmacology.org/appendix/appendix) :D

**Comment by msevestre** [comment]
This was a question. I didn't know they were equivalent.  But if they are, then the important should be consistent as BOTH base unit should be the same. I'll investigate

And please, the doc is open for everyone to update and change. Submit a PR  if something is outdated

**Comment by StephanSchaller** [comment]
> Bequerel and inveesedtime are the same dimension?? ( From a scientific point of view?)

Yes, Bequerel measures the clics per secon of a "Geiegr-Counter" for radioactive emissions... or sth. like this 
;-)

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/master/OSPSuite.Dimensions.xml#L691

vs

https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/master/OSPSuite.Dimensions.xml#L431

That should be completely equivalent

>I cannot even check what is the base unit of becquerel (because if it is not 1/min, then importing "1/min" will result in wrong calculations)

are you sure?

**Comment by msevestre** [comment]
The base unit is 1/min. It should be completely equivalent and if this is not, then there is a bug

**Comment by PavelBal** [comment]
OK, at least the values stay correct. Thanks.

Nevertheless, a separate column "Dimension" would be useful.

**Comment by msevestre** [comment]
@PavelBal Would it be enough for now to force InverseTime  in this circumstance?

**Comment by PavelBal** [comment]
Yes, this would be an acceptable workaround for now.

Maybe we could still think about a "Dimension"-column for same later version.

**Comment by msevestre** [comment]
I cannot reproduce the behavior
![image](https://user-images.githubusercontent.com/1041237/111217817-5ca33100-85ac-11eb-8d16-4a920b4fd58e.png)

At any rate, I will also add an optional column import
