### ISSUE TITLE
What's the meaning of Filllevelflag?

### ISSUE THREAD

**Issue by jzq90** [Open-Systems-Pharmacology/MoBi#464]
Hello, everyone,

Does somebody know the meaning of `Filllevelflag`? According to the code in the picture below, it seems when the `Liquid/Volume` is larger than 0.9, `Filllevelflag` will decrease. Then the drug transport in the lumen will decrease. 

`Filllevel = Liquid/Volume`
`Filllevelflag = (FillLevel<0.9?1:1/(1+exp((FillLevel-1)/0.01)))`
`dN/dt = (OralApplicationsEnabled AND IsFloatingInLumen) ? w*Drug*FillLevelFlagNext : 0`

![图片](https://user-images.githubusercontent.com/58142266/77885187-208e9780-7299-11ea-80c4-6bba78d5f733.png)
![图片](https://user-images.githubusercontent.com/58142266/77885231-3e5bfc80-7299-11ea-96c3-019643c5a0a1.png)

For example,
When `Liquid/Volume` = 1, it will be 50% of normal transport.
When `Liquid/Volume` = 1.01, it will be almost no transport.

How to illustrate this?

**Comment by PavelBal** [comment]
`Filllevelflag` prevents the contents of segment `A` from being transported into segment `B`, if the latter is full. `Liquid/Volume = 1` means that the whole volume of the segment is already full.

**Comment by jzq90** [comment]
> 
> 
> `Filllevelflag` prevents the contents of segment `A` from being transported into segment `B`, if the latter is full. `Liquid/Volume = 1` means that the whole volume of the segment is already full.

Thanks. I overlooked the `TARGET` before `Filllevelflag`.
