### ISSUE TITLE
Bug: Import of excel broken again.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#465]
MoBi 9 Build 107: When trying to load observed data from excel file:

`Could not load file or assembly 'SX, Version=2.7.4.1, Culture=neutral, PublicKeyToken=882b9c044052e7f6' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**Comment by msevestre** [comment]
ok thanks. I need to remember to do two things instead of one now when updating to a new version of SX.dll
Luckily this won't be necessary much longer once we get rid of this F#$%^#$%^#$% component

**Comment by msevestre** [comment]
ok taking care of that bad boy
