### ISSUE TITLE
 "sort dimensions" alphabetically

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#467]
MoBi 9 Build 115.

The list of parameter dimensions is incomplete, e.g., almost al "inversed xxx" are missing.

![image](https://user-images.githubusercontent.com/25903040/80081217-f1dfa600-8552-11ea-8e9a-541ac3b344a2.png)

**Comment by msevestre** [comment]
Weird.. there was a bug in MoBi creating all sorts of inversed xxx dimensions automatically. How many do we have usually defined by default?

**Comment by PavelBal** [comment]
If the parameter already has the dimention e.g. "Inversed time", than the drop-down menu shows the other options:
![image](https://user-images.githubusercontent.com/25903040/80107923-008e8300-857c-11ea-9ee7-6ff00da77a45.png)

**Comment by msevestre** [comment]
hum. There are 5 invesed time dimension in the repo and they should all be there. Any other will be added dynamically when adding a RHS parameter

**Comment by msevestre** [comment]
@PavelBal I can't reproduce. Can you scroll down? I think the dimensions are just not sorted anymore

**Comment by msevestre** [comment]
going to suggest to rename the issue to "sort dimensions" alphabetically/ Do you agree?

**Comment by msevestre** [comment]
@Yuri05 Could be the problem with the observed data stuff not working anymore in MoBi. I am going to make sure the stuff is sorted and we can go from there

**Comment by PavelBal** [comment]
Oh yes, somehow the "Inversed concentration" appears after "Concentration", and not after the letter "H". SO the other dimensions are there, but "Inversed concentration" is sorted wrong.

> going to suggest to rename the issue to "sort dimensions" alphabetically/ Do you agree?

Yes
