### ISSUE TITLE
Crash when selecting UI elements

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#469]
This has been like this for a long time, but is veeery anoying.

After some time working with MoBi, the app crashes when selecting an element of UI, like any entry in the list. Easiest way to reproduce - open any project, go to the "Formula"-tab of the spatial structure, and randomly select the formulas. It will take a while, but at some point it will crash.

**Comment by msevestre** [comment]
>It will take a while, but at some point it will crash

Does not seem like an easy way to reproduce to me :)

Can you observed the memory usage. Does it go high? Can you reproduce say with a simple easy project or does it need to be a big projec.t. or a very big project ?

**Comment by PavelBal** [comment]
> Does not seem like an easy way to reproduce to me :)

Time consuming, yes, but also easy ;)

It is not directly related to memory consumption, or the size of the project, but to the number of "clicks" on list elements. I had a project that consumed 30 GB RAM and continued running. This really only happens when you click around too often - for example, going through all the parameters of a spatial structure, or Copy-pasting a lot in the Events-BB (because there the whole list collapses every time a new parameter or entry are copy-pasted, so you have to expand the whole tree again and again -> many clicks).

It seems like there is a leak somewhere in the UI, so updating the view after selecting a new entry crashes at some point. This does not happen e.g. when just selecting the entries of PSV-lists, because nothing is updated there upon select.

There is no better way to describe how to reproduce the crash. However, there is also no way to avoid it - I just made it a habbit so save a lot when I am editing parameters or browsing through formula lists.

**Comment by msevestre** [comment]
>I just made it a habit so save a lot when I am editing parameters or browsing through formula lists

Not good.  I think the constant refresh is probably an issue indeed. That there is absolutely no error but a silent crash is very surprising.

**Comment by PavelBal** [comment]
Yepp, just silent death.

**Comment by StephanSchaller** [comment]
> Yepp, just silent death.

FYI this also happens in PK-Sim if you have a large project. Most of the time when working with (i.e. opening) PIs. Is this silent crash behaviour reported as a bug in PKSim?

**Comment by msevestre** [comment]
I have never seen in PKSim and I have used projects with many, many simulations (>50) and PIs. 
We'll need  steps to reproduce otherwise we won't be able to understand, nevermind fix it

**Comment by Yuri05** [comment]
@StephanSchaller @PavelBal If something like this happens in PK-Sim or MoBi, go to Windows Error Reporting and search for application errors (app name might be either PK-Sim/MoBi or .NET Runtime or both)

**Comment by StephanSchaller** [comment]
> We'll need steps to reproduce otherwise we won't be able to understand, nevermind fix it

I am aware of that. I was just checking if this has been reported. There is no particular pattern of how to reproduce this. Also no project I can share.
@Yuri05 , I will check Windows Error Reporting the next time it happens...

**Comment by PavelBal** [comment]
Error reports (sorry only in German):

```
Anwendung: MoBi.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.ComponentModel.Win32Exception
   bei System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   bei System.Windows.Forms.Control.CreateHandle()
   bei System.Windows.Forms.Control.get_Handle()
   bei System.Windows.Forms.Control.get_WindowText()
   bei System.Windows.Forms.Control.set_CacheTextInternal(Boolean)
   bei System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)
   bei System.Windows.Forms.Control+ControlCollection.Remove(System.Windows.Forms.Control)
   bei System.Windows.Forms.Control.Dispose(Boolean)
   bei OSPSuite.UI.Controls.UxTreeList.Dispose(Boolean)
   bei OSPSuite.UI.Controls.UxTreeView.Dispose(Boolean)
   bei System.ComponentModel.Component.Dispose()
   bei MoBi.UI.Views.SelectReferenceView.Dispose(Boolean)
   bei System.ComponentModel.Component.Finalize()

```

and 

```
Name der fehlerhaften Anwendung: MoBi.exe, Version: 9.0.109.0, Zeitstempel: 0xf84803e9
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.18362.815, Zeitstempel: 0xb89efff3
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003a799
ID des fehlerhaften Prozesses: 0x3760
Startzeit der fehlerhaften Anwendung: 0x01d61e16dbb40dbb
Pfad der fehlerhaften Anwendung: C:\Program Files\Open Systems Pharmacology\MoBi 9.0.109\MoBi.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: 8cfcef88-3c33-4de3-876f-2d20e683595f
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

and 

```
Fehlerbucket 1536369175813864017, Typ 5
Ereignisname: CLR20r3
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: MoBi.exe
P2: 9.0.109.0
P3: f84803e9
P4: System.Windows.Forms
P5: 4.8.4150.0
P6: 5e176e69
P7: 2df1
P8: 0
P9: System.ComponentModel.Win32
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER66DE.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER720A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER721B.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7219.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7248.tmp.txt

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_MoBi.exe_df936cd59cbdf97c31fed4b6d71a1ed772abd_f268c892_c16e9337-6542-49d3-b524-0371800961d2

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 8cfcef88-3c33-4de3-876f-2d20e683595f
Berichtstatus: 268435456
Bucket mit Hash: ae1327b3fc1669d6655247a0183eba51
CAB-Datei-Guid: 0
```

**Comment by msevestre** [comment]
Well that's very useful

Especially here
```
Ausnahmeinformationen: System.ComponentModel.Win32Exception

   bei System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)

   bei System.Windows.Forms.Control.CreateHandle()

   bei System.Windows.Forms.Control.get_Handle()

   bei System.Windows.Forms.Control.get_WindowText()

   bei System.Windows.Forms.Control.set_CacheTextInternal(Boolean)

   bei System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.LayoutEventArgs)

   bei System.Windows.Forms.Control+ControlCollection.Remove(System.Windows.Forms.Control)

   bei System.Windows.Forms.Control.Dispose(Boolean)

   bei OSPSuite.UI.Controls.UxTreeList.Dispose(Boolean)

   bei OSPSuite.UI.Controls.UxTreeView.Dispose(Boolean)

   bei System.ComponentModel.Component.Dispose()

   bei MoBi.UI.Views.SelectReferenceView.Dispose(Boolean)

   bei System.ComponentModel.Component.Finalize()
```


If we can get the same for PKSim, this would be great. Again, we cannot fix it if we don't know where to look. I know that you know @StephanSchaller , but sometime, it's good to repeat stuff

**Comment by Yuri05** [comment]
`Control.Dispose()` calls `CreateHandle()`  interesting...
@PavelBal @StephanSchaller Try [this](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/862#issuecomment-466048852)

**Comment by StephanSchaller** [comment]
> but sometime, it's good to repeat stuff

I know ;-)

@Yuri05, I will first try to "induce" the silent crash and report before trying the fix.

**Comment by msevestre** [comment]
Good idea @StephanSchaller 
@Yuri05 it looks like some stuff is not released properly. At least we can try to reduce the creation of such stuff all the time to make the UI a bit more responsive

**Comment by PavelBal** [comment]
@msevestre @Yuri05 Anything you think could/should be done? Otherwise let's close the issue for now.

**Comment by Yuri05** [comment]
Let's close. This kind of crash cannot be prevented programmatically.
Due to the many optimizations that have been made in charts etc., it should not happen too often.

**Comment by rwmcintosh** [comment]
This might already be addressed. Some comments here relate to PI's and we made a very helpful change in PI's to reduce the chances of this happening. It applies to both PK-Sim and MoBi.
