### ISSUE TITLE
Feature: Warning if processes are defined in Liver Pericentral for Zonation = 0

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/MoBi#473]
Of course, modelers should be aware of this, but maybe we can catch this case with a warning?

**Comment by Yuri05** [comment]
what do you mean by "if processes are defined in Liver Pericentral"?

**Comment by StephanSchaller** [comment]
If someone defines a reaction with e.g. zero order synthesis rate with container criteria "Liver" and "intracellular", this reaction also produces compound (amount only, concentration is zero) in the pericentral compartment even though volume = 0.

**Comment by Yuri05** [comment]
>If someone defines a reaction with e.g. zero order synthesis rate with container criteria "Liver" and "intracellular", this reaction also produces compound

Without liver zonation amounts of all molecules in the pericentral zone are zero per construction.
Thus any properly defined reaction should also produce only zero amounts of any product.

I would not create any warning

**Comment by StephanSchaller** [comment]
> ...zero amounts of any product.

Are you sure, because in our case it did (amount not equal zero), but concentration was zero.
What is a not properly defined reaction? ;-)

**Comment by PavelBal** [comment]
Yes, the reaction will be defined and will produce molecules... The concentration is 0, though.

**Comment by Yuri05** [comment]
Concentration in zero-volume compartments is always zero per construction.
If the synthesis reaction is defined as "molecule X is created out of nothing and synthesis rate is not dependent on the concentration of X": well, in this case amount of X could be nonzero in liver pericentral indeed. which will not influence other parts of the system.

**Comment by StephanSchaller** [comment]
> which will not influence other parts of the system.

Only if no amount-based processes are defined (accidently) that use pericentral amounts ;-)

Well nothing too critical, but maybe we should also inhibit creation of reactions in containers if volume if zero?

**Comment by msevestre** [comment]
Lots of accidents here..  maybe this is a pebkac problem

**Comment by msevestre** [comment]
In MoBi, one can have two livers and no brain. All fine

As an FYI
Reactions are created before PSV are applied. So volume may be zero when the reaction is created and non zero after PSV

If we want to show such a warning, we would have to go another traversal of the model to check for those inconsistencies. This could be optional

In that case: what other types of rules would be helpful to handle?
E.g warning when reaction is defined in a volume 0 compartment
Warning when....

Also we need to make sure there are no more warnings when exporting from PKSim. This makes the warning window useless in my opinion

**Comment by StephanSchaller** [comment]
Yes, pebkac, I agree to some extent, but if the user is not specific enough with the container criteria tags for reactions in liver, this may be enough to cause this... 

Good point with the PSV.

> In that case: what other types of rules would be helpful to handle?
E.g warning when reaction is defined in a volume 0 compartment

Can't think of anything else on the spot

> Also we need to make sure there are no more warnings when exporting from PKSim. This makes the warning window useless in my opinion

I agree

**Comment by PavelBal** [comment]
>In MoBi, one can have two livers and no brain

Sometimes I wish I had that....
