### ISSUE TITLE
Parameters cannot be referenced in B/P partition coefficient

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/MoBi#481]
Hi, this is a bug report concerning the issue described here

https://github.com/Open-Systems-Pharmacology/Forum/issues/526#issue-617446527

In the B/P partition coefficient I tried to reference a parameter but it was not possible. The bug was reproduced by @Yuri05.

Donato

**Comment by msevestre** [comment]
ok it is already defined as #507 which will be solved in v10 closing this one
