### ISSUE TITLE
Manual input for event assignment path

### ISSUE THREAD

**Issue by moPellowe** [Open-Systems-Pharmacology/MoBi#485]
Currently, the only way to change an event assignment's entity path to use the keyword "MOLECULE" (as in the particle dissolution model, shown below) is by manually editing the pkml file. Perhaps, it would be more user-friendly to allow for manual input of the entity path?

![Capture](https://user-images.githubusercontent.com/57540473/84304272-400e3000-ab26-11ea-99d8-e9a83ac32c4f.PNG)

**Comment by PavelBal** [comment]
> Are you saying you cannot enter a path by typing in something? In that case, this is a bug
 
A known one ;)
https://github.com/Open-Systems-Pharmacology/MoBi/issues/164

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/111003567-641ccd00-8355-11eb-847a-db086dd48d0d.png)

Done
