### ISSUE TITLE
Suggestion: Display of actual formula name instead of formula

### ISSUE THREAD

**Issue by moPellowe** [Open-Systems-Pharmacology/MoBi#486]
There are two places in the Event building blocks where the formula itself is displayed instead of the formula name: 1) in the application molecule builder and 2) in event assignments. 
This can make it difficult to track down the formula under the Formulas tab. Also, one cannot distinguish between formulas with the same equation but different references (e.g. ParticleBinDissolvedDrugMassBinDecrease formulas in the particle dissolution model). I would think that displaying the formula name would be more consistent with how other formulas are handled and avoid these issues.

![InkedCapture2_LI](https://user-images.githubusercontent.com/57540473/84305968-da6f7300-ab28-11ea-978d-26f34d2a4f40.jpg)
![InkedCapture3_LI](https://user-images.githubusercontent.com/57540473/84305992-e3604480-ab28-11ea-82fc-4d25740a24a9.jpg)
![InkedCapture_LI](https://user-images.githubusercontent.com/57540473/84305932-cfb4de00-ab28-11ea-9285-4e659b63a5bc.jpg)
![InkedCapture4_LI](https://user-images.githubusercontent.com/57540473/84306006-e9eebc00-ab28-11ea-85fd-d41cde4dc7b3.jpg)

**Comment by PavelBal** [comment]
Yes!!

**Comment by msevestre** [comment]
What about a mix of both ?
![image](https://user-images.githubusercontent.com/1041237/111223520-a4798680-85b3-11eb-979c-117ebabbabeb.png)

That way there is the name first and then the formula just to make sure you pick the right one?
