### ISSUE TITLE
No windows displaying when opening old simulation

### ISSUE THREAD

**Issue by saharagh** [Open-Systems-Pharmacology/MoBi#490]
When trying to open an old project, no window is opening in MoBi. Also, none of the icons of the View bar are working. The problem is still occurring after uninstalling and reinstalling the OSP Suite...

![image](https://user-images.githubusercontent.com/47666798/85020129-2a28ec80-b170-11ea-8524-9fbeb21bcf32.png)

**Comment by msevestre** [comment]
@saharagh Somehow the layout got corrupted (happens when undocking from a docking stations sometimes)

Anyways there is an easy fix.

https://github.com/Open-Systems-Pharmacology/MoBi/issues/322

Let me know if this fixes your issue

**Comment by msevestre** [comment]
note that instead of 7.3, it will be 8.0
`C:\Users\ USERID\AppData\Roaming\Open Systems Pharmacology\MoBi\8.0\Settings.xml" (replace USERID with your windows user name)`

**Comment by saharagh** [comment]
The problem is solved, thank you very much !!
