### ISSUE TITLE
Export simulation to XML

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#491]
There is no option to export a simulation to an XML any more? I don't think it the right thing to remove it at all, as many projects may still rely on the "old" r or matlab toolbox.

**Comment by Yuri05** [comment]
it's available if you start PK-Sim/MoBi in dev-mode. We will explain it in the Release Notes
![grafik](https://user-images.githubusercontent.com/25061876/85133240-a2f47b00-b23a-11ea-9477-19c50854c291.png)

**Comment by PavelBal** [comment]
All right.
