### ISSUE TITLE
Bug: Export of Journal crashes due to outdated Latex package

### ISSUE THREAD

**Issue by maalbrec89** [Open-Systems-Pharmacology/MoBi#496]
Hi everyone,

I cannot export journal reports by selecting "Import/Export/Project Report" and get the following errors:

![MoBiError](https://user-images.githubusercontent.com/52818721/86099524-e0b59700-bab7-11ea-8fec-a779c59352d3.PNG)
![LatexError](https://user-images.githubusercontent.com/52818721/86099516-dd221000-bab7-11ea-96c9-b0c1f3a11100.PNG)

so basically expl3 is not supported anymore, which leads to the crash of the longtabu environment.

**Comment by msevestre** [comment]
@maalbrec89 I am a bit confused here. Journal does not used miktex. What are you trying to export?
Where is the table coming from? 

How did you install the miktex package? Did you have it on your machine before?

**Comment by maalbrec89** [comment]
That is strange. On the Figure, you see some journal entries on the right-hand side. I wanted to export it and have chosen the yellow marked button. Then, it crashed. I was actually not expecting MikTex but I found a generated folder with Latex files and I tried to compile them to see why it broke down.

So the journal itself is not in Latex but the export function generates a kind of Latex-dependent folder.

![grafik](https://user-images.githubusercontent.com/52818721/86134178-99e09500-bae9-11ea-9c02-e27b6ad8a87e.png)

**Comment by msevestre** [comment]
The button is exporting the project (e.g the MoBi file) and has nothing to do with the WJ
If you want to export the WJ, please use the Export Journal button instead
![image](https://user-images.githubusercontent.com/1041237/86134895-22464200-bab8-11ea-9079-c04ddfb771f8.png)

**Comment by maalbrec89** [comment]
Ah okay. Nevertheless, the "Import/Export"/"Project Report" button leads to a crash, independent of the working journal then.

**Comment by msevestre** [comment]
yep. Probably because you have another miktex installation on your machine? 
Can you ask someone else to export and see if this work? We know that an other miktex installation corrupts the one we install with the suite. After that...it's more or less impossible to get right :)

**Comment by maalbrec89** [comment]
The same file seems to compile on Vanessa's laptop, albeit it needs quite long. I guess I will add a warning in the documentation (Installation) for the next people in case it is still missing there. I have first to figure out how the documentation editiing process works.

**Comment by Yuri05** [comment]
obsolete (no pdf reports anymore). closing
