### ISSUE TITLE
MoBi Crash

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/MoBi#497]
PBPK/PD model crashes after
(1) MoBi re-start
or (2) start of parameter estimation. 

even though simuations worked without any problems before.   

Error message "Object reference not set to an instance of an object."

**Comment by msevestre** [comment]
@lkuepfer Can you reproduce this problem consistently or is this a one time off?
Any chance you can share a project to reproduce this behavior?
/cc @Yuri05

**Comment by PavelBal** [comment]
Cannot reproduce without an example.
