### ISSUE TITLE
"Expected number of solver warning does not match"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#506]
What exactly does it mean? Getting this since V9 now and then.

**Comment by msevestre** [comment]
You are going to have to explain what you mean here.

**Comment by PavelBal** [comment]
Sometimes simulations fail (or PI runs fail) with the above mentioned message.

**Comment by PavelBal** [comment]
@msevestre Do you still require more feedback? What kind of feedback?

**Comment by msevestre** [comment]
Yes. In order to solve an issue, we need to reproduce. IF we can't reproduce, we can't solve :)

**Comment by PavelBal** [comment]
Example simulation provided.

**Comment by Yuri05** [comment]
fixed in V10
