### ISSUE TITLE
Drag and drop of parameter to the "references area" does not work

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/MoBi#507]
Mobi, OPS version: 9.1:
Attached model (file "Model.zip"): In the spatial structure at the organism level a new parameter "AAA" is added. 
At the molecule "Rez" at the molecules building block a parameter BBB was added. In order to define the equation for parameter BBB I wanted to drag and drop the parameter AAA to the references area. The drop does not work, see the black "forbidden" sign in the picture attached. An analogous drop worked in a previous version (now only adding the reference manually works). 

[Model.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/5167270/Model.zip)
![DragDrop](https://user-images.githubusercontent.com/26439150/92091676-5cda9c80-edd1-11ea-8c6e-ae34b0ad1e03.jpg)

**Comment by Yuri05** [comment]
related to #481

**Comment by msevestre** [comment]
THis is by design
AAA is a local parameter
BBB is a global parameter. Dropping AAA (local parameter) on BBB global (parameter) in fact never worked

but I have removed this constraints. User should be able to do what they want IMO
