### ISSUE TITLE
Concentration observer producing strange values

### ISSUE THREAD

**Issue by moPellowe** [Open-Systems-Pharmacology/MoBi#510]
I have created an observer to calculate the drug concentration of the Organism container (the only container) as Amount / Volume using absolute paths. The Organism has a volume of 1L. I set the molecule start value to 1 umol. When I look at the concentration produced by the observer, the result is 3333333.25 umol/L. This doesn't make sense to me since the concentration should be Conc = 1umol / 1L, right?

Also, the concentration value does not change when I increase the volume of the Organism container to 100 L, for example. What am I missing?

![image](https://user-images.githubusercontent.com/57540473/93639963-cd83da80-f9c7-11ea-81c6-9f26b3c5214d.png)
![image](https://user-images.githubusercontent.com/57540473/93640078-f906c500-f9c7-11ea-9328-51dd51c9a6f7.png)

**Comment by msevestre** [comment]
@moPellowe Hard to tell without looking at the project

But the Dimension seems to be wrong (it reads Concentration (mass)) and you convert it back to molar. Do you maybe have a MW that is not set properly?

**Comment by msevestre** [comment]
Please attach your project if you want me to take a look

**Comment by moPellowe** [comment]
So the issue is because I had the dimension listed as Concentration (mass) instead of Concentration (molar)?
[amount_vs_concentration_test.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/5247951/amount_vs_concentration_test.zip)

**Comment by msevestre** [comment]
@moPellowe I do not know what the issue is but it seems that the observer is not defined properly :) I'll check it out and let you know

**Comment by msevestre** [comment]
@moPellowe 
THe observer is defined as a "Concentration (mass)" but the formula is molar and therefor it does not match

There is fact a warning from MoBi when you build the simulation

![image](https://user-images.githubusercontent.com/1041237/93804512-66a73100-fc14-11ea-818a-1730988b299b.png)

It just happens that we are doing some fancy conversion between molar and mass and in your case,the MW of 300g/mol was used to convert the value in g/l to umol/l (Even though no conversion is required)

So in short, if you fix the warning by setting the matching dimension for your observer, you are back to what you expect
![image](https://user-images.githubusercontent.com/1041237/93804645-a0783780-fc14-11ea-82c1-4a3ecc35bb20.png)

and everything is the same
![image](https://user-images.githubusercontent.com/1041237/93804734-bab21580-fc14-11ea-86f6-6e006255e2bf.png)


of course changing the volume also influences the conentration (change the volume in the simulation if you want the value to take effect)
![image](https://user-images.githubusercontent.com/1041237/93804836-dc130180-fc14-11ea-96d1-e44880e135ae.png)


BEWARE the curve looks the same but the y-axis is different on the left

**Comment by moPellowe** [comment]
Thanks @msevestre . That makes sense.

**Comment by moPellowe** [comment]
I changed the observer dimension to "Concentration (molar)" so the amount and concentration line up. But then, I changed the volume to 10 L and the concentration hasn't changed for me. I know that I might be missing something silly, but I can't figure out why it is not changing. What am I missing?

[amount_vs_concentration_test.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/5279036/amount_vs_concentration_test.zip)

**Comment by msevestre** [comment]
@moPellowe Where did you change the volume?

**Comment by msevestre** [comment]
@moPellowe Looking at the project
![image](https://user-images.githubusercontent.com/1041237/94197998-92305280-fe84-11ea-96f6-640003f492f8.png)

Volume 1L

![image](https://user-images.githubusercontent.com/1041237/94198033-9f4d4180-fe84-11ea-8ba6-efd2d2ac0b16.png)
Concentration: 1L

Changing Voilume to 10 in the simulation
![image](https://user-images.githubusercontent.com/1041237/94198084-b429d500-fe84-11ea-8c89-f84111498b22.png)

Running the simulation

Concnetration 0.1
![image](https://user-images.githubusercontent.com/1041237/94198119-c277f100-fe84-11ea-8d05-d1d979671a5c.png)

**Comment by moPellowe** [comment]
Ahh okay. I see the mistake. I had changed the spatial structure volume parameter, but the parameter start values were overriding that value. Thanks!
