### ISSUE TITLE
Add distributed parameter to spatial structure

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/MoBi#513]
I'd like to add a distributed parameter in MoBi, similar to this one:
![image](https://user-images.githubusercontent.com/26541603/95967025-133b9380-0e0c-11eb-9cb3-8c57f883a756.png)

However, I can't find the option for a distributed parameter:
![image](https://user-images.githubusercontent.com/26541603/95966510-82fd4e80-0e0b-11eb-8829-0683a3aa8ce4.png)

Is this hidden somewhere?

**Comment by PavelBal** [comment]
Hi Andre,

right-mouse-click on the container where you want to add the parameter and select "Add distributer parameter".

But I would also like to have a more convenient way ;)

**Comment by AndreDlm** [comment]
Thanks @PavelBal!
