### ISSUE TITLE
Disable Scroll (Mouse-Wheel) on Drop-Down Menues (maybe also for PK-Sim)

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/MoBi#515]
I might have posted this already, but it is extremely dangerous to allow scrolling in drop-downs as this often leads to accidental changes (e.g. when selecting the formula for a reaction)

**Comment by Yuri05** [comment]
>I might have posted this already

Yes, you did 😄 https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/478

**Comment by msevestre** [comment]
This is MoBi. The other one is PKsim. We might not be able to fix this all at once, therefor, let's keep it open
