### ISSUE TITLE
Confirmation message before "Commit to BB"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#518]
A propose to introduce a confirmation dialogue before invoking "Commit to BB". It happens way too often to me and some other users I know that we accidentally select "Commit to" instead of "Update from" and, since the action is irreversible, end up loosing changes we did before.

**Comment by msevestre** [comment]
I agree with this. Irreversible command should always show messages

Maybe we can rename those menus?

Commit to building block
Update from building black

Or because this is svn nomenclature and we all use git now

Push to building block
Pull from building block

....

**Comment by PavelBal** [comment]
I would not rename the commands, users are used to "commit/update" and I do not see a benefit from renaming.

**Comment by msevestre** [comment]
The rename was a joke;-)

**Comment by msevestre** [comment]
SVN vs git

**Comment by PavelBal** [comment]
:D OK didn't get that.
