### ISSUE TITLE
Allow editing "Output selections"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#526]
I would like to have the option to edit "Output selections" (as part of Simulation Settings - BB currently and as part of project options for OSMOSES). It should be possible to:
- Remove existing entries
- Add new entries by providing the full path.

**Comment by Yuri05** [comment]
assume this is obsolete after OSMOSES and closing. please reopen if not

**Comment by PavelBal** [comment]
I think it's not obsolete - default output selections should still be editable. @rwmcintosh we discussed it, right? You said it was a to do?

**Comment by rwmcintosh** [comment]
It will be covered by https://github.com/Open-Systems-Pharmacology/MoBi/issues/1163
