### ISSUE TITLE
Feature request : Enabling the export of 'PI for matlab' from PKSIM (in developer mode) for new PKSIM

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#529]
@Sulav1 commented on [Thu Nov 26 2020](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1603)

This feature in the previous PKSIM enabled to work with PI in other code based language such as Matlab. Disenabling this feature in the new version unfortunately causes loss of an important function.

**Comment by StephanSchaller** [comment]
@msevestre , didn't we discuss this (a "simple" re-enable for V10 might do the trick)?

But we should also aim at a 'PI for R' Export ;-)

**Comment by msevestre** [comment]
@StephanSchaller hmmm??

**Comment by msevestre** [comment]
As far as R is concerned...
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/d587d61e47104e236f70770917e47b0e95bc9dd5/src/OSPSuite.Core/Services/ParameterIdentifications/ParameterIdentificationExportTemplate.r#L1

This is the template that we generate. It's all ready to have but we need to know what we should generate. In the same folder, there is the example for Matlab. If you can give me a template file, we'll add it

**Comment by msevestre** [comment]
and here is the one for Matlab 
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/d587d61e47104e236f70770917e47b0e95bc9dd5/src/OSPSuite.Core/Services/ParameterIdentifications/ParameterIdentificationExportTemplate.m

 @PI_FILE_NAME
@SIM_FILE_NAMES

are string templates replaced with the name of sim etc... during export
So if you can give me an R template using the new toolbox, easy to add

**Comment by StephanSchaller** [comment]
Yes, assign it to @abdelr and @PavelBal ;-)
