### ISSUE TITLE
Illegal characters in parameter/container names

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#530]
At the moment some illegal characters can be included into parameter names, which might lead to problems, e.g.
* Double quotes
* Pipes
* ... (anything else?)

Naming check should be extended, so that those characters will be forbidden.

![grafik](https://user-images.githubusercontent.com/25061876/110501629-a9918e00-80fa-11eb-8d59-8aa71288917f.png)

![grafik](https://user-images.githubusercontent.com/25061876/110502101-2d4b7a80-80fb-11eb-86df-23a9edddfb72.png)

**Comment by msevestre** [comment]
in MoBi there is absolutly no Name check
![image](https://user-images.githubusercontent.com/1041237/110847250-b0dfa580-827a-11eb-86af-0fc992058748.png)

WHAT?!?

**Comment by PavelBal** [comment]
> in MoBi there is absolutly no Name check

But I think that a formula using such an "alias" would not work?

I can create a parameter `123`, but in the formula the alias must be `_123`, otherwise an error in the equation field is shown.

**Comment by Yuri05** [comment]
@PavelBal For a formula it's true, but it will crash elsewhere.
Try to create a simulation in this project: [P1P2.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/6151570/P1P2.zip) 😉 
![grafik](https://user-images.githubusercontent.com/25061876/111364619-c1848700-8691-11eb-962b-0e083d0f4752.png)

**Comment by msevestre** [comment]
Should not we simply disallow usage of all weird stuff like in PKSim and do if for ALL entities created from now on.
?

**Comment by Yuri05** [comment]
>Should not we simply disallow usage of all weird stuff like in PKSim and do if for ALL entities created from now on?

Would make sense :)

**Comment by msevestre** [comment]
The base class in core already is like this
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Presentation/DTO/NonEmptyNameDTO.cs#L26

Cleary Mobi does not use this
