### ISSUE TITLE
Fixed all ignored unit tests

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/MoBi#533]
There exist some unit tests that are currently failing and have been ignored to facilitate merging. The issues have to do with the redesign of the importer and with smartXLS.

**Comment by msevestre** [comment]
This is major now. We need to make sure those tests pass. ALso in Core and In PKSim

**Comment by georgeDaskalakis** [comment]
this issue has been already fixed
