### ISSUE TITLE
Differences between simulation exported from PK-Sim and re-created from BBs

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#534]
1. Export a simulation from PK-Sim to MoBi.
2. In MoBi, create a second simulation from the BBs
3. Compare simulations

I would expect no differences. However, many new containers are present in the "new" simulation and are not in the exported. Also some observer types are not identical ("Drug, Observer" versus "Metabolite, Observer").

![image](https://user-images.githubusercontent.com/25903040/110770768-02c40380-825a-11eb-9e03-596f2a3f7863.png)

**Comment by PavelBal** [comment]
Probably (partly) relates to https://github.com/Open-Systems-Pharmacology/MoBi/issues/519.

**Comment by Yuri05** [comment]
New containers: https://github.com/Open-Systems-Pharmacology/MoBi/issues/519
New observers: need to check

**Comment by PavelBal** [comment]
Example project attached here: https://github.com/Open-Systems-Pharmacology/MoBi/issues/418

**Comment by msevestre** [comment]
fixed
