### ISSUE TITLE
Cannot store a mobi file send from pk-sim

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/MoBi#556]
(OSP 10.0 test version ) After sending a pk-sim file to mobi, i could save the pk-sim file, but i could not save the mobi file...

![image](https://user-images.githubusercontent.com/25530079/116541868-4814c100-a8ec-11eb-8e23-513c2749fa22.png)

**Comment by Yuri05** [comment]
duplicates #554
