### ISSUE TITLE
Help with validating new model structure/set-up after addition of new organ compartment?

### ISSUE THREAD

**Issue by eburg007** [Open-Systems-Pharmacology/MoBi#571]
Hello all,

Using MoBi, I modified the original PBPK model structure to include a new "Lymph Node" organ. This compartment represents all lymph node structures within the body, and collects lymphatic fluid through new neighborhoods connecting each organ's interstitial to the lymph node interstitial. The lymph is then returned to the blood stream by connection of the lymph node interstitial to the venous blood plasma.

If possible, would someone be able to take a look at the model structure and verify that I've set everything up correctly?
[TFV_LN_NHP.zip.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/6650200/TFV_LN_NHP.zip.zip)

Happy to answer any other questions/provide details.
(I utilized the forum discussions github.com/Open-Systems-Pharmacology/MoBi/issues/1 and github.com//issues/302 to set up the new compartment).

**Comment by StephanSchaller** [comment]
@eburg007, the Discussion Forum is the right place for your question. I did see it but did not have time looking at your model so far.
This Repo is only for Bug Reporting.

**Comment by msevestre** [comment]
This needs to be posted as discussion in the forum

**Comment by StephanSchaller** [comment]
already done and reviewed
