### ISSUE TITLE
After import: observed data may not be modified anymore (except for the meta data)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#578]
It should not be possible to edit observed **data** in PK-Sim (**meta data** can be edited as before)
If data needs to be changed: the new "Update" functionality must be used instead.

![grafik](https://user-images.githubusercontent.com/25061876/123847766-403ac280-d917-11eb-911c-adf141843df2.png)

**Comment by abdelr** [comment]
@Yuri05 and @msevestre, at some point we added the feature to show this editor in read-only mode. This could be the case but now I wonder, could you think of any use case where the editor should allow editing the data? If not, I would suggest to remove the dual function (read-only/editable) and only use it to show the data.

**Comment by Yuri05** [comment]
not sure if it's the same editor as for **Table formulations**? If yes: we need the edit mode there
![grafik](https://user-images.githubusercontent.com/25061876/123858032-53ec2600-d923-11eb-872c-847102ea652e.png)

**Comment by abdelr** [comment]
Also, I checked and in PKSim, it is also possible to edit the data. We should also disable there.

**Comment by Yuri05** [comment]
that's why https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1820 :wink:

**Comment by abdelr** [comment]
I am closing in favor of [Core/1145](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1145)
