### ISSUE TITLE
Error_PRARM_Density(tissue)_LiverZone

### ISSUE THREAD

**Issue by tztz117** [Open-Systems-Pharmacology/MoBi#583]
Hi,

I tried to run the PD simulation of Kuepfer's paper, stuck in the simulation step with error of " Error_PRARM_Density(tissue)_LiverZone", could someone to see how to fix it?

![Error_PRARM_Density(tissue)_LiverZone1](https://user-images.githubusercontent.com/86744277/125100337-f8e6cb80-e0a6-11eb-83ff-ca5254a6e918.JPG)
![Error_PRARM_Density(tissue)_LiverZone2](https://user-images.githubusercontent.com/86744277/125100353-fc7a5280-e0a6-11eb-8e21-4cd522579308.JPG)
[Ciprofloxacin 1000 mg PO QD.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/6792351/Ciprofloxacin.1000.mg.PO.QD.zip)

**Comment by msevestre** [comment]
What is the error? Can you go with the mouse over the icon to see what's going on?
Does it happen when you create or when you RUN the simulation?

**Comment by tztz117** [comment]
"unable to ceate simulation"
![Error_PRARM_Density(tissue)_LiverZone3](https://user-images.githubusercontent.com/86744277/125102159-000ed900-e0a9-11eb-83e8-592e530bed24.JPG)

**Comment by tztz117** [comment]
found that formulad description  was somehow missing, i manually typed in:
![Error_PRARM_Density(tissue)_LiverZone4](https://user-images.githubusercontent.com/86744277/125137223-43ce0680-e0da-11eb-8065-d7bf0146e243.JPG)
