### ISSUE TITLE
SBML importer: create missing building block

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#598]
When importing an SBLM model, not all building blocks necessary for model creation are created (e.g., simulation settings). In this case, empty or default BB of the type should be created, so the user can directly create a simulation.

**Comment by Yuri05** [comment]
@PavelBal Is it fixed now? There was a PR claiming to fix the issue

**Comment by PavelBal** [comment]
I don't know, will have to check. SMBL importer is on our radar but low prio.

**Comment by StephanSchaller** [comment]
"low prio" only due to ressource limitations... technically it is relatively high prior ;-)
