### ISSUE TITLE
Nighlty build failing

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#601]
This has been going on for a while
https://ci.appveyor.com/project/open-systems-pharmacology-ci/mobi/history
Due to SBML stuff. Please fix asap (it might already be fixed with PR merged this morning)
@abdelr @georgeDaskalakis

**Comment by abdelr** [comment]
@msevestre I think it has to do with the changes on the MoBi.Engine\Sbml\SBMLImportRegister.cs file. It should be fixed when merging #599

**Comment by msevestre** [comment]
@abdelr This is adding all the stuff that we have just removed. Please review the changes because what is proposed is not ok

**Comment by abdelr** [comment]
I will take a look on Tuesday (I am on vacations tomorrow and Monday) but the changes proposed on Develop do not work and not only break some tests but also break the importer.

**Comment by msevestre** [comment]
I merged the PR this morning so the fact that it is broken has nothing to do with this... it has been broken for many many days

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/132760067-2f2f70a5-953e-4435-8e22-21dd25b10bf1.png)

**Comment by msevestre** [comment]
over a month ago

**Comment by PavelBal** [comment]
Still failing

**Comment by PavelBal** [comment]
@abdelr @georgeDaskalakis
