### ISSUE TITLE
Importer configuration created in PK-Sim not used correctly

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#628]
A configuration has been created in PK-Sim for the following mapping:

![image](https://user-images.githubusercontent.com/25903040/136057647-b1d1d297-8320-44f6-9002-4786ce29946f.png)

Using the same configuration with the same file in MoBi:

![image](https://user-images.githubusercontent.com/25903040/136058002-eb780d3f-d055-4e4a-a7a5-a54a2cf99f76.png)

1) The column "Molecular weight" cannot be selected for molecular weight
2) "Mapping Name" is "Molecular **W**eight" in PK-Sim and "Molecular **w**eight" in MoBi
3) Columns "Species", "Study Id", "Subject Id", "Gender", "Dose", "Route" are not shown as additional grouping (why do the lists of mapping settings differ betwen PK-Sim and MoBi at all?)
4) After import, all these meta data are actually present (which is good!)

![image](https://user-images.githubusercontent.com/25903040/136058656-bec04556-cdca-476a-a2f7-95a62ef0bb0a.png)

But "Molecular Weight" is also considered as meta data and not the actual molecular weight property.

**Comment by PavelBal** [comment]
FYI @msevestre @Yuri05

**Comment by msevestre** [comment]
Yeah that's a bug. All meta data should be the same, at least the default one. Good find @PavelBal

**Comment by PavelBal** [comment]
[MobiImportBug.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/7287339/MobiImportBug.zip)
Attached the Excel file and the configuration.

**Comment by msevestre** [comment]
Going to fix one obivous error and submit a PR.
