### ISSUE TITLE
Could not retrieve simulation results for [my modeling]

### ISSUE THREAD

**Issue by ImSuajo** [Open-Systems-Pharmacology/MoBi#651]
I made a model to simulate [H+].
my equation is
d[H+]/dt=(ka+ka*cos(fa*Time))-kdeg*[H+]
Here parameters are ka, fa, kdeg
and I want to calculate ka and fa and kdeg but.... when I use optimization, there is error.
The error said "Could not retrieve simulation results for..."
I use "monte-calro" algorithm

I want to know my problem's reason.
What I have to do to use 'optimization'?
HELP.... I want to graduate my university...help me....

**Comment by Yuri05** [comment]
in the project you attached all data mappings in the parameter identification are invalid
![grafik](https://user-images.githubusercontent.com/25061876/139486152-979140fc-392b-428e-b012-1c6c81d92835.png)

**Comment by msevestre** [comment]
This looks like a user issue. Please reopen if you have another issue

**Comment by ImSuajo** [comment]
[pH.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/7450310/pH.zip)
I did it but still I can't use optimization....

**Comment by msevestre** [comment]
All right so there is a bug indeed
![image](https://user-images.githubusercontent.com/1041237/139670358-a56a22e7-643c-421c-ad98-f33a06dd842c.png)

We need to investigate to know what's going on

**Comment by Yuri05** [comment]
@ImSuajo The problem in your simulations is: simulation name stored internally in each "OPZ Control (XXX)" simulation is "OPZ PO 0mg".  You can see it e.g. if you open one of those simulations amd start "Define Settings and Run" dialog:
![grafik](https://user-images.githubusercontent.com/25061876/139824108-b49cd96a-a889-4c35-95b1-03a7b9828d33.png)

A workaround to fix it: **rename** those simulations (if you want to keep the simulation name, rename it twice, e.g. rename "OPZ Control(Bruely)" to "tmp_OPZ Control(Bruely)" and then rename "tmp_OPZ Control(Bruely)" back to "OPZ Control(Bruely)"). The result:
![grafik](https://user-images.githubusercontent.com/25061876/139824645-dd7eabc6-70e0-4e23-b19e-6917b9af8c42.png)

In the PI, output names are adjusted automatically (if not: close and reopen it) and you can run it now
![grafik](https://user-images.githubusercontent.com/25061876/139824819-b0ee049c-f512-4728-b2d4-9da8976ec0b2.png)

**Comment by Yuri05** [comment]
@ImSuajo Can you explain in detail how you created those 4 OPZ Control simulations? E.g. did you export "OPZ PO 0mg" as pkml and imported it under the different name or cloned this simulation in PK-Sim and exported cloned simulations or ...?
![grafik](https://user-images.githubusercontent.com/25061876/139825117-53793fff-ce6b-423b-9709-f5a88334d624.png)

**Comment by msevestre** [comment]
@ImSuajo Yes. @Yuri05's question is very important for us to be able to solve the issue. How did you create those simulations?

**Comment by ImSuajo** [comment]
@Yuri05 I export all of these OPZ Control(XXX) same pkml and changed the name.

**Comment by ImSuajo** [comment]
@Yuri05 
[pH_1103.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/7465510/pH_1103.zip)

I changed all these OPZ Contorl(XXX) to have own 'Spatial Sturctures' but there is still error

**Comment by Yuri05** [comment]
@ImSuajo As I wrote [above](https://github.com/Open-Systems-Pharmacology/MoBi/issues/651#issuecomment-957281272): rename the simulations

**Comment by ImSuajo** [comment]
thank you for your help. you're another professor in my life.
