### ISSUE TITLE
Select "Use derivative values" in a table formula should change parameter Dimension?

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/MoBi#656]
Select "Use derivative values" in a table formula:

![image](https://user-images.githubusercontent.com/25477643/142651348-c14897c6-224d-445c-9e01-c47a817a22a1.png)

 should change the underlying parameter dimension to its original dimension dividend per minute (Dimension/min) if that is possible (e.g. when this parameter is then plotted this is not considered)

**Comment by Yuri05** [comment]
Parameter dimensions are always manually set by user, independently from the used formula.
If activated, the dimension check would usually produce a warning when creating a simulation, if parameter dimension and used formula dimension do not match (not sure if it will also be the case in this particular situation).
