### ISSUE TITLE
I want to know about 'total error'

### ISSUE THREAD

**Issue by ImSuajo** [Open-Systems-Pharmacology/MoBi#657]
When I use 'Identification' tool, I always check 'Monte-carlo' and there is 'total error' parameter.
I know that Mobi changes parameter to minimize total error.
But I don't know how to calculate total error.
I check PK-sim documentation... but I can't find.
Can anyone help me to know how to calculate total error?
Is there a equation for it? Or total error is SST?

**Comment by Yuri05** [comment]
Total error is the square root of squared weighted residuals, where each residual is either `simulated-observed` or `log10(simulated)-log10(observed)` (depending on the [Mapping Simulation Outputs to Observed Data‌](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#mapping-simulation-outputs-to-observed-data)).
Weights (which are all = 1 as per default) can be set per observed data set and per observed data point as described  [Mapping Simulation Outputs to Observed Data‌](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#mapping-simulation-outputs-to-observed-data)
For the small values below LLOQ residual calculation is done depending on the LLOQ handling settings as described in [Handling of LLOQ values‌](https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/parameter-identification#handling-of-lloq-values)

**Comment by msevestre** [comment]
Please use the forum to ask questions. Thanks
