### ISSUE TITLE
Finite dose in Mobi

### ISSUE THREAD

**Issue by MelanieMartha26** [Open-Systems-Pharmacology/MoBi#662]
Dear Everyone, 

I was wondering whether it is possible to insert an event with a finite dose and, if yes, how I could implement this.

Thank you in advance!

Best regards, 

Mèlanie

**Comment by StephanSchaller** [comment]
Dear @MelanieMartha26, can you elaborate what you mean with "finite dose" and what you intend to do?

Thanks,
Stephan

**Comment by MelanieMartha26** [comment]
Dear @StephanSchaller, thank you for offering your help!

I would like to simulate a situation where you apply a certain dosis on a skin permeation model and then after several hours remove the permeant that is still left on the skin and in that way create a finite dose situation.

Thank you in advance!

**Comment by StephanSchaller** [comment]
Dear @MelanieMartha26, you can do this by defining an event at the time you want the permeant removed by setting the event in a way it sets the amount of permeant in the application compartment to zero.
