### ISSUE TITLE
MoBi cannot convert observed data units from mass to molar although Molecular weight is correctly specified in observed data BB

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/MoBi#663]
Steps to follow:
1. Observed data in unit [ng/ml] are uploaded for a compound selected from the drop down list of compounds. A right click on the uploaded observed data and selecting "Edit All MetaData ..." shows that the Molecular weight is correctly specified!
2. A simulation is created with Y-axis unit µmol/l and observed data are dragged&dropped to the simulation window. Observed data are not displayed and mouse over information in "curve options" says "cannot convert to Y-axis unit".

**Comment by msevestre** [comment]
@TWendl Can you attach a project to reproduce?

**Comment by TWendl** [comment]
Unfortunately, I cannot share the project!

**Comment by PavelBal** [comment]
I cannot even reproduce because I just cannot import any data with MW set!

**Comment by PavelBal** [comment]
Fixed.
