### ISSUE TITLE
Importer: MoBi: Molecular Weight is treated as a group

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#669]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/inst/extdata/Aciclovir.pkml

with [Acicloriv.xlsx](https://github.com/Open-Systems-Pharmacology/MoBi/files/7838382/Acicloriv.xlsx)

with this mapping:

![image](https://user-images.githubusercontent.com/25903040/148757101-606f103c-1626-4d8a-aac9-fc2602be46d2.png)

-> Add all sheets -> Import ->

![image](https://user-images.githubusercontent.com/25903040/148757250-3ffe3b9d-409c-447f-8bcd-7ab73c405966.png)

125 is the value in the MW columen, the groups are "a", "b", and "c". All three imported data sets get the group "125"

**Comment by georgeDaskalakis** [comment]
Not reproducible anymore, probably solved through
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/1443
