### ISSUE TITLE
"Time Profile" plots obtainable after "Parameter Identification" are missing lines

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/MoBi#67]
I used a model with >2000 time points set in the output interval.  After PI, I selected "Time Profile". Curves with dotted or dashed lines or the experimental data with only points look normal, but solid lines are either invisible or displayed only as faintly dotted lines.

**Comment by msevestre** [comment]
Is this something new (7.1) or can you observed the same behavior with your
current version (7.0 or older)

**Comment by UlrichSi** [comment]
It works ok in MoBi 6.4, so this is new. - It seems that the pixel density in all solid lines has been changed, but in standard simulation plots the lines are still ok.

**Comment by msevestre** [comment]
Could you attach a test project? (project will need to be zipped)

**Comment by msevestre** [comment]
@rwmcintosh can you look at that?

**Comment by msevestre** [comment]
I suspect it;s a devexpress change...but who knows

**Comment by UlrichSi** [comment]
Test project attached to YT 46-7469.

**Comment by msevestre** [comment]
I can reproduce

**Comment by msevestre** [comment]
@rwmcintosh Back to you. I have fixed all the issues with the Chart Editor Layout. The problem still remains. Maybe you'll have an idea as to what might be wrong.

**Comment by Yuri05** [comment]
Here also a PK-Sim project, where the problem can be reproduced (in the simulation _**OLD_iv**_)
[Paracetamol_IV_Old_vs_New.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/920307/Paracetamol_IV_Old_vs_New.zip)

**Comment by msevestre** [comment]
That now really looks like a bug in DevExpress. Probably with too many points and LineStyle dash

**Comment by msevestre** [comment]
going to thickness 3 solves the issue for example. Very weird

**Comment by msevestre** [comment]
@rwmcintosh Could you submit an issue with DevExpress (unless you know what might be going on?)

**Comment by rwmcintosh** [comment]
That's been submitted to DevExpress
https://www.devexpress.com/Support/Center/Question/Details/T503976

**Comment by msevestre** [comment]
Swift response:

We have already fixed this behavior in the context of the Line Series is
rendered as a dashed line in certain situations
<https://www.devexpress.com/Support/Center/p/T478325.aspx> topic. Update
our controls to the recent (16.2.6) version and let me know whether it
solves the issue.

**Comment by msevestre** [comment]
The update to devexpress fixes the issue. Yet the line look thinner than before. 
@rwmcintosh Could you update the issue and let them know that the line thickness is not as it used to be and see what they have to say

**Comment by msevestre** [comment]
@UlrichSi Please try the new version when you have time and let me know what you think. This issue is due to a high density of points I believe

**Comment by UlrichSi** [comment]
Looks ok now. Solid lines with many points now (build 36) have a sawtooth appearance, but they are clearly visible and will suffice.

**Comment by msevestre** [comment]
@rob: can you update your ticket with DevExpress and let them now that the
curves are better but still not as good as they were?

**Comment by rwmcintosh** [comment]
I posted two screenshots. Before and after update to latest DevExpress

**Comment by UlrichSi** [comment]
@rwmcintosh: where do I find those screenshots?

**Comment by rwmcintosh** [comment]
@UlrichSi They are in the support request at DevExpress. You have to scroll down to where I posted a response.

https://www.devexpress.com/Support/Center/Question/Details/T503976

**Comment by rwmcintosh** [comment]
This has gone to the second tier support at DevExpress for investigation.

**Comment by rwmcintosh** [comment]
Suggestion from DevExpress is to enable Anti-aliasing.

https://documentation.devexpress.com/#CoreLibraries/DevExpressXtraChartsLineSeriesView_EnableAntialiasingtopic

**Comment by rwmcintosh** [comment]
Anti-aliasing set as default
![image](https://cloud.githubusercontent.com/assets/261477/26650053/3528cb78-4616-11e7-81c2-59d2c3a47cf0.png)

Anti-aliasing set to true for all curves
![image](https://cloud.githubusercontent.com/assets/261477/26650144/7c9a399c-4616-11e7-9694-9cd9cbc8b823.png)

For me this second curve looks like 7.0 and older. We have the option to turn it back on for all curves or leave it as it is now.

**Comment by msevestre** [comment]
is there a big performance difference?

**Comment by rwmcintosh** [comment]
Hard to tell. Makes very little difference to the load time of this chart if any. Most charts probably have anti aliasing turned on by default since the default behavior of this property is to allow DevExpress to decide based on point density and maybe some other factors.

In the DevExpress issue created, the property is described as being introduced in 'recent versions'. My guess is that we are used to anti aliasing being something that was not optional.

**Comment by msevestre** [comment]
sounds good. Let's turn it on then
