### ISSUE TITLE
Error plotting "Residuals vs time" 

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#677]
![image](https://user-images.githubusercontent.com/25903040/150979137-04fd384b-51c2-4e31-86cc-1179dcdc1cac.png)

I can send you the project via email (who wants? @msevestre @Yuri05 )

**Comment by msevestre** [comment]
Bring it on

**Comment by PavelBal** [comment]
No need, it is here:

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/5f6a4d0e86361c1489369066b46f70ac8bca8f19/src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationResidualVsTimeChartPresenter.cs#L88-L95

In case all data used in the PI have only one time point which is identical, 

` dataRepository.BaseGrid.Values = new[] {_parameterIdentification.MinObservedDataTime, _parameterIdentification.MaxObservedDataTime};`

creates a repository with two identical time points. I would propose to use something like

` dataRepository.BaseGrid.Values = new[] {_parameterIdentification.MinObservedDataTime * 0.1, _parameterIdentification.MaxObservedDataTime * 1.1};`

**Comment by PavelBal** [comment]
Or use some +-`epsilon` (I saw it somewhere else for axis extension). That way you would also cover the use case if min and max data time is 0 (for whatever reason).

**Comment by msevestre** [comment]
Interesting.....we can make it work

**Comment by Yuri05** [comment]
is adding just 1 value somehow a problem?
If not: I would prefer an explicit check (Min == Max) and inserting just 1 value in this case instead of extending the range with factor or epsilon.

**Comment by rwmcintosh** [comment]
I'll try some stuff out, but I think it's not a problem to add 1 point. The problem is when you add two points that are the same.
The error is only thrown if you go through all values and find non-increasing.

So these special cases where we always add two, maybe we just need to add a single point when they are the same. I'll see how it works.

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/e61b6c65776abfddb481a74d26479c7d55c65bbe/src/OSPSuite.Core/Domain/Data/BaseGrid.cs#L33-L53

**Comment by Yuri05** [comment]
>It works well, but we use dashed line with no point marker by default for this zero indicator. When you have a single point, there's not much to see!

I would say it's OK. If you have only 1 point - it's most likely above LLOQ
(and I would argue that a dataset with just 1 point which is below LLOQ is garbage - in such a case I would even show a warning when importing and ask user if he really wants to import. But that's a wish for later :))
