### ISSUE TITLE
Error referencing MOLECULE parameter

### ISSUE THREAD

**Issue by moPellowe** [Open-Systems-Pharmacology/MoBi#681]
I reference Fraction unbound from the MOLECULE building block, but I get an error when creating a simulation. It says that the reference uses reserved keywords. What does this mean?

![image](https://user-images.githubusercontent.com/57540473/152265143-3ea94f77-b6ee-482e-a15d-ef6c1170408f.png)

![image](https://user-images.githubusercontent.com/57540473/152264927-e386729d-ba06-4ae6-a177-2391e39e5701.png)

Edit: I noticed that if I replace MOLECULE with the specific molecule (e.g. Aciclovir), then there is no error, but I'm wanting to use the general keyword.

**Comment by PavelBal** [comment]
Could you please specify where you are trying to use this reference? Is it a parameter? If yes - where are you trying to create it?

**Comment by msevestre** [comment]
@moPellowe You are using the keyword MOLECULE which means your parameter must be defined somehow in a MoleculeContainer so that it will be replaced during model building with the corresponding molecule name (Dynamically). Probably, you have defined your `fraction unbound in interstitial fluid` in a molecule independent container?

**Comment by moPellowe** [comment]
Okay, I understand. I will move that parameter to the Molecule building block then. Thanks.

**Comment by msevestre** [comment]
It **does not have** to be in the molecule building block. It can be like any other parameters that are molecule dependent under the MoleculeProperties container in the spatial structure. But when you use the MOLECULE keyword, MoBi needs to know what Molecule you are referencing

**Comment by moPellowe** [comment]
So for example, the parameter could be defined as NEIGHBORHOOD|MOLECULE|Fraction unbound... ? 

In my case, the formula result should not change between containers, so I'm thinking that it should be a property of the molecule. Although I know that this parameter will have to be added to every compound that I want to use with my model. Is there best practice in terms of where to define a molecule-dependent parameter?

**Comment by PavelBal** [comment]
> So for example, the parameter could be defined as NEIGHBORHOOD|MOLECULE|Fraction unbound... ?

Exactly
