### ISSUE TITLE
Importing selected data into mobi takes ages (2+ hours)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/MoBi#685]
I have created a dummy dataset similar to what i used, and tried to import it in my Mobi Model file. Somehow it takes ages to load, after 2.5h it is still loading. No error, or crashes.... 

Anyone has an idea why? I have loaded such datasets before in OSP 9 without this issue
[testcsv.csv](https://github.com/Open-Systems-Pharmacology/MoBi/files/7996526/testcsv.csv).

I had the following import configuration:

filter for importing data: by (Z = 5), (BLA = 0), (A = 0,4), (D= 0)

Mapping settings:
DOSE = X,
Subject Id: SID,
Study ID: Z,
Measurement: DV,
Time: TIME
Group By = DOSE, COLA, BLA, A, CMT,

**Comment by msevestre** [comment]
Sounds like an infinite loop to ne

**Comment by abdelr** [comment]
You have a really complex combinatorial problem here. You are creating too many datasets. Currently you have the following values for your grouping/metadata parameters:
X - 12
SID - 202
Z - 5
DOSE - 140
COLA - 2
BLA - 3
A - 5
CMT - 3
All together they make 152,712,000 combinations. The importer filters [by (Z = 5), (BLA = 0), (A = 0,4), (D= 0)] only after calculating all possible datasets so it takes indeed forever. Now even after filtering you have:
X - 3
SID - 48
Z - 1
DOSE - 26
COLA - 1
BLA - 3
A - 5
CMT - 3
All together they make 168,480 combinations. This looks like a suspiciously big number and will probably take some time to load but we can modify the code definitely to cope with it. In any case, I think that the code needs some changes for a better performance.

**Comment by Incei** [comment]
The idea behind these groupings was to have the option to sort different studies also into sub-groups, incase I want to exploratory investigate some parameters. 
If you can modify the code, this would be ofcourse great.

**Comment by abdelr** [comment]
Sure, we will discuss the details and keep you posted.

**Comment by msevestre** [comment]
@Incei and you could load 100k+ repo in Mobi before? I am a bit... sceptical

**Comment by Incei** [comment]
@msevestre when are you not skeptical... :-)
As said I have loaded such datasets before, but perhaps not that many groupings.

**Comment by msevestre** [comment]
>This looks like a suspiciously big number and will probably take some time to load but we can modify the code definitely to cope with it

I do not think that MoBi nor PKSim will be able to handle 100k + datarepository. We are importing them all as different entities.This will probably crash the UI

**Comment by Incei** [comment]
After reading https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1285  I guess, there will also be saving issues at the end. I need to use far less groupings, or separate files. 

So In case the software cannot deal with this many groupings, I will import it differently, all good, and thanks for considering it.

**Comment by Yuri05** [comment]
>The importer filters [by (Z = 5), (BLA = 0), (A = 0,4), (D= 0)] only after calculating all possible datasets so it takes indeed forever.

This could be improved for sure by executing the filtering as the **first step**.

>All together they make 168,480 combinations.

It's a huge amount and I doubt it can be ever handled by the software. 
But I assume the data should be used not **directly** but somehow **aggregated** instead?

**Comment by Incei** [comment]
> It's a huge amount and I doubt it can be ever handled by the software. But I assume the data should be used not **directly** but somehow **aggregated** instead? @Incei

Yes, the plan was to only import 1 study (Study Z = 5) from a list of studies, and I wanted to sub-group the individuals from that study by the dose, and some other factors for exploration...so at the end the dataset was not supposed to be that big.

**Comment by Incei** [comment]
@msevestre  @abdelr  @Yuri05 

I just checked the dummy dataset that I send, it seems the dose column is wrong! It should have only been 3 different doses, there are like more than 25 in there...Sry. Unfortunately i cannot share the original datafile. 
I will reupload the dummy after checking the collumns again...

**Comment by Incei** [comment]
Here it is,
[testcsv.csv](https://github.com/Open-Systems-Pharmacology/MoBi/files/8003415/testcsv.csv)

**Comment by Incei** [comment]
Actually the more I think about it, as there is only 1 dose for each ID, this should not be multiplied to calculate the amount of datasets.... since every individual receives only 1 dose.. 

**This would mean **only 288 datasets**,**  and not 100k +

**Comment by abdelr** [comment]
Hi @Incei 

Could you please check if you selected the use of the filter for importing the data. If you did not then the filter is only used to show your data but it is ignored during import. Check the image below. So, if this check box is not selected you are actually loading all your datasets on your file.

![image](https://user-images.githubusercontent.com/7632459/153561550-87a38563-19f6-4c3c-bc25-fdaa051934e1.png)

**Comment by Incei** [comment]
This was indeed the problem! Thank you. I have discussed this shortly with @Yuri05 too and am in very much favor to have this option automatically activated.
Cheers

**Comment by abdelr** [comment]
Good to know. I was just checking you were informed about this. So, it is OK if I create an issue for the default behavior to be activated and close this issue, right?

**Comment by Incei** [comment]
That is right, many thanks!

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1491](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1491) via [**ZenHub**](https://www.zenhub.com/)
