### ISSUE TITLE
MoBi 11: Very big icons

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#713]
![grafik](https://user-images.githubusercontent.com/25061876/162009255-fcc6e9e3-18c0-46ae-827d-41fb87c64336.png)

![grafik](https://user-images.githubusercontent.com/25061876/162009452-fa358e37-8c66-47c2-aa14-5131d3f080a2.png)

![grafik](https://user-images.githubusercontent.com/25061876/162009996-e8d119f4-9ba4-40a0-8788-85f4605926ca.png)

![grafik](https://user-images.githubusercontent.com/25061876/162010375-aad60946-167a-42bd-bd87-d07087d101d0.png)

![grafik](https://user-images.githubusercontent.com/25061876/162010513-4bcc38ce-bd6d-4f74-b848-73ffa6e7b3dc.png)

**Comment by msevestre** [comment]
looks nice
