### ISSUE TITLE
"Chart editor" frame size gets reset after each simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#724]
Every time I run a simulation, the "Chart Editor" size gets reset:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/25903040/170990635-c204fefa-84b4-4a80-afdc-b4b5acbbd715.png">

**Comment by Christoph27** [comment]
... and not only after each simulation, re-clicking a simulation is sufficient for re-sizing (and sometimes completely covering the results window).

**Comment by msevestre** [comment]
Will be fixed in v11 Update 1

**Comment by msevestre** [comment]
@PavelBal @Christoph27 @abdullahhamadeh @Yuri05 

Here is a workaround for now

1. Go to MoBi. Open A simulation with a chart.
2. Run the simulation
3. Go to the pin icon. It will look like this
![image](https://user-images.githubusercontent.com/1041237/176966907-f4ecde99-8b06-43ea-8560-833711605f6e.png)
4. **Unpin** it **** THIS IS VERY IMPORTANT *****
5. Click on Layout 
6. Click on Save to User Settings

![image](https://user-images.githubusercontent.com/1041237/176967203-ed557a99-c879-4ea9-8325-d0a5ae023b9f.png)

The problem. The Layout templates were all created again after the addition of the Color Grouping Feature with the pin on.
In MoBi, the layout is applied after each RUN and not when the view is initialized so it shows the settings again

I am suggesting removing this Template layout stuff completely.  I do not know of anyone using it *actively* and I think this is yet another feature that was implemented without a need and just creates maintenance problems.

**Comment by msevestre** [comment]
This is fixed with #732
