### ISSUE TITLE
Layout problems in MSV-BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#725]
<img width="761" alt="image" src="https://user-images.githubusercontent.com/25903040/170995358-0bc1e4bb-ed4b-4287-be5e-45b9a7058b4b.png">

**Comment by msevestre** [comment]
We need screen resolution and scaling here please

**Comment by msevestre** [comment]
With the propsed changed
![image](https://user-images.githubusercontent.com/1041237/177057262-afe8693b-8bac-48d8-8349-7f1144cc9735.png)

**Comment by msevestre** [comment]
This is a 225% scaling
