### ISSUE TITLE
Chart Editor panel automatically resizes and hides plots after every simulation run

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/MoBi#732]
For example: before clicking 'Run':

![image](https://user-images.githubusercontent.com/18409098/176909279-c91ab1ea-1b5a-453a-b458-6021cae391b3.png)

and immediately after clicking 'Run':

![image](https://user-images.githubusercontent.com/18409098/176909335-c98306e8-5c0e-4b34-9456-158ab94c4690.png)

Makes it very hard to spot shifts in the plots due to, eg, a parameter change.

**Comment by msevestre** [comment]
>Makes it very hard to spot shifts in the plots 

Would be to easy to earn the big $$ otherwise

Also duplicate of #724
