### ISSUE TITLE
UI: unnecessary scroll bars in explorers

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#739]
![image](https://user-images.githubusercontent.com/25903040/182330564-aa1497d4-735a-45bf-b353-60f01fbb51e5.png)

The scroll bars appear even if the whole content fits into the frame.

**Comment by msevestre** [comment]
That's because you have a big name under one of the. Node I presume?  This was the only way to ensure that the scroll bar was visible when you expand the nodes so that it does not get truncated
