### ISSUE TITLE
UI: Value origin has unnecessary row

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#740]
![image](https://user-images.githubusercontent.com/25903040/182330957-1fc1967d-df0a-43fb-b2d2-20e05412e8f5.png)

The second row is empty (no action when clicking on it).

**Comment by PavelBal** [comment]
Can confitm that its still there.

**Comment by rwmcintosh** [comment]
Let's remove this for now. It doesn't stop anyone from working with V11 update 1

**Comment by PavelBal** [comment]
Not repdocudible.
