### ISSUE TITLE
UI: Reaction -> Stochiometry -> Empty column

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#742]
![image](https://user-images.githubusercontent.com/25903040/182331908-43f490b6-6b2e-449a-ba02-9e8306ff0452.png)

There is an unused column in the "Stoichiometry" tab of a reaction.

**Comment by PavelBal** [comment]
Actually also:

- All formula aliases frames
![image](https://user-images.githubusercontent.com/25903040/182332061-920405fc-f531-4778-a7c7-d1b714ad1a86.png)

- Reaction -> Modifiers
![image](https://user-images.githubusercontent.com/25903040/182332378-f966ec3f-c454-4e1d-9233-2b06c456533d.png)

**Comment by msevestre** [comment]
it is not empty... there is the X button lo
![image](https://user-images.githubusercontent.com/1041237/189186173-d7764534-e909-4d0f-8bc8-2822be4ef43f.png)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/189192557-086b99d6-4f44-4621-af74-04e136843e5c.png)

225% scaling
