### ISSUE TITLE
UI: Passive transports -> "Add molecule" button

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#743]
Are too small

![image](https://user-images.githubusercontent.com/25903040/182332765-d058998c-afde-46fc-974c-9ba87e4a85df.png)

**Comment by StephanSchaller** [comment]
I think it fits with the overall scaling, no?

**Comment by PavelBal** [comment]
The height of the buttons is smaller than the hight of the icons. We see this behavior everywhere - they do not scale equally.

**Comment by msevestre** [comment]
Looks good on my machine with the upcoming fix. Please review once this is merged
100% scaling
![image](https://user-images.githubusercontent.com/1041237/189141714-6b64f630-710f-4035-b0bc-0422a4200c69.png)

225% scaling
![image](https://user-images.githubusercontent.com/1041237/189142282-8af4d687-dc95-42b2-b1ed-aaa9d20a8d5a.png)
