### ISSUE TITLE
svg for MoBi splash screen logo

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/MoBi#746]
Same issue as in https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2289

@StephanSchaller: Do you have an svg for MoBi too? :)

**Comment by msevestre** [comment]
@StephanSchaller: Can you attach here the one for MoBi with the updated R etc?

**Comment by StephanSchaller** [comment]
Here again the OSP Tool Logos... 
[OSPS Logos Vector.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/9530907/OSPS.Logos.Vector.zip)
for R, I have this one: https://www.r-project.org/logo/

**Comment by msevestre** [comment]
Looking at this file, it is not a real svg but a png in SVG disguise.

**Comment by StephanSchaller** [comment]
> Looking at this file, it is not a real svg but a png in SVG disguise.

Which one? MoBi/PKSim should definitely be svg

**Comment by msevestre** [comment]
Both of them. You can tell by the size (over 1MB). It's basically just the png file that was converted in SVG. by loading the image in a base64 string. A little bit of a scam between you and me :)

**Comment by StephanSchaller** [comment]
you mean a re-vectorized image?...
It seems there is some rasterized image material in there. I could try remooving it:
![image](https://user-images.githubusercontent.com/25477643/192887462-558b83d4-0c37-470c-9ef4-825ff7fe868a.png)

**Comment by msevestre** [comment]
No i Mean the whole image (That I received) is a png 

![image](https://user-images.githubusercontent.com/1041237/192888230-219d08b1-3601-4c85-b596-4adfd65824d0.png)

Look at the size of it This is opening the file in a code editor. An SVG (a real one) does not like this.
This SVG won't scale up or down properly. It's better than what we had before so it's a good (small) step in the right direction. But a good step nonetheless
