### ISSUE TITLE
Simulation - move tag "Data" to "Results" instead of "Parameters"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#749]
![image](https://user-images.githubusercontent.com/25903040/185143793-b94205f2-8815-48cb-ba06-38e833d3a964.png)

Or even make it a new "major" tab next to "Parameters" and "Results".

**Comment by msevestre** [comment]
What is data??

**Comment by PavelBal** [comment]
Similar to what is implemented in PK-Sim - mapping of obsreved data with simulation outputs:
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/discussions/1628

**Comment by msevestre** [comment]
@georgeDaskalakis Change the icon: It should be the observed data icon
