### ISSUE TITLE
Comparison does not include container criteria for parameter

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#751]
When comparing e.g. two molecules BBs, the container criteria of parameters are not listed.

**Comment by msevestre** [comment]
It's probably in core. 
And it's probably a one liner code if we have already a way to compare criteria
There is ParameterDiffBuilder and in there, we need to add the comparison for the missing properties

**Comment by msevestre** [comment]
This is done
