### ISSUE TITLE
Description of Sink Condition parameters inconsistent

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/MoBi#752]
Exporting a model from PK-Sim to Mobi changes the "Sink Condition" parameter value from "No Sink Condition" to 0, which is defined as sink condition. The model behavior is the same in PK-Sim and Mobi though and consistent with "No Sink Condition" in my interpretation. I tested this with a small molecule in the small molecules model with default parameterisation in v11
PK-Sim:
![image](https://user-images.githubusercontent.com/8969023/188901985-529ba677-3398-4b3b-8058-2cc7af84cbd2.png)
![image](https://user-images.githubusercontent.com/8969023/188902123-7413649b-49f3-4a25-a3f2-da3dae251a65.png)
Mobi:
![image](https://user-images.githubusercontent.com/8969023/188902412-101a1e61-ef9a-49f6-bfe9-f3d00250902c.png)
![image](https://user-images.githubusercontent.com/8969023/188902604-46773855-8efc-470d-b89a-192f01f3ac7f.png)

**Comment by Yuri05** [comment]
Both PK-Sim and MoBi can deal with **numeric** parameters only. Yes/No or True/False parameters are always represented internally by 0 or 1.
PK-Sim hides the values 0/1 from the user by representing the parameters in more user friendly way (e.g. "No sink conditions").
MoBi does not.
So in fact nothing changes in the model when exporting from PK-Sim to MoBi - only the **display** of the parameter value in the user interface is different

**Comment by msevestre** [comment]
It seems that the tooltip is wrong?

**Comment by PavelBal** [comment]
> It seems that the tooltip is wrong?

Looks like it, yes...

**Comment by wilbertdew** [comment]
Indeed that was my impression, sorry should have specified.

Op do 8 sep. 2022 10:55 schreef Pavel Balazki ***@***.***>:

**Comment by Yuri05** [comment]
This was fixed with https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2932
