### ISSUE TITLE
text boxes cut-off in parameter menu

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/MoBi#757]
![image](https://user-images.githubusercontent.com/18409098/189544523-d4846d35-f070-431d-aa66-4398e9ce4d50.png)

**Comment by PavelBal** [comment]
Can confirm on 4k 200%.

**Comment by rwmcintosh** [comment]
The fix I have right now is not perfect, but it's better than what I found. There's just a little bit of extra margin on those ValueEdits (with two text boxes beside one another).

![image](https://user-images.githubusercontent.com/261477/196243041-db7d4d3c-ba52-4fca-a929-544829b2343a.png)

Should we proceed with this and maybe leave this open but removed from Version11 Update 1?

**Comment by rwmcintosh** [comment]
Without scaling it's normal.

![image](https://user-images.githubusercontent.com/261477/196243654-6e5d1396-67f1-4d47-b968-3e2d5589a4cb.png)

**Comment by msevestre** [comment]
Looks awesome. Well done.
Let's create a new issue for the problem. We may never fix this
