### ISSUE TITLE
If a simulation output is assigned to an axis with a different dimension, Mobi gets stuck

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/MoBi#766]
If I include an output with another dimension than the two already included in the plot, and I assign it manually to a different Y axis while something else is already plotted there or the y-axis has the wrong dimension, I cannot do much else then closing the file. This also happens when I have only two output dimensions and I change the Y2 also to Y.
I have the situation as below and I cannot:

- remove the output
- change the dimension of the graph after removing the previous Y2 output
- change the y-axis
- close the simulation
- open another simulation

I can still close other windows, extend the folders in the building blocks view and save the file, so Mobi isn't entirely stuck, and I can close and reopen the file. 

![image](https://user-images.githubusercontent.com/8969023/193762513-38f05a31-dd45-484d-b97c-c1641a59a7a9.png)

**Comment by PavelBal** [comment]
Hit "Esc" in this situation...

Unfortunate behavior, but I am not sure it can be fixed.
