### ISSUE TITLE
Wrong icon for "Events"-BB

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#768]
When editing an Events-BB, the "Passive Transports"-icon is shown in the tab.

![image](https://user-images.githubusercontent.com/25903040/194297010-1cf486f9-3f40-4f9a-a8ec-048e8c114562.png)

**Comment by msevestre** [comment]
I can confirm. WTF

**Comment by msevestre** [comment]
this is fixed
