### ISSUE TITLE
Parameter added to an inhibition/induction process should be GLOBAL

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#769]
I created a new parameter in the Induction-Process container of a molecule in the Molecules-BB:

![image](https://user-images.githubusercontent.com/25903040/194347920-ba2fc0af-e26e-4ad0-8566-4f4cbd0d6ac9.png)

When I create a simulation with this building block, the parameter is not there:

![image](https://user-images.githubusercontent.com/25903040/194348135-01dbf5ed-ad19-4106-889d-df0c0dd2e161.png)

@Yuri05 @msevestre Could you explain? Am I doing something wrong?

**Comment by msevestre** [comment]
can you attach a project so that I can reproduce?

**Comment by StephanSchaller** [comment]
And you are sure you are using this Building Block? 
Can you expand the PSV BB and find the parameter there?

**Comment by PavelBal** [comment]
> And you are sure you are using this Building Block?

Please! :D

> Can you expand the PSV BB and find the parameter there?

No parameters from Induction/Inhibition processes or active transportrs are in the PSV BB.

**Comment by msevestre** [comment]
I am looking at it now....

Mansplaning lol

**Comment by StephanSchaller** [comment]
> I am looking at it now....
> 
> Mansplaning lol

Sometimes the obvious is the solution ;-)

**Comment by msevestre** [comment]
The issue I believe is that by default the parameter is created as a LOCAL parameter
![image](https://user-images.githubusercontent.com/1041237/194394042-b758cd58-232e-4553-b6b9-3919d394ddc2.png)

(This is definitely a bug as Local parameter are probably ignored at this level)

If I change it to global, it works
![image](https://user-images.githubusercontent.com/1041237/194394480-f72886b4-0981-4e8c-b4b9-a4690d735ed5.png)

**Comment by msevestre** [comment]
I aam going to rename this issue to Parameter in process should be created as GLOBAL

**Comment by PavelBal** [comment]
WHere can you change the type??

![image](https://user-images.githubusercontent.com/25903040/194395380-5939f672-41dc-4cb7-a9eb-6ad7cb5ded5c.png)

**Comment by PavelBal** [comment]
LOL, the "type" column is not shown be default...

**Comment by msevestre** [comment]
right click on the header, drag the type column
It's not show by default because in this case, it should ALWAYS BE GLOBAL
