### ISSUE TITLE
Rename Data tab in SImulations

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/MoBi#778]
It is proposed to rename the "Data" tab on MoBi simulations to "Observed Data" since it more accurately representes the content and function of the tab. It is also suggested to change the icon to the observed data icon. 

![image](https://user-images.githubusercontent.com/37107428/197538360-9d062196-06cf-4789-bbab-f707c16aab5a.png)

@PavelBal any pushback on this?

**Comment by PavelBal** [comment]
Nope.

georgeDaskalakis ***@***.***> schrieb am Mo., 24. Okt. 2022,
15:36:

**Comment by Yuri05** [comment]
I think this is fixed?

**Comment by georgeDaskalakis** [comment]
yeap fixed
