### ISSUE TITLE
11.1 Observed data not automatically mapped

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#800]
e.g. here I have some data sets for Alfentanil, Peripheral Venous Blood, Plasma - and the curve is simulated
![grafik](https://user-images.githubusercontent.com/25061876/202006545-8e4d419b-ca1d-481b-b670-bf6b1122e5c5.png)
![grafik](https://user-images.githubusercontent.com/25061876/202006652-45d2d23a-b3a5-4728-a9a3-62e61be1a2b6.png)

But when adding observed data to the chart: no mapping as per default
![grafik](https://user-images.githubusercontent.com/25061876/202006734-3a59f7b3-d1ad-46a5-af02-7120eec98d18.png)

**Comment by msevestre** [comment]
This I don't get. This should be the same code used in all application to do the mapping

**Comment by rwmcintosh** [comment]
Sorry, I wasn't working on #801. It was in Core. Open-Systems-Pharmacology/OSPSuite.Core#1794

**Comment by georgeDaskalakis** [comment]
@Yuri05 cannot reproduce, when I manually create the same user case in my project, it gets mapped automatically. If you still have the issue could you attach a project so I can debug?

**Comment by PavelBal** [comment]
Because its **Peripheral Venous Blood** in PK-Sim and Data, but **PeripheralVenousBlood** in MoBi... Because of this inconsistency it is also not possible to have one excel file structure that could be equally imported for PK-Sim and Mobi.

**Comment by Yuri05** [comment]
@georgeDaskalakis @rwmcintosh  With the latest Mobi (Core 11.1.60) I still have the same problem.
I think it's what @PavelBal said.

But: I changed the Organ of all observed data sets to "VenousBlood" and calculated "VenousBlood" as output.
Even here, adding obs data sets to the simulation does not map them automatically to the venous blood.

s. attached project: drag all obs data into the simulation, reopen it (refreshing of the observed data tab not working yet) and check the mappings: all set to none
[P4.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/10040992/P4.zip)

**Comment by georgeDaskalakis** [comment]
@Yuri05 I ll debug in the project and let you know ;)

**Comment by georgeDaskalakis** [comment]
> @georgeDaskalakis @rwmcintosh With the latest Mobi (Core 11.1.60) I still have the same problem. I think it's what @PavelBal said.
> 
> But: I changed the Organ of all observed data sets to "VenousBlood" and calculated "VenousBlood" as output. Even here, adding obs data sets to the simulation does not map them automatically to the venous blood.
> 
> s. attached project: drag all obs data into the simulation, reopen it (refreshing of the observed data tab not working yet) and check the mappings: all set to none [P4.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/10040992/P4.zip)

@Yuri05 When I follow the described steps I get this:

![image](https://user-images.githubusercontent.com/37107428/202924679-5f9ea8e9-ddbb-447b-901b-51f4208848d2.png)


which I would say is a correct mapping. I am doing this on the latest develop of MoBi with the latest Core develop dlls copied. I think something that is not an issue anymore, still I suggest we keep it open so @Yuri05 can check once again on the beta that it is not reproducible anymore (cause if it still is something really weird is going on.)

**Comment by PavelBal** [comment]
@Yuri05 could you check again?

**Comment by Yuri05** [comment]
It does NOT work (MoBi 11.1.90 = latest nightly)
Even worse: #799 which was fixed, does not work anymore as well.

**Comment by PavelBal** [comment]
Cannot reproduce. Latest MoBi nightly (11.1.93), downloaded P4

Open simulation, dradndropp all obs data to the "Results"-tab, switch to "Observed data" - all is mapped there.

**Comment by Yuri05** [comment]
Reproducible on my computer with 11.1.93 and P4. Showed it yesterday to @rwmcintosh

**Comment by msevestre** [comment]
It works as expected here. 
I am using it locally from vscodfe. I am going to use the latest build
