### ISSUE TITLE
11.1 No refresh of GOF charts

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#801]
(continues the issue #800) 
After setting the mapping manually: GOF charts are not refreshed (e.g. predicted vs. observed shows onlythe identity line)
![grafik](https://user-images.githubusercontent.com/25061876/202007138-fe546f8e-b79a-4589-8fa7-ba9f7f33a59f.png)
![grafik](https://user-images.githubusercontent.com/25061876/202007193-38852f16-6960-4fd6-80ae-17bbee8811da.png)

After closing and reopening the simulation: both GOF plots are shown correctly

**Comment by msevestre** [comment]
A quick and dirty solution, if it's hard to react to event changed somehow, it to add a refresh button

**Comment by rwmcintosh** [comment]
Seems related to Open-Systems-Pharmacology/OSPSuite.Core#1794
Let's merge that PR first and see what might be left

**Comment by msevestre** [comment]
@georgeDaskalakis @Yuri05 @rwmcintosh 
There is a much bigger probkem than this. The charts are not saved AT all in the simulation . They are just transient. as soon as you close the presented and reopen it, everything is gone.

**Comment by msevestre** [comment]
This seeems to be working now after my changes for serialization. That being said, the identity line is not drawn automatically. I am not quite sure why
