### ISSUE TITLE
Distributed parameter with descrete distribution?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#819]
I suppose that `Mean` is wrong, it should be something like `Upper bound`?

![image](https://user-images.githubusercontent.com/25903040/205885025-f1ae1d64-4fdc-4e4b-9917-66a60ef27928.png)

Or another question - what is the `Discrete distribution`?

**Comment by Yuri05** [comment]
>what is the Discrete distribution?

Const value.
https://docs.open-systems-pharmacology.org/working-with-mobi/mobi-documentation/model-building-components#working-with-constant-and-distributed-parameters

**Comment by PavelBal** [comment]
Ok... Confusing, as the mathematical definition of a "Discrete distribution" is different.

**Comment by PavelBal** [comment]
@Yuri05 Could you help?

**Comment by PavelBal** [comment]
Ok makes sense. Thanks!
