### ISSUE TITLE
Drag and drop same obs data on chart duplicates mapping

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#821]
![image](https://user-images.githubusercontent.com/1041237/205927842-8aea5010-8622-48a5-809a-934fbb5f5846.png)
I believe this is NOT by design
Using project from #800

IMO, obs data should only be added once to the list

Thoughts? @rwmcintosh @Yuri05 @PavelBal @georgeDaskalakis ?

**Comment by Yuri05** [comment]
>obs data should only be added once to the list 

Yes!

**Comment by PavelBal** [comment]
> obs data should only be added once to the list

Hmm... In PI we are (finally!) allowed to map the same obs data to multiple simulations outputs. I would say it should also be possible in the simulations. However, multiple mapping of the same data to the same simulation output makes no sense. So:

1. Mapping the same observed data to multiple outputs: YES
2. Mapping multiple observed data to the same output: YES
3. Duplicated mappings: NO.

**Comment by msevestre** [comment]
>Mapping the same observed data to multiple outputs: YES

Within ONE Simulation? Why does it make sense?
