### ISSUE TITLE
Sum-Formulas: PARENT Keyword

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#837]
Following scenario:
* My spatial structure has some containers with the tag "**XXX**"
* All these containers have different subcontainer structure
* I want to calculate total amount of some molecule within every **XXX**-container
![grafik](https://user-images.githubusercontent.com/25061876/207576078-7ae51f9c-af05-44e3-be70-23835be8c1d7.png)

So I would define a container observer for the molecule of interest like this:
<img width="450" src="https://user-images.githubusercontent.com/25061876/207577713-3717d82a-43c3-4568-a511-20300718b2eb.png">

Now when it comes to the observer formula, I would define a sum formula, where I need to **restrict the used quantities to the parent container (= container where my observer is created in the simulation) and all its subcontainers** - and this is currently not possible.

So I would need something like this in my sum formula:
![grafik](https://user-images.githubusercontent.com/25061876/207579181-40a1138a-a53f-4750-9194-19d4cedf6d18.png)

**Comment by Yuri05** [comment]
@msevestre @PavelBal @stephanschaller Or do you see any possibility to solve this in the current version? 
(definition of N observers - one for each XXX-container - is not an option).

**Comment by PavelBal** [comment]
Does "in container == XXX" not work?

I thought "in container" also uses tags. If not - extend the functionality to also use tags?

**Comment by Yuri05** [comment]
Yes, it uses tags. But if I define "In Container: XXX" it will sum up over ALL containers with this tag. But what I need is a sum **per Container**.

**Comment by PavelBal** [comment]
OK I see now.

Well, a keyword `PARENT` is surely a good addition, and we already require this keyword for Neighborhoods. From OSMOSES-specs:

> - It should be possible to create neighborhoods by other means than drag-and-drop. E.g., a UI "Create neighborhood", where the user selects (or types in the full path to) the neighbors. In case of a tumor module, the user would select "PARENT|Tumor|Plasma" as one neighbor, and type in "Organism|VenousBlood|Plasma" as the second neighbor. the "PARENT" keyword is necessary as the path within the module is not complete. "PARENT" will be replaced by the container that is defined in the "Parent container" property.

**Comment by msevestre** [comment]
I am wondering how this should work here. 
What should happen to the SUM Formula instance when we see PARENT? How do we extend our criteria ?

**Comment by Yuri05** [comment]
I think it should happen somewhere here:
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/91aef0a2b8dc7b2455cd6d2d05fea34ef8c9b111/src/OSPSuite.Core/Domain/Services/FormulaTask.cs#L141-L155

Usually we pass ALL potential formula usable objects when replacing the sum placeholders with the concrete entities
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/91aef0a2b8dc7b2455cd6d2d05fea34ef8c9b111/src/OSPSuite.Core/Domain/Services/FormulaTask.cs#L153

Here we could check, if one of the criteria is `InContainer:PARENT` (I think PARENT makes here sense only in Combination with IcContainer, not with other options). If yes:
* remove `InContainer:PARENT` from the criteria list
* instead of passing ALL formula usable objects, pass only **those located underneath of the parent container of `entityUsingFormula`**
  * alternatively, we could add a bunch of `InContainer `criteria for the whole path of the parent container of `entityUsingFormula`. E.g. if the parent container is Organism|Brain|Plasma we could add the criteria:
    * `InContainer:Organism`
    * `InContainer:Brain`
    * `InContainer:Plasma`
 
Something like this?

**Comment by msevestre** [comment]
I think option two is more what we need. We modify the criteria of the formula in place to make sure it only targets the parent container.
But what about a sub container in plasma? In your example, does it inherit the parent stuff?

**Comment by Yuri05** [comment]
>But what about a sub container in plasma? In your example, does it inherit the parent stuff?

Yes :)

**Comment by msevestre** [comment]
Ok then we are good

**Comment by msevestre** [comment]
@Yuri05 Is is something we want to target now?

**Comment by Yuri05** [comment]
Yes :)

**Comment by msevestre** [comment]
but this is alreayd implemented lol

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Services/FormulaTask.cs#L326

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/1901

**Comment by Yuri05** [comment]
cool 👍
