### ISSUE TITLE
Event Assignment: checkbox "Use relative path"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#845]
Additionally to https://github.com/Open-Systems-Pharmacology/MoBi/issues/164:
At the moment, when the target object was selected from the object tree - it is always enterd with its **absolute** path.
It would be good to have the possibility to enter the **relative** path instead.
![grafik](https://user-images.githubusercontent.com/25061876/208684440-411377d2-1a90-4516-bf05-1a3507b66fa0.png)

**Comment by PavelBal** [comment]
This field is editable:

![image](https://github.com/user-attachments/assets/2a965e94-529c-4fcb-957e-b1701be6f726)
