### ISSUE TITLE
an unhandled exception when open pksim11 and Mobi11

### ISSUE THREAD

**Issue by zjupharma** [Open-Systems-Pharmacology/MoBi#853]
I was just trying to open pksim11 software after completing installation, an unhandled exception was occurred as shown in following picture. Also, the same problem still exists  when I  try to install and open the earlier version, such as Pksim10.0 and Pksim9.1. Dose  someone know how to solve this problem, please let me know. 
Best regards,
Yu Wang

![the problem](https://user-images.githubusercontent.com/109033288/211196735-4e4fa562-f99b-4b98-9614-b497153c5285.png)

**Comment by Yuri05** [comment]
same as https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2505#issuecomment-1374850541
it has nothing to do with the osp suite, it's a general windows installation problem

**Comment by Yuri05** [comment]
Closing the issue according to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2505#issuecomment-1375207855
