### ISSUE TITLE
Include Initial Conditions of the associated protein in Expression Profile

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#855]

**Comment by PavelBal** [comment]
@PavelBal Write down specification.

**Comment by rwmcintosh** [comment]
I think this only needs implementation in PK-Sim

**Comment by PavelBal** [comment]
> I think this only needs implementation in PK-Sim

@rwmcintosh Hm not sure. At least the presentation (additional tab) must be implemented in MoBi?

**Comment by rwmcintosh** [comment]
@PavelBal Is this written somewhere what should happen that you can link to?

**Comment by PavelBal** [comment]
Kinda... https://github.com/Open-Systems-Pharmacology/OSMOSES/blob/develop/Documentation/BuildingBlocks/ExpressionProfile.md If not sufficient - have to discuss.

**Comment by msevestre** [comment]
What additional tab are you talking about @PavelBal ?

**Comment by rwmcintosh** [comment]
He means to add a tab that contains the MSV's (or Initial Conditions) for the protein.
This is about editing convenience, grouping all the quantities for protein in one location for editing.

@PavelBal LMK if I have that right.

**Comment by PavelBal** [comment]
@rwmcintosh Yepp
