### ISSUE TITLE
Modeling ribbon implementation

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#888]
In the windows that are created from Create buttons, you need to select a module, or else remove the ribbon

**Comment by PavelBal** [comment]
Let's discuss if we want to remove some of the "new" buttons.

**Comment by rwmcintosh** [comment]
We will remove the 'New' buttons for building blocks. Ribbon still contains some buttons
https://github.com/open-systems-pharmacology/mobi/issues/889
