### ISSUE TITLE
Spatial Structure: Allow creation of neighborhood via UI (not drag and drop)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#898]
It should be possible to create neighborhoods by other means than drag-and-drop. E.g., a UI "Create neighborhood", where the user selects (or types in the full path to) the neighbors. In case of a tumor module, the user would select "PARENT|Tumor|Plasma" as one neighbor, and type in "Organism|VenousBlood|Plasma" as the second neighbor. the "PARENT" keyword is necessary as the path within the module is not complete. "PARENT" will be replaced by the container that is defined in the "Parent container" property.

![image](https://user-images.githubusercontent.com/1041237/219666231-9936fd49-281a-4d31-91fe-9a676de7545a.png)

**Comment by msevestre** [comment]
progressing
![image](https://user-images.githubusercontent.com/1041237/223907254-803396b1-9204-4f9e-85f7-eca72130f07f.png)

**Comment by PavelBal** [comment]
Looking good! 

But direct input of the path will also be supported, right?

**Comment by msevestre** [comment]
well If I enter a path such as VenBlood|Plasma (typo), I will accept it. So basically, we do not check anything? 
This is going to be all a massive change...damn

**Comment by PavelBal** [comment]
> So basically, we do not check anything?

This would be the expected behavior (not checking), because we could have a module that should create a neighborhood to a container that is maybe still not in the project (e.g., I have an extension module for tumor and it defines a neighborhood with venous blood, and open it in a project where I do not have a PK-Sim project yet).

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/224107873-e8215a2f-f9de-4c98-b6ba-75653c29901c.png)
