### ISSUE TITLE
Module Combination: Only one neighborhood between two containers

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#899]
Combining modules will overwrite neighborhoods with identical neighbors (i.e., matching of neighborhoods is performed by their neighbors and not by names). Deleting of neighborhoods is possible by defining them in the "Delete"-list of the SS BB.

comes from https://github.com/Open-Systems-Pharmacology/OSMOSES/blob/develop/Documentation/BuildingBlocks/SpatialStructures-BB.md

**Comment by PavelBal** [comment]
This is implemented in some way already.
