### ISSUE TITLE
Lots of exception thrown when opening a event building block

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#902]
![image](https://user-images.githubusercontent.com/1041237/219691290-d982b226-30a3-4894-8a75-28fdf03b2a08.png)

Is this new/ This makes opening the view very very slow in debug

**Comment by rwmcintosh** [comment]
@Yuri05 @georgeDaskalakis I'll unassign you guys while I investigate so you don't accidentally solve it while I'm fumbling around...
