### ISSUE TITLE
MoBi cannot handle observed data sets with only 1 point anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/MoBi#908]
When an observed data set contains only 1 data point and is added to a simulation: simulation cannot be runned anymore due to the error below:
![grafik](https://user-images.githubusercontent.com/25061876/221168481-81e053dc-2812-4631-a711-17b084e3ec0a.png)

Example: [Bug_Observed1P.zip](https://github.com/Open-Systems-Pharmacology/MoBi/files/10823577/Bug_Observed1P.zip)
![grafik](https://user-images.githubusercontent.com/25061876/221169583-af138882-9e94-48f5-bbc9-d149948ef364.png)

Seems to be the problem in MoBi only, PK-Sim works.
Also worked in MoBi v 11.0

**Comment by msevestre** [comment]
How can it work in MoBi but not in PKSim??

**Comment by msevestre** [comment]
This is because of the residual vs time plot not handling this properly, In MoBi this is done right at the beginning. PKSim on demand. Same problem in PKSim probably
