### ISSUE TITLE
After update to using theme in table, content is not readable anymore

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#926]
@rwmcintosh @Yuri05 
![image](https://user-images.githubusercontent.com/1041237/224508159-61a22395-3539-45ca-a93b-4e32c10ac247.png)

@rwmcintosh We need a way to specify that readonly cell are NOT using the theme. The changes introduces to satisfy dark mode are creating a lot of UX issues 

Another example
![image](https://user-images.githubusercontent.com/1041237/224508186-8a760d03-0301-46e8-b960-07c142a63869.png)

So either we can make the text more readable (in this case the gray is fine) or  we do something else. Right now, this is a regression IMO using the default theme

**Comment by rwmcintosh** [comment]
Is there any override colour for the text boxes happening? Eg. parent path? Those are readable. What we have now is just using the theme defaults in the grid so I would expect them to look the same.

**Comment by msevestre** [comment]
No idea. I noticed this issue on all grid however

**Comment by rwmcintosh** [comment]
It probably just needs a different foreground text color. I picked "Readonly  Text", but if we used the default text it will probably be darker in light theme and lighter in dark theme.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/225454044-c8605238-e6a9-41a1-821c-d7a4f288a81e.png)
lol

**Comment by Yuri05** [comment]
>lol

agree :)

**Comment by rwmcintosh** [comment]
Really stretching the "Read" of "**Read**Only".

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1933](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1933) via [**Zenhub**](https://www.zenhub.com/)
