### ISSUE TITLE
Neighborhood Edit: Do we need another view?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/MoBi#927]
@PavelBal @Yuri05 
Right now, when I click on a neighborhood, I see the usual container edit

![image](https://user-images.githubusercontent.com/1041237/224508440-44ff5a0c-49fa-4bfd-9576-614b67d98335.png)

I think this is a mistake because

1. the container and type and mode can be changed?!?
2. we do not see the first neighbor and second neighghbor (even more important now that we can edit them and can be anything)

I propose adding a custom view to show those two new  properties (readonly for now, we can decide if we allow edit, maybe when a neighborhood is not connected to anyone, why not. Otherwise, this is going to mess up the diagram)

Also should we add first and second neighbor somehow in the tree view as well?
![image](https://user-images.githubusercontent.com/1041237/224508538-68cb1db4-bbe7-4b15-95c1-ef5327d0f67c.png)
maybe as sub node or sthg? I added a tooltip yesterday but maybe we need more

**Comment by Yuri05** [comment]
Absolutely! Container type must be read only , neighbor paths must be shown and editable.
Showing the neighbors in the tree view would be great as well. Once shown, additional feature wish: navigate to the neighbors from there (e.g. right click on a neighbor in the tree view and "Navigate to")

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/225493709-6a037c02-4bd6-4499-ad6e-7df86d79397e.png)
Neighbor paths shown but not editable yet (not hard to do but a bit tedious). Everything takes a lot of time because of very poor engineering of some sections that I am finally starting to refactor

**Comment by msevestre** [comment]
Icons for neighbor will be changed obviously
ContainerType is gone. It has no meaning in this case

**Comment by Yuri05** [comment]
For the neighbors we could use the icons which correspond to the last path entry. E.g. in the above screenshot both neighbors would become the icon of "Blood cells"

**Comment by Yuri05** [comment]
By the way, should we define an icon for the "Molecule properties" contianers?
E.g. something like a combination of parameter table icon and molecule icon:
![grafik](https://user-images.githubusercontent.com/25061876/225590883-9a2044c3-5e97-4c70-b567-6c58f1a4d832.png)

**Comment by msevestre** [comment]
ye sI like the icon for molecue properties
However for the neighbors icon, I am not sure about the proposal. SOmetimes, the target won't exist. What should be the icon then?

**Comment by PavelBal** [comment]
Yes, implemented. Created a new issue for icons: https://github.com/Open-Systems-Pharmacology/MoBi/issues/1255
