### ISSUE TITLE
Find all TODO's created during OSMOSES

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#932]
This is a reminder to go back and search for TODO's in the code that were created during OSMOSES

Also, if you can, bullet TODO's below, or add as an issue in this epic

**Comment by Yuri05** [comment]
<details><summary><b>Easy 😄 </b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/226596764-59e5f163-a9fb-4852-bdfa-dd96d8487a3d.png)
</details>

**Comment by rwmcintosh** [comment]
There's always one of those guys in every crew

**Comment by rwmcintosh** [comment]
I found one ```TODO OSMOSES``` today, and fixed it. Searched for outstanding TODO in code and am satisfied that was the last one.
