### ISSUE TITLE
What will happen during clone and merge for module building blocks

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/MoBi#979]
Clone and merge workflows formerly added the result directly to a project. However, in OSMOSES, the resulting building blocks are not top-level members of a project (except Individual and Expression).

**Comment by msevestre** [comment]
What it this function??

**Comment by rwmcintosh** [comment]
There's some work to do on InteractionTasks hierarchy because all the BB interaction tasks define parent as MoBiProject. Most of them should use Module now instead since you add/remove them from a module, not a project. I started to split this into separate hierarchies, but this merge workflow just stands out as unnecessary.

![image](https://user-images.githubusercontent.com/261477/234549720-ac21a176-ca3f-49dc-848f-d2e899e7d556.png)


Similarly, do we clone BB's with Module parent anymore? Or clone modules and select which BB's are included in the clone?

**Comment by rwmcintosh** [comment]
Clone module -> open the selector with default all BB's selected, deslect those BB's that won't be cloned
Allow Start values cloning within the module.
