### ISSUE TITLE
Module has no name when importing a pkml simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/MoBi#999]
-	Export any simulation with PK-Sim V11.2 to pkml
-	Open Simulation created with V11.2 in MoBi OSMOSES
- The Module does not have any name. I would expect the name of the simulation here:
![image](https://github.com/Open-Systems-Pharmacology/MoBi/assets/25903040/053a0ac5-fb88-4963-9d75-b8aa4b5c073d)

**Comment by msevestre** [comment]
Agreed. I don't think that our naming of BB makes sense however. We do not need to name everything like the simulation. Giving name like observers or spatial structure would probably be easier to understand

**Comment by PavelBal** [comment]
Yes agreed. Only name the Module, the rest should be "Spatial Structures" etc, except for PV and IC.

**Comment by msevestre** [comment]
I would have said expect for expression and individual no? Why PSV and IC? They are still in the module

**Comment by PavelBal** [comment]
Ah ok, yes agree.

**Comment by rwmcintosh** [comment]
This is a two-parter, if I understand correctly.

Confirm that we are:
- renaming the building blocks and module during PKML conversion (in Core), thus renaming the building blocks for pre-V12 pkml files.
- changing the default building block names for simulation transfer export (in PK-Sim).
